id = "svelte"
match_suffixes = ["svelte"]

[language]
primary_ext = "svelte"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "svelte"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "ts"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = ".test"
extension = "ts"

[syntax]
top_level_keywords = ["<script", "export let ", "let ", "const "]
comment_prefixes = ["<!--", "//", "/*", "*"]

[[syntax.imports]]
starts_with = "import "

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
<script lang="ts">
// Implement your feature here.
</script>

<div><!-- Implement your feature here. --></div>
'''