id = "astro"
match_suffixes = ["astro"]

[language]
primary_ext = "astro"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "astro"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "ts"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = ".test"
extension = "ts"

[syntax]
top_level_keywords = ["---", "const ", "export ", "interface "]
comment_prefixes = ["<!--", "//", "/*", "*"]

[[syntax.imports]]
starts_with = "import "

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
---
// Implement your feature here.
---

<div><!-- Implement your feature here. --></div>
'''