id = "rails"
match_suffixes = ["rails"]

[language]
primary_ext = "rb"

[files.source]
strip_lang_ext = true
prefix = ""
suffix = ""
extension = "rb"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "rb"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = "_test"
extension = "rb"

[syntax]
top_level_keywords = ["class ", "module ", "def ", "scope ", "validates ", "before_action "]
comment_prefixes = ["#"]

[[syntax.imports]]
starts_with = "require "

[[syntax.imports]]
starts_with = "require_relative "

[scaffold]
fence_lang = "rb"
source_body = '''
# Implement your Rails feature here.
'''