// Generated by mds. Do not edit. Source: .mds/source/adapter.rs.md. Source-Hash: 05136421a26863e20c70f49e24d82354e0ae78fec856747d98a760c1e1ab5f9c.

use std::path::{Path};
use std::process::{Command as ProcessCommand};
use std::process::{Stdio};
use crate::{descriptor};
use crate::model::{ImplDoc};
use crate::model::{OutputKind};
