// Generated by mds. Do not edit. Source: .mds/source/config.rs.md. Source-Hash: e24eca6c06160a74f9551ef65f8cf1ac966e1275703780a66e1048a37371c094.

use std::fs;
use std::path::{Path, PathBuf};
use crate::diagnostics::{Diagnostic, RunState};
use crate::model::{Config, Lang};
