// Generated by mds. Do not edit. Source: mds/core/.mds/source/descriptor.rs.md. Source-Hash: 5772f46814216138a28063c677116920b0e4b6065bc340271573108448118857.

use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::model::{Lang, OutputKind};

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum OutputRoot {
    Package,
    Source,
    Types,
    Test,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct Descriptor {
    #[allow(dead_code)]
    pub id: String,
    pub language: LanguageSection,
    pub files: FileRules,
    #[serde(default)]
    pub special_files: Vec<SpecialFileRule>,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct SpecialFileRule {
    #[serde(rename = "match")]
    pub match_path: String,
    pub kind: String,
    pub output: String,
    #[serde(default)]
    pub root: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct LanguageSection {
    pub primary_ext: String,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct FileRules {
    pub source: FileRule,
    pub types: FileRule,
    pub test: FileRule,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct FileRule {
    #[serde(default)]
    pub strip_lang_ext: bool,
    #[serde(default)]
    pub prefix: String,
    #[serde(default)]
    pub suffix: String,
    pub extension: String,
}

impl Descriptor {
    pub fn file_rule(&self, kind: OutputKind) -> &FileRule {
        match kind {
            OutputKind::Source => &self.files.source,
            OutputKind::Types => &self.files.types,
            OutputKind::Test => &self.files.test,
        }
    }

    pub fn special_file_rule(&self, relative: &Path, kind: OutputKind) -> Option<&SpecialFileRule> {
        let relative = relative.to_string_lossy().replace('\\', "/");
        let kind = kind.manifest_kind();
        self.special_files
            .iter()
            .find(|rule| rule.match_path == relative && rule.kind == kind)
    }
}

impl SpecialFileRule {
    fn output_root(&self, kind: OutputKind) -> OutputRoot {
        match self.root.as_deref() {
            Some("package") => OutputRoot::Package,
            Some("source") => OutputRoot::Source,
            Some("types") => OutputRoot::Types,
            Some("test") => OutputRoot::Test,
            _ => match kind {
                OutputKind::Source => OutputRoot::Source,
                OutputKind::Types => OutputRoot::Types,
                OutputKind::Test => OutputRoot::Test,
            },
        }
    }
}

pub(crate) fn builtin_descriptor(lang: &Lang) -> Descriptor {
    let raw = match lang {
        Lang::TypeScript => include_str!("descriptors/ts.toml"),
        Lang::Python => include_str!("descriptors/py.toml"),
        Lang::Rust => include_str!("descriptors/rs.toml"),
        Lang::Other(ext) => panic!("no built-in descriptor for `{ext}`"),
    };
    toml::from_str(raw).expect("built-in descriptor must parse")
}

pub(crate) fn output_relative_path(relative: &Path, lang: &Lang, kind: OutputKind) -> PathBuf {
    let descriptor = builtin_descriptor(lang);
    if let Some(rule) = descriptor.special_file_rule(relative, kind) {
        return PathBuf::from(&rule.output);
    }
    let rule = descriptor.file_rule(kind);
    apply_file_rule(relative, &descriptor.language.primary_ext, rule)
}

pub(crate) fn output_root(relative: &Path, lang: &Lang, kind: OutputKind) -> OutputRoot {
    let descriptor = builtin_descriptor(lang);
    if let Some(rule) = descriptor.special_file_rule(relative, kind) {
        return rule.output_root(kind);
    }
    match kind {
        OutputKind::Source => OutputRoot::Source,
        OutputKind::Types => OutputRoot::Types,
        OutputKind::Test => OutputRoot::Test,
    }
}

fn apply_file_rule(relative: &Path, primary_ext: &str, rule: &FileRule) -> PathBuf {
    let stripped = strip_md_extension(relative);
    let parent = stripped.parent().map(PathBuf::from).unwrap_or_default();
    let file_name = stripped.file_name().unwrap_or_default().to_string_lossy();
    let target_suffix = format!(".{}", rule.extension);
    let base_without_target = file_name.strip_suffix(&target_suffix).unwrap_or(&file_name);
    let base = if rule.strip_lang_ext {
        let primary_suffix = format!(".{primary_ext}");
        base_without_target
            .strip_suffix(&primary_suffix)
            .unwrap_or(base_without_target)
    } else {
        base_without_target
    };
    let output_name = format!("{}{}{}.{}", rule.prefix, base, rule.suffix, rule.extension);
    parent.join(output_name)
}

fn strip_md_extension(path: &Path) -> PathBuf {
    let name = path.file_name().unwrap_or_default().to_string_lossy();
    let stripped = name.strip_suffix(".md").unwrap_or(&name);
    path.with_file_name(stripped)
}
