// Generated by mds. Do not edit. Source: .mds/source/descriptor.rs.md. Source-Hash: 684cd80f4883dfce845ca69658d353e5f1dc1b0c1410b0716619a4616c56b1f3.

use std::cell::RefCell;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::model::{Lang, OutputKind};

mod descriptor_registry {
    include!(concat!(env!("OUT_DIR"), "/descriptor_registry.rs"));
}

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum OutputRoot {
    Package,
    Source,
    Types,
    Test,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct Descriptor {
    #[allow(dead_code)]
    pub id: String,
    #[serde(default)]
    pub aliases: Vec<String>,
    #[serde(default)]
    pub match_suffixes: Vec<String>,
    pub language: LanguageSection,
    pub files: FileRules,
    #[serde(default)]
    pub special_files: Vec<SpecialFileRule>,
    #[serde(default)]
    pub syntax: SyntaxSection,
    #[serde(default)]
    pub scaffold: ScaffoldSection,
    #[serde(default)]
    pub tooling: ToolingSection,
    #[serde(default)]
    pub quality_defaults: QualityDefaults,
    #[serde(default)]
    pub tool_profiles: ToolProfiles,
}

#[derive(Debug, Clone)]
struct DescriptorRegistry {
    by_id: HashMap<String, Descriptor>,
    alias_to_id: HashMap<String, String>,
    suffix_to_id: Vec<(String, String)>,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct SpecialFileRule {
    #[serde(rename = "match")]
    pub match_path: String,
    pub kind: String,
    pub output: String,
    #[serde(default)]
    pub root: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct LanguageSection {
    pub primary_ext: String,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct FileRules {
    pub source: FileRule,
    pub types: FileRule,
    pub test: FileRule,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct FileRule {
    #[serde(default)]
    pub strip_lang_ext: bool,
    #[serde(default)]
    pub prefix: String,
    #[serde(default)]
    pub suffix: String,
    pub extension: String,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub(crate) struct SyntaxSection {
    #[serde(default)]
    pub imports: Vec<LinePattern>,
    #[serde(default)]
    pub top_level_keywords: Vec<String>,
    #[serde(default)]
    pub comment_prefixes: Vec<String>,
    #[serde(default)]
    pub doc_comment_prefixes: Vec<String>,
    #[serde(default)]
    pub doc_string_delimiters: Vec<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub(crate) struct LinePattern {
    pub starts_with: String,
    #[serde(default)]
    pub contains: Vec<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub(crate) struct ScaffoldSection {
    #[serde(default)]
    pub fence_lang: Option<String>,
    #[serde(default)]
    pub source_body: String,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub(crate) struct ToolingSection {
    #[serde(default)]
    pub lint: ToolBehavior,
    #[serde(default)]
    pub fix: ToolBehavior,
    #[serde(default)]
    pub test: ToolBehavior,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub(crate) struct QualityDefaults {
    #[serde(default)]
    pub lint: Option<String>,
    #[serde(default)]
    pub fix: Option<String>,
    #[serde(default)]
    pub test: Option<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub(crate) struct ToolProfiles {
    #[serde(default)]
    pub lint: HashMap<String, ToolProfile>,
    #[serde(default)]
    pub fix: HashMap<String, ToolProfile>,
    #[serde(default)]
    pub test: HashMap<String, ToolProfile>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub(crate) struct ToolProfile {
    pub command: String,
    #[serde(default)]
    pub required: Vec<String>,
    #[serde(default)]
    pub optional: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct ToolBehavior {
    #[serde(default = "default_input_mode")]
    pub input: String,
    #[serde(default = "default_output_mode")]
    pub output: String,
    #[serde(default)]
    pub append_file_arg: Option<bool>,
    #[serde(default)]
    pub diagnostics: Vec<DiagnosticCaptureRule>,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct DiagnosticCaptureRule {
    pub pattern: String,
    #[serde(default = "default_path_group")]
    pub path_group: String,
    #[serde(default = "default_line_group")]
    pub line_group: String,
    #[serde(default = "default_column_group")]
    pub column_group: String,
    #[serde(default = "default_message_group")]
    pub message_group: String,
    #[serde(default = "default_severity_value")]
    pub severity: String,
    #[serde(default)]
    pub line_offset: isize,
}

impl Default for ToolBehavior {
    fn default() -> Self {
        Self {
            input: default_input_mode(),
            output: default_output_mode(),
            append_file_arg: None,
            diagnostics: Vec::new(),
        }
    }
}

impl Descriptor {
    pub fn file_rule(&self, kind: OutputKind) -> &FileRule {
        match kind {
            OutputKind::Source => &self.files.source,
            OutputKind::Types => &self.files.types,
            OutputKind::Test => &self.files.test,
        }
    }

    pub fn special_file_rule(&self, relative: &Path, kind: OutputKind) -> Option<&SpecialFileRule> {
        let relative = relative.to_string_lossy().replace('\\', "/");
        let kind = kind.manifest_kind();
        self.special_files
            .iter()
            .find(|rule| rule.match_path == relative && rule.kind == kind)
    }

    pub fn matches_import_line(&self, trimmed_start: &str) -> bool {
        self.syntax
            .imports
            .iter()
            .any(|pattern| pattern.matches(trimmed_start))
    }

    pub fn matches_top_level_declaration(&self, line: &str) -> bool {
        self.syntax
            .top_level_keywords
            .iter()
            .any(|keyword| line.starts_with(keyword))
    }

    pub fn matches_comment_line(&self, trimmed: &str) -> bool {
        self.syntax
            .comment_prefixes
            .iter()
            .any(|prefix| trimmed.starts_with(prefix))
    }

    pub fn matches_doc_comment_line(&self, trimmed: &str) -> bool {
        self.syntax
            .doc_comment_prefixes
            .iter()
            .any(|prefix| trimmed.starts_with(prefix))
            || self
                .syntax
                .doc_string_delimiters
                .iter()
                .any(|delimiter| trimmed.starts_with(delimiter))
    }

    pub fn render_source_block(&self, matched_suffix: Option<&str>) -> String {
        let fence_lang = match self.scaffold.fence_lang.as_deref() {
            Some("matched-suffix") => matched_suffix.unwrap_or(&self.language.primary_ext),
            Some(value) if !value.is_empty() => value,
            _ => &self.language.primary_ext,
        };
        let body = if self.scaffold.source_body.trim().is_empty() {
            let prefix = self
                .syntax
                .comment_prefixes
                .first()
                .map(String::as_str)
                .unwrap_or("//");
            format!("{prefix} Implement your feature here.")
        } else {
            self.scaffold.source_body.trim_end().to_string()
        };
        format!("```{fence_lang}\n{body}\n```")
    }

    pub fn lint_behavior(&self) -> &ToolBehavior {
        &self.tooling.lint
    }

    pub fn fix_behavior(&self) -> &ToolBehavior {
        &self.tooling.fix
    }

    pub fn test_behavior(&self) -> &ToolBehavior {
        &self.tooling.test
    }

    pub fn default_lint_command(&self) -> Option<&str> {
        self.quality_defaults.lint.as_deref()
    }

    pub fn default_fix_command(&self) -> Option<&str> {
        self.quality_defaults.fix.as_deref()
    }

    pub fn default_test_command(&self) -> Option<&str> {
        self.quality_defaults.test.as_deref()
    }

    pub fn lint_profile(&self, key: &str) -> Option<&ToolProfile> {
        self.tool_profiles.lint.get(key)
    }

    pub fn fix_profile(&self, key: &str) -> Option<&ToolProfile> {
        self.tool_profiles.fix.get(key)
    }

    pub fn test_profile(&self, key: &str) -> Option<&ToolProfile> {
        self.tool_profiles.test.get(key)
    }

    fn all_match_suffixes(&self) -> Vec<&str> {
        let mut suffixes: Vec<&str> = self.match_suffixes.iter().map(String::as_str).collect();
        if !suffixes.contains(&self.language.primary_ext.as_str()) {
            suffixes.push(&self.language.primary_ext);
        }
        suffixes
    }
}

impl LinePattern {
    fn matches(&self, line: &str) -> bool {
        line.starts_with(&self.starts_with)
            && self.contains.iter().all(|needle| line.contains(needle))
    }
}

impl ToolBehavior {
    pub fn input_mode(&self) -> ToolInputMode {
        match self.input.as_str() {
            "stdin" => ToolInputMode::Stdin,
            "inline" => ToolInputMode::Inline,
            _ => ToolInputMode::TempFile,
        }
    }

    pub fn output_mode(&self) -> ToolOutputMode {
        match self.output.as_str() {
            "stdout" => ToolOutputMode::Stdout,
            "tempfile" => ToolOutputMode::TempFile,
            _ => ToolOutputMode::None,
        }
    }

    pub fn append_file_arg(&self) -> bool {
        self.append_file_arg
            .unwrap_or(matches!(self.input_mode(), ToolInputMode::TempFile))
    }
}

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum ToolInputMode {
    TempFile,
    Stdin,
    Inline,
}

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub(crate) enum ToolOutputMode {
    None,
    Stdout,
    TempFile,
}

fn default_input_mode() -> String {
    "tempfile".to_string()
}


fn default_output_mode() -> String {
    "none".to_string()
}


fn default_path_group() -> String {
    "path".to_string()
}


fn default_line_group() -> String {
    "line".to_string()
}


fn default_message_group() -> String {
    "message".to_string()
}


fn default_column_group() -> String {
    "column".to_string()
}


fn default_severity_value() -> String {
    "error".to_string()
}

impl DescriptorRegistry {
    fn descriptor_for_key(&self, key: &str) -> Option<&Descriptor> {
        let canonical = self.alias_to_id.get(key).map_or(key, String::as_str);
        self.by_id.get(canonical)
    }

    fn descriptor_for_markdown_name(&self, name: &str) -> Option<&Descriptor> {
        self.markdown_match(name).map(|(descriptor, _)| descriptor)
    }

    fn matched_markdown_suffix(&self, name: &str) -> Option<&str> {
        self.markdown_match(name).map(|(_, suffix)| suffix)
    }

    fn markdown_match(&self, name: &str) -> Option<(&Descriptor, &str)> {
        let without_md = name.strip_suffix(".md")?;
        for (suffix, id) in &self.suffix_to_id {
            let candidate = format!(".{suffix}");
            if without_md.ends_with(&candidate) {
                if let Some(descriptor) = self.by_id.get(id) {
                    return Some((descriptor, suffix.as_str()));
                }
            }
        }
        None
    }
}

impl SpecialFileRule {
    fn output_root(&self, kind: OutputKind) -> OutputRoot {
        match self.root.as_deref() {
            Some("package") => OutputRoot::Package,
            Some("source") => OutputRoot::Source,
            Some("types") => OutputRoot::Types,
            Some("test") => OutputRoot::Test,
            _ => match kind {
                OutputKind::Source => OutputRoot::Source,
                OutputKind::Types => OutputRoot::Types,
                OutputKind::Test => OutputRoot::Test,
            },
        }
    }
}

pub(crate) fn builtin_descriptor(lang: &Lang) -> Descriptor {
    descriptor_for_key(lang.key())
        .unwrap_or_else(|| panic!("no built-in descriptor for `{}`", lang.key()))
}

pub(crate) fn descriptor_for_key(key: &str) -> Option<Descriptor> {
    registry().descriptor_for_key(key).cloned()
}

pub(crate) fn descriptor_for_markdown_name(name: &str) -> Option<Descriptor> {
    registry().descriptor_for_markdown_name(name).cloned()
}

pub(crate) fn matched_markdown_suffix(name: &str) -> Option<String> {
    registry().matched_markdown_suffix(name).map(str::to_string)
}

pub fn set_workspace_descriptor_root(root: Option<&Path>) {
    DESCRIPTOR_ROOT.with(|storage| {
        *storage.borrow_mut() = root.map(Path::to_path_buf);
    });
}


fn registry() -> DescriptorRegistry {
    load_registry(active_descriptor_root().as_deref())
}


fn active_descriptor_root() -> Option<PathBuf> {
    let configured = DESCRIPTOR_ROOT.with(|storage| storage.borrow().clone());
    if configured.is_some() {
        return configured;
    }
    std::env::current_dir().ok()
}


thread_local! {
    static DESCRIPTOR_ROOT: RefCell<Option<PathBuf>> = const { RefCell::new(None) };
}


fn load_registry(root: Option<&Path>) -> DescriptorRegistry {
    let mut by_id = HashMap::new();
    let mut alias_to_id = HashMap::new();
    let mut suffix_to_id = Vec::new();

    for entry in descriptor_registry::BUILTIN_DESCRIPTORS {
        let descriptor: Descriptor =
            toml::from_str(entry.content).expect("built-in descriptor must parse");
        let id = descriptor.id.clone();
        register_alias(&mut alias_to_id, &id, &id);
        for alias in &descriptor.aliases {
            register_alias(&mut alias_to_id, alias, &id);
        }
        for suffix in descriptor.all_match_suffixes() {
            suffix_to_id.push((suffix.to_string(), id.clone()));
        }
        by_id.insert(id, descriptor);
    }

    if let Some(root) = root {
        let descriptors_root = root.join(".mds/descriptors");
        for descriptor in load_workspace_descriptors(&descriptors_root) {
            let id = descriptor.id.clone();
            register_alias(&mut alias_to_id, &id, &id);
            for alias in &descriptor.aliases {
                register_alias(&mut alias_to_id, alias, &id);
            }
            for suffix in descriptor.all_match_suffixes() {
                suffix_to_id.push((suffix.to_string(), id.clone()));
            }
            by_id.insert(id, descriptor);
        }
    }

    suffix_to_id.sort_by(|left, right| {
        right
            .0
            .len()
            .cmp(&left.0.len())
            .then_with(|| left.0.cmp(&right.0))
    });

    DescriptorRegistry {
        by_id,
        alias_to_id,
        suffix_to_id,
    }
}

fn register_alias(alias_to_id: &mut HashMap<String, String>, alias: &str, id: &str) {
    if let Some(existing) = alias_to_id.insert(alias.to_string(), id.to_string()) {
        assert_eq!(
            existing, id,
            "descriptor alias `{alias}` mapped to both `{existing}` and `{id}`"
        );
    }
}

fn load_workspace_descriptors(root: &Path) -> Vec<Descriptor> {
    let mut descriptors = Vec::new();
    for path in collect_descriptor_files(root) {
        let content = match fs::read_to_string(&path) {
            Ok(content) => content,
            Err(_) => continue,
        };
        let Ok(descriptor) = toml::from_str::<Descriptor>(&content) else {
            continue;
        };
        descriptors.push(descriptor);
    }
    descriptors
}

fn collect_descriptor_files(root: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    collect_descriptor_files_into(root, &mut files);
    files.sort();
    files
}

fn collect_descriptor_files_into(root: &Path, files: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    for entry in entries.filter_map(|entry| entry.ok()) {
        let path = entry.path();
        if path.is_dir() {
            collect_descriptor_files_into(&path, files);
            continue;
        }
        if path.extension().and_then(|value| value.to_str()) == Some("toml") {
            files.push(path);
        }
    }
}

pub(crate) fn output_relative_path(relative: &Path, lang: &Lang, kind: OutputKind) -> PathBuf {
    let descriptor = builtin_descriptor(lang);
    if let Some(rule) = descriptor.special_file_rule(relative, kind) {
        return PathBuf::from(&rule.output);
    }
    let rule = descriptor.file_rule(kind);
    apply_file_rule(relative, &descriptor.language.primary_ext, rule)
}

pub(crate) fn output_root(relative: &Path, lang: &Lang, kind: OutputKind) -> OutputRoot {
    let descriptor = builtin_descriptor(lang);
    if let Some(rule) = descriptor.special_file_rule(relative, kind) {
        return rule.output_root(kind);
    }
    match kind {
        OutputKind::Source => OutputRoot::Source,
        OutputKind::Types => OutputRoot::Types,
        OutputKind::Test => OutputRoot::Test,
    }
}

fn apply_file_rule(relative: &Path, primary_ext: &str, rule: &FileRule) -> PathBuf {
    let stripped = strip_md_extension(relative);
    let parent = stripped.parent().map(PathBuf::from).unwrap_or_default();
    let file_name = stripped.file_name().unwrap_or_default().to_string_lossy();
    let target_suffix = format!(".{}", rule.extension);
    let base_without_target = file_name.strip_suffix(&target_suffix).unwrap_or(&file_name);
    let base = if rule.strip_lang_ext {
        let primary_suffix = format!(".{primary_ext}");
        base_without_target
            .strip_suffix(&primary_suffix)
            .unwrap_or(base_without_target)
    } else {
        base_without_target
    };
    let output_name = format!("{}{}{}.{}", rule.prefix, base, rule.suffix, rule.extension);
    parent.join(output_name)
}

fn strip_md_extension(path: &Path) -> PathBuf {
    let name = path.file_name().unwrap_or_default().to_string_lossy();
    let stripped = name.strip_suffix(".md").unwrap_or(&name);
    path.with_file_name(stripped)
}
