// Generated by mds. Do not edit. Source: .mds/source/descriptor.rs.md. Source-Hash: f84ab503d6dc85c562cdd3082d2006be69b5e48dd8f04e67b87295b641ba780a.

use std::cell::{RefCell};
use std::collections::{HashMap};
use std::{fs};
use std::path::{Path};
use std::path::{PathBuf};
use serde::{Deserialize};
use crate::model::{Lang};
use crate::model::{OutputKind};
