// Generated by mds. Do not edit. Source: mds/core/.mds/source/diagnostics.rs.md. Source-Hash: bdd7b0783bff97b2202fa1aa0c2cf130474b32f6a4a6e749d2ad4e93e5cbb070.

use std::path::PathBuf;

#[derive(Debug, Clone, Copy, Eq, PartialEq)]

pub enum Severity {
    Warning,
    Error,
}

#[derive(Debug, Clone)]

pub struct Diagnostic {
    pub severity: Severity,
    pub path: Option<PathBuf>,
    pub line: Option<usize>,
    pub message: String,
}

impl Diagnostic {
    pub fn warning(path: Option<PathBuf>, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Warning,
            path,
            line: None,
            message: message.into(),
        }
    }

    pub fn error(path: Option<PathBuf>, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Error,
            path,
            line: None,
            message: message.into(),
        }
    }

    pub fn at_line(mut self, line: usize) -> Self {
        self.line = Some(line);
        self
    }

    pub fn render(&self) -> String {
        let level = match self.severity {
            Severity::Warning => "warning",
            Severity::Error => "error",
        };
        match (&self.path, self.line) {
            (Some(path), Some(line)) => {
                format!("{level}: {}:{line}: {}\n", path.display(), self.message)
            }
            (Some(path), None) => format!("{level}: {}: {}\n", path.display(), self.message),
            (None, _) => format!("{level}: {}\n", self.message),
        }
    }
}

#[derive(Debug, Default)]

pub struct RunState {
    pub stdout: String,
    pub diagnostics: Vec<Diagnostic>,
    pub generated: Vec<PathBuf>,
    pub environment_missing: bool,
}

impl RunState {
    pub fn has_errors(&self) -> bool {
        self.diagnostics
            .iter()
            .any(|diagnostic| diagnostic.severity == Severity::Error)
    }
}
