// Generated by mds. Do not edit. Source: .mds/source/doctor.rs.md. Source-Hash: 90b61835d7d180879c8160f07722b9388c6e695301608cbe5ebf2c971801bcce.

use std::process::Command as ProcessCommand;
use crate::adapter::tool_available;
use crate::diagnostics::{Diagnostic, RunState};
use crate::model::{DoctorFormat, Package};
