// Generated by mds. Do not edit. Source: .mds/source/lib.rs.md. Source-Hash: 0db696fa549490fa83ecfd0ef21f4a141cc80dd3c14193f70fda78e07d440bc8.

mod adapter;
pub mod config;
pub mod descriptor;
pub mod diagnostics;
mod diff;
mod doctor;
mod fs_utils;
mod generation;
mod hash;
mod init;
mod manifest;
pub mod markdown;
pub mod model;
mod new;
pub mod package;
mod package_sync;
mod quality;
mod runner;
pub mod table;

pub use diagnostics::{Diagnostic, RunState, Severity};
pub use model::{
    AgentKitCategory, AiTarget, BuildMode, CliRequest, CliResult, Command, Config, DocKind,
    DoctorFormat, GeneratedFile, GeneratedKind, ImplDoc, InitOptions, InitQualityCommands,
    InitTargetCategories, LabelPreset, Lang, MetadataKind, NewOptions, OutputKind, Package,
    PackageMetadata, PythonTool, QualityConfig, Roots, RustTool, TypeScriptTool,
};
pub use runner::execute;
