// Generated by mds. Do not edit. Source: .mds/source/manifest.rs.md. Source-Hash: 9c1f7f56637a0537dccf4f0ba7655edf981f2c97d3d0a14ef2d61c3878c4256b.

use std::{fs};
use std::path::{Component};
use std::path::{Path};
use crate::diagnostics::{Diagnostic};
use crate::diagnostics::{RunState};
use crate::hash::{sha256};
use crate::model::{GeneratedFile};
use crate::model::{GeneratedKind};
use crate::model::{ImplDoc};
use crate::model::{Package};
