// Generated by mds. Do not edit. Source: .mds/source/markdown.rs.md. Source-Hash: e966a0a91e61853a3f7d3240b8d39b0ca1259e84635a3ace7b3ad9bc69ad184f.

use std::collections::{HashMap};
use std::{fs};
use std::path::{Path};
use std::path::{PathBuf};
use crate::descriptor::{builtin_descriptor};
use crate::diagnostics::{Diagnostic};
use crate::diagnostics::{RunState};
use crate::fs_utils::{collect_files};
use crate::fs_utils::{is_excluded};
use crate::model::{DocKind};
use crate::model::{ImplDoc};
use crate::model::{Lang};
use crate::model::{Package};
use crate::table::{parse_table_with_labels};
