// Generated by mds. Do not edit. Source: .mds/source/markdown.rs.md. Source-Hash: 5b24b73052e456e89f720e09c0b02fd57b8fe7623cb8d70109b04eea87cf2092.

use std::collections::{HashMap};
use std::{fs};
use std::path::{Path};
use std::path::{PathBuf};
use crate::descriptor::{builtin_descriptor};
use crate::diagnostics::{Diagnostic};
use crate::diagnostics::{RunState};
use crate::fs_utils::{collect_files};
use crate::fs_utils::{is_excluded};
use crate::model::{DocKind};
use crate::model::{ImplDoc};
use crate::model::{Lang};
use crate::model::{Package};
use crate::table::{parse_table_with_labels};
pub fn load_implementation_docs(
    package: &Package,
    state: &mut RunState,
) -> Result<Vec<ImplDoc>, String> {
    let markdown_root = source_markdown_root(package);
    if !markdown_root.exists() {
        state.diagnostics.push(Diagnostic::error(
            Some(markdown_root),
            "markdown root does not exist",
        ));
        return Ok(Vec::new());
    }

    let mut docs = Vec::new();
    for path in collect_files(&markdown_root, false)? {
        if is_excluded(&package.root, &path, &package.config.excludes) {
            continue;
        }
        if is_template_asset_markdown(&path) {
            continue;
        }
        let Some(lang) = Lang::from_path(&path) else {
            continue;
        };
        if !package.config.adapters.get(&lang).copied().unwrap_or(true) {
            continue;
        }
        if let Some(doc) = parse_impl_doc(package, DocKind::Source, lang, &path, state) {
            docs.push(doc);
        }
    }
    docs.extend(load_test_docs(package, &docs, state)?);
    docs.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(docs)
}

fn load_test_docs(
    package: &Package,
    source_docs: &[ImplDoc],
    state: &mut RunState,
) -> Result<Vec<ImplDoc>, String> {
    let markdown_root = test_markdown_root(package);
    if !markdown_root.exists() {
        return Ok(Vec::new());
    }

    let mut docs = Vec::new();
    for path in collect_files(&markdown_root, false)? {
        if is_excluded(&package.root, &path, &package.config.excludes) || !is_test_doc(&path) {
            continue;
        }
        let Some(lang) = resolve_test_doc_lang(package, &path, source_docs, state) else {
            continue;
        };
        if let Some(doc) = parse_impl_doc(package, DocKind::Test, lang, &path, state) {
            docs.push(doc);
        }
    }
    Ok(docs)
}

fn is_template_asset_markdown(path: &Path) -> bool {
    path.extension().is_some_and(|ext| ext == "md")
        && path.components().any(|component| component.as_os_str() == "templates")
}

pub fn parse_impl_doc(
    package: &Package,
    doc_kind: DocKind,
    lang: Lang,
    path: &Path,
    state: &mut RunState,
) -> Option<ImplDoc> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(error) => {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!("failed to read implementation md: {error}"),
            ));
            return None;
        }
    };
    validate_impl_doc_structure(
        path,
        &text,
        &package.config.label_overrides,
        &package.config.check,
        state,
    );
    if package.config.check.markdown_links {

        validate_markdown_links(path, &text, state);
    }
    validate_code_block_boundaries(
        path,
        &lang,
        &text,
        &package.config.label_overrides,
        &package.config.check,
        state,
    );

    let sections = sections_with_labels(&text, &package.config.label_overrides);
    let imports_code = render_imports_section(
        sections.get("Imports"),
        path,
        &lang,
        &package.config.label_overrides,
        state,
    );
    let types_code = prepend_imports(&imports_code, code_from_section(sections.get("Types")));
    let source_code = prepend_imports(&imports_code, code_from_section(sections.get("Source")));
    let test_code = prepend_imports(&imports_code, code_from_section(sections.get("Test")));
    let covers = covers_from_section(sections.get("Covers"));

    let code = extract_all_code_blocks(&text);
    if package.config.check.code_blocks_required && code.trim().is_empty() {
        state.diagnostics.push(Diagnostic::error(
            Some(path.to_path_buf()),
            "implementation md requires at least one code block",
        ));
    }

    let package_relative_path = match path.strip_prefix(&package.root) {
        Ok(path) => path.to_path_buf(),
        Err(_) => path.to_path_buf(),
    };
    let markdown_relative_path = match path.strip_prefix(markdown_root_for(package, doc_kind)) {
        Ok(path) => path.to_path_buf(),
        Err(_) => path.to_path_buf(),
    };
    let normalized_input = normalized_input(path, &text);

    Some(ImplDoc {
        doc_kind,
        lang,
        path: path.to_path_buf(),
        package_relative_path,
        markdown_relative_path,
        code,
        types_code,
        source_code,
        test_code,
        covers,
        normalized_input,
    })
}

pub fn source_markdown_root(package: &Package) -> PathBuf {
    let fixed = package.root.join(".mds/source");
    if fixed.exists()
        && (has_source_impl_docs(&fixed)
            || !package.root.join(&package.config.roots.markdown).exists())
    {
        fixed
    } else {
        package.root.join(&package.config.roots.markdown)
    }
}

pub fn test_markdown_root(package: &Package) -> PathBuf {
    package.root.join(".mds/test")
}

fn markdown_root_for(package: &Package, doc_kind: DocKind) -> PathBuf {
    match doc_kind {
        DocKind::Source => source_markdown_root(package),
        DocKind::Test => test_markdown_root(package),
    }
}

fn has_source_impl_docs(root: &Path) -> bool {
    let Ok(files) = collect_files(root, false) else {
        return false;
    };
    files.into_iter().any(|path| {
        matches!(path.extension().and_then(|ext| ext.to_str()), Some("md"))
            && !matches!(
                path.file_name().and_then(|name| name.to_str()),
                Some("overview.md" | "index.md")
            )
    })
}

fn is_test_doc(path: &Path) -> bool {
    matches!(path.extension().and_then(|ext| ext.to_str()), Some("md"))
        && !matches!(
            path.file_name().and_then(|name| name.to_str()),
            Some("overview.md")
        )
}

fn resolve_test_doc_lang(
    package: &Package,
    path: &Path,
    source_docs: &[ImplDoc],
    state: &mut RunState,
) -> Option<Lang> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(error) => {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!("failed to read test md: {error}"),
            ));
            return None;
        }
    };
    let sections = sections_with_labels(&text, &package.config.label_overrides);
    let covers = covers_from_section(sections.get("Covers"));
    if covers.is_empty() {
        state.diagnostics.push(Diagnostic::error(
            Some(path.to_path_buf()),
            "test md requires at least one Covers entry",
        ));
        return None;
    }

    let mut lang = None;
    for cover in covers {
        let matches = source_docs
            .iter()
            .filter(|doc| cover_matches(doc, &cover))
            .collect::<Vec<_>>();
        match matches.as_slice() {
            [] => {
                state.diagnostics.push(Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!("test md Covers entry `{cover}` does not resolve to a source md"),
                ));
                return None;
            }
            [doc] => {
                if let Some(current) = &lang {
                    if current != &doc.lang {
                        state.diagnostics.push(Diagnostic::error(
                            Some(path.to_path_buf()),
                            "test md Covers entries must resolve to source docs of the same language",
                        ));
                        return None;
                    }
                } else {
                    lang = Some(doc.lang.clone());
                }
            }
            _ => {
                state.diagnostics.push(Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!("test md Covers entry `{cover}` resolves ambiguously"),
                ));
                return None;
            }
        }
    }

    lang
}

fn cover_matches(doc: &ImplDoc, cover: &str) -> bool {
    let cover = cover.trim();
    cover == logical_module_id(&doc.markdown_relative_path)
        || cover == doc.markdown_relative_path.to_string_lossy()
}

fn logical_module_id(path: &Path) -> String {
    let value = path.to_string_lossy().replace('\\', "/");
    let value = value.strip_suffix(".md").unwrap_or(&value);
    if let Some(index) = value.rfind('.') {
        value[..index].to_string()
    } else {
        value.to_string()
    }
}

fn validate_impl_doc_structure(
    path: &Path,
    text: &str,
    label_overrides: &HashMap<String, String>,
    check: &crate::model::CheckConfig,
    state: &mut RunState,
) {
    if check.code_fence_integrity {
        validate_code_fence_integrity(path, text, state);
    }
    if check.duplicate_h2_sections {
        validate_duplicate_h2_sections(path, text, label_overrides, state);
    }
}

fn validate_code_fence_integrity(path: &Path, text: &str, state: &mut RunState) {
    let mut fence_len: Option<usize> = None;
    let mut fence_start_line = 0usize;
    for (line_index, line) in text.lines().enumerate() {
        let Some((marker_len, suffix)) = backtick_fence(line) else {
            continue;
        };
        if let Some(open_len) = fence_len {
            if is_closing_fence(marker_len, suffix, open_len) {
                fence_len = None;
                fence_start_line = 0;
            } else if marker_len >= open_len {
                state.diagnostics.push(Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!(
                        "code fence opened at line {} is not closed before a new fence opener at line {}",
                        fence_start_line,
                        line_index + 1
                    ),
                ));
                fence_len = Some(marker_len);
                fence_start_line = line_index + 1;
            }
        } else {
            fence_len = Some(marker_len);
            fence_start_line = line_index + 1;
        }
    }
    if fence_len.is_some() {
        state.diagnostics.push(Diagnostic::error(
            Some(path.to_path_buf()),
            format!("unterminated code fence opened at line {fence_start_line}"),
        ));
    }
}

fn validate_duplicate_h2_sections(
    path: &Path,
    text: &str,
    label_overrides: &HashMap<String, String>,
    state: &mut RunState,
) {
    let mut first_seen = HashMap::new();
    let mut fence_len: Option<usize> = None;
    for (line_index, line) in text.lines().enumerate() {
        if let Some((marker_len, suffix)) = backtick_fence(line) {
            if let Some(open_len) = fence_len {
                if is_closing_fence(marker_len, suffix, open_len) {
                    fence_len = None;
                }
            } else {
                fence_len = Some(marker_len);
            }
            continue;
        }
        if fence_len.is_some() {
            continue;
        }
        let Some(title) = line.strip_prefix("## ") else {
            continue;
        };
        let canonical = canonical_section_title(title.trim(), label_overrides);
        if let Some(first_line) = first_seen.insert(canonical.clone(), line_index + 1) {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!(
                    "duplicate H2 section `{canonical}`: first defined at line {first_line}, repeated at line {}",
                    line_index + 1
                ),
            ));
        }
    }
}

pub fn extract_all_code_blocks(text: &str) -> String {
    let mut fence_len: Option<usize> = None;
    let mut current = String::new();
    let mut blocks = Vec::new();
    for line in text.lines() {
        if let Some((marker_len, suffix)) = backtick_fence(line) {
            if let Some(open_len) = fence_len {
                if !is_closing_fence(marker_len, suffix, open_len) {
                    current.push_str(line);
                    current.push('\n');
                    continue;
                }
                blocks.push(current.trim_end_matches(['\r', '\n']).to_string());
                current.clear();
                fence_len = None;
            } else {
                fence_len = Some(marker_len);
            }
            continue;
        }
        if fence_len.is_some() {
            current.push_str(line);
            current.push('\n');
        }
    }
    if blocks.is_empty() {
        String::new()
    } else {
        blocks.join("\n\n") + "\n"
    }
}

fn code_from_section(section: Option<&String>) -> String {
    section
        .map(|section| {
            let blocks = extract_all_code_blocks(section);
            if !blocks.trim().is_empty() {
                blocks
            } else {
                code_from_table(section)
            }
        })
        .unwrap_or_default()
}

fn prepend_imports(imports: &str, body: String) -> String {
    if imports.trim().is_empty() {
        return body;
    }
    if body.trim().is_empty() {
        return String::new();
    }
    format!("{}\n{}", imports.trim_end(), body)
}

fn render_imports_section(
    section: Option<&String>,
    path: &Path,
    lang: &Lang,
    label_overrides: &HashMap<String, String>,
    state: &mut RunState,
) -> String {
    let Some(section) = section else {
        return String::new();
    };
    let Some(rows) = parse_table_with_labels(
        section,
        &["From", "Target", "Symbols", "Via", "Summary", "Reference"],
        path,
        label_overrides,
        state,
    ) else {
        return String::new();
    };

    let descriptor = builtin_descriptor(lang);
    let mut output = String::new();
    for row in rows {
        let Some(statement) = descriptor.render_import(&row) else {
            continue;
        };
        output.push_str(&statement);
        output.push('\n');
    }
    output
}

fn code_from_table(section: &str) -> String {
    let lines: Vec<&str> = section.lines().collect();
    for index in 0..lines.len().saturating_sub(1) {
        if !lines[index].trim_start().starts_with('|') || !lines[index + 1].contains("---") {
            continue;
        }
        let headers = split_markdown_row(lines[index]);
        let Some(code_index) = headers
            .iter()
            .position(|header| header.trim().eq_ignore_ascii_case("statement"))
        else {
            continue;
        };
        let mut output = String::new();
        for row_line in lines.iter().skip(index + 2) {
            if !row_line.trim_start().starts_with('|') {
                break;
            }
            let cells = split_markdown_row(row_line);
            let value = cells
                .get(code_index)
                .map(String::as_str)
                .unwrap_or_default()
                .trim()
                .trim_matches('`');
            if value.is_empty() {
                continue;
            }
            output.push_str(value);
            output.push('\n');
        }
        return output;
    }
    String::new()
}

fn split_markdown_row(line: &str) -> Vec<String> {
    line.trim()
        .trim_matches('|')
        .split('|')
        .map(|cell| cell.trim().to_string())
        .collect()
}

fn covers_from_section(section: Option<&String>) -> Vec<String> {
    section
        .map(|section| {
            section
                .lines()
                .map(|line| line.trim().trim_start_matches(['-', '*']).trim())
                .filter(|line| !line.is_empty())
                .map(ToOwned::to_owned)
                .collect()
        })
        .unwrap_or_default()
}

fn validate_code_block_boundaries(
    path: &Path,
    lang: &Lang,
    text: &str,
    label_overrides: &HashMap<String, String>,
    check: &crate::model::CheckConfig,
    state: &mut RunState,
) {
    for block in code_blocks(text, label_overrides) {
        if check.doc_comments_outside_code {
            if let Some(line_offset) = block
                .content
                .lines()
                .position(|line| is_doc_comment_line(lang, line.trim_start()))
            {
                let line_number = block.start_line + line_offset;
                state.diagnostics.push(Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!(
                        "code block starting at line {} contains a doc comment at line {}; move documentation text outside the code block",
                        block.start_line,
                        line_number
                    ),
                ));
            }
        }

        let has_import = if check.import_with_implementation {
            block
                .content
                .lines()
                .any(|line| is_import_line(lang, line.trim_start()))
        } else {
            false
        };
        let declaration_count = if check.import_with_implementation || check.top_level_fence_required {
            top_level_declaration_count(lang, block.content)
        } else {
            0
        };
        let import_only_block = has_import
            && block.content.lines().all(|line| {
                let trimmed = line.trim_start();
                trimmed.is_empty()
                    || is_comment_line(lang, trimmed)
                    || is_import_line(lang, trimmed)
            });
        if check.import_with_implementation && has_import && declaration_count > 0 {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!(
                    "code block starting at line {} mixes imports with implementation; move imports to the Imports section table",
                    block.start_line
                ),
            ));
        }

        if import_only_block && block.section.as_deref() != Some("Imports") {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!(
                    "code block starting at line {} is an import-only block; move imports to the Imports section table",
                    block.start_line
                ),
            ));
        }

        if check.top_level_fence_required && declaration_count > 1 {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!(
                    "code block starting at line {} contains multiple top-level implementations; split each logical unit into its own code block",
                    block.start_line
                ),
            ));
        }
    }
}

#[derive(Debug)]
struct CodeBlock<'a> {
    content: &'a str,
    start_line: usize,
    section: Option<String>,
}

fn code_blocks<'a>(
    text: &'a str,
    label_overrides: &HashMap<String, String>,
) -> Vec<CodeBlock<'a>> {
    let mut blocks = Vec::new();
    let mut fence_len: Option<usize> = None;
    let mut content_start = 0;
    let mut content_start_line = 1;
    let mut cursor = 0;
    let mut line_number = 1;
    let mut current_section: Option<String> = None;
    for line in text.split_inclusive('\n') {
        let line_start = cursor;
        cursor += line.len();
        if fence_len.is_none() {
            if let Some(title) = line.trim_end_matches(['\r', '\n']).strip_prefix("## ") {
                current_section = Some(canonical_section_title(title.trim(), label_overrides));
            }
        }
        if let Some((marker_len, suffix)) = backtick_fence(line) {
            if let Some(open_len) = fence_len {
                if is_closing_fence(marker_len, suffix, open_len) {
                    blocks.push(CodeBlock {
                        content: &text[content_start..line_start],
                        start_line: content_start_line,
                        section: current_section.clone(),
                    });
                    fence_len = None;
                }
            } else {
                fence_len = Some(marker_len);
                content_start = cursor;
                content_start_line = line_number + 1;
            }
        }
        line_number += 1;
    }
    blocks
}

fn is_import_line(lang: &Lang, trimmed_start: &str) -> bool {
    crate::descriptor::builtin_descriptor(lang).matches_import_line(trimmed_start)
}

fn is_top_level_declaration(lang: &Lang, line: &str) -> bool {
    if line.trim_start() != line {
        return false;
    }
    let trimmed = line.trim_start();
    if trimmed.is_empty() || is_comment_line(lang, trimmed) || is_import_line(lang, trimmed) {
        return false;
    }
    crate::descriptor::builtin_descriptor(lang).matches_top_level_declaration(trimmed)
}

fn is_comment_line(lang: &Lang, trimmed: &str) -> bool {
    crate::descriptor::builtin_descriptor(lang).matches_comment_line(trimmed)
}

fn is_doc_comment_line(lang: &Lang, trimmed: &str) -> bool {
    crate::descriptor::builtin_descriptor(lang).matches_doc_comment_line(trimmed)
}

fn backtick_fence(line: &str) -> Option<(usize, &str)> {
    let trimmed = line.trim_start();
    let count = trimmed.chars().take_while(|char| *char == '`').count();
    (count >= 3).then_some((count, &trimmed[count..]))
}

fn is_closing_fence(marker_len: usize, suffix: &str, open_len: usize) -> bool {
    marker_len >= open_len && suffix.trim().is_empty()
}

pub fn sections_with_labels(
    text: &str,
    label_overrides: &HashMap<String, String>,
) -> HashMap<String, String> {
    let mut result = HashMap::new();
    let mut current: Option<String> = None;
    let mut body = String::new();
    for line in text.lines() {
        if let Some(title) = line.strip_prefix("## ") {
            let title = canonical_section_title(title.trim(), label_overrides);
            if let Some(name) = current.replace(title) {
                result.insert(name, body.trim_matches('\n').to_string());
                body.clear();
            }
        } else if current.is_some() {
            body.push_str(line);
            body.push('\n');
        }
    }
    if let Some(name) = current {
        result.insert(name, body.trim_matches('\n').to_string());
    }
    result
}

fn canonical_section_title(title: &str, label_overrides: &HashMap<String, String>) -> String {
    for canonical in [
        "Purpose", "Contract", "Types", "Source", "Cases", "Test", "Covers", "Imports", "Exports", "Expose", "Exposes", "Architecture", "Rules",
    ] {
        if title == canonical {
            return canonical.to_string();
        }
        let key = canonical.to_ascii_lowercase();
        if label_overrides
            .get(&key)
            .is_some_and(|override_label| override_label.trim() == title)
        {
            return canonical.to_string();
        }
    }
    title.to_string()
}

pub fn normalized_input(path: &Path, text: &str) -> String {
    let mut normalized = path.display().to_string();
    normalized.push('\n');
    normalized.push_str(text.replace("\r\n", "\n").trim_end());
    normalized.push('\n');
    normalized
}

pub fn validate_markdown_links(path: &Path, text: &str, state: &mut RunState) {
    let link_text = text_without_code_blocks(text);
    for target in standard_markdown_links(&link_text)
        .into_iter()
        .chain(wikilinks(&link_text))
    {
        if !should_validate_local_link(&target) {
            continue;
        }
        let clean_target = target
            .split('#')
            .next()
            .unwrap_or_default()
            .trim()
            .trim_matches('<')
            .trim_matches('>');
        if clean_target.is_empty() {
            continue;
        }
        let target_path = path
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join(clean_target);
        if !target_path.exists() {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!("Markdown link target does not exist: `{target}`"),
            ));
        }
    }
}

fn top_level_declaration_count(lang: &Lang, content: &str) -> usize {
    let declarations: Vec<&str> = content
        .lines()
        .filter(|line| is_top_level_declaration(lang, line))
        .collect();
    if declarations.is_empty() {
        return 0;
    }
    if declarations.iter().all(|line| is_module_declaration(line)) {
        return 1;
    }
    declarations.len()
}

fn is_module_declaration(line: &str) -> bool {
    line.starts_with("mod ") || line.starts_with("pub mod ")
}

fn text_without_code_blocks(text: &str) -> String {
    let mut output = String::new();
    let mut fence_len: Option<usize> = None;
    for line in text.lines() {
        if let Some((marker_len, suffix)) = backtick_fence(line) {
            if let Some(open_len) = fence_len {
                if is_closing_fence(marker_len, suffix, open_len) {
                    fence_len = None;
                }
            } else {
                fence_len = Some(marker_len);
            }
            continue;
        }
        if fence_len.is_none() {
            output.push_str(line);
            output.push('\n');
        }
    }
    output
}

fn standard_markdown_links(text: &str) -> Vec<String> {
    let mut links = Vec::new();
    let bytes = text.as_bytes();
    let mut idx = 0;
    while idx < bytes.len() {
        if bytes[idx] != b'[' {
            idx += 1;
            continue;
        }
        let Some(close_text) = text[idx + 1..].find(']') else {
            break;
        };
        let open_target = idx + close_text + 2;
        if bytes.get(open_target) != Some(&b'(') {
            idx += 1;
            continue;
        }
        let Some(close_target) = text[open_target + 1..].find(')') else {
            break;
        };
        links.push(text[open_target + 1..open_target + 1 + close_target].to_string());
        idx = open_target + close_target + 2;
    }
    links
}

fn wikilinks(text: &str) -> Vec<String> {
    let mut links = Vec::new();
    let mut rest = text;
    while let Some(start) = rest.find("[[") {
        rest = &rest[start + 2..];
        let Some(end) = rest.find("]]") else {
            break;
        };
        let target = rest[..end]
            .split('|')
            .next()
            .unwrap_or_default()
            .trim()
            .to_string();
        links.push(target);
        rest = &rest[end + 2..];
    }
    links
}

fn should_validate_local_link(target: &str) -> bool {
    let target = target.trim();
    if target.is_empty()
        || target.starts_with('#')
        || target.starts_with("http://")
        || target.starts_with("https://")
        || target.starts_with("mailto:")
    {
        return false;
    }
    let clean = target.split('#').next().unwrap_or_default();
    clean.ends_with(".md") || clean.contains('/')
}
