// Generated by mds. Do not edit. Source: .mds/source/package.rs.md. Source-Hash: d54c367b35b23e68a8ed35c3c172faaf166394a8fc7d189649b3f478a4a066ff.

use std::collections::{HashMap};
use std::collections::{HashSet};
use std::ffi::{OsStr};
use std::{fs};
use std::path::{Path};
use regex::{Regex};
use crate::config::{merge_config_file};
use crate::{descriptor};
use crate::diagnostics::{Diagnostic};
use crate::diagnostics::{RunState};
use crate::fs_utils::{collect_files};
use crate::fs_utils::{is_excluded};
use crate::markdown::{sections_with_labels};
use crate::markdown::{source_markdown_root};
use crate::markdown::{validate_markdown_links};
use crate::model::{Package};
use crate::model::{PackageMetadata};
use crate::table::{parse_table_with_labels};
