// Generated by mds. Do not edit. Source: .mds/source/package_sync.rs.md. Source-Hash: c86999b8799383bdbc1ca744c9629dd854e7ae04d23879a56f756221465d225b.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use crate::diagnostics::{Diagnostic, RunState};
use crate::diff::unified_diff;
use crate::model::Package;
use crate::package::read_package_metadata;
