// Generated by mds. Do not edit. Source: .mds/source/quality.rs.md. Source-Hash: a75d56e58316303e769fbf90b33edfe3d7da16e20e4b4dcddd2f9b808ffed40a.

use regex::Regex;
use std::fs;
use std::path::PathBuf;
use crate::adapter::{
path_variants, replace_path_variants, run_toolchain_command, tool_available,
tool_output_detail, ToolInvocation, ToolRunOutput, ToolRunStatus,
};
use crate::descriptor::{self, ToolBehavior, ToolInputMode, ToolOutputMode};
use crate::diagnostics::{Diagnostic, RunState};
use crate::diff::unified_diff;
use crate::fs_utils::is_excluded;
use crate::model::{ImplDoc, Lang, Package};
