// Generated by mds. Do not edit. Source: .mds/source/quality.rs.md. Source-Hash: d9d297ef40748373a66d07175fe4eaba9fb5a855a407fcea3e97fb480f4210d0.

use regex::Regex;
use std::fs;
use std::path::PathBuf;

use crate::adapter::{
    path_variants, replace_path_variants, run_toolchain_command, tool_available,
    tool_output_detail, ToolInvocation, ToolRunOutput, ToolRunStatus,
};
use crate::descriptor::{self, ToolBehavior, ToolInputMode, ToolOutputMode};
use crate::diagnostics::{Diagnostic, RunState};
use crate::diff::unified_diff;
use crate::fs_utils::is_excluded;
use crate::model::{ImplDoc, Lang, Package};

#[derive(Debug, Clone, Copy)]

pub(crate) enum QualityOperation {
    Lint,
    Fix { check: bool },
    Test,
}

pub(crate) fn run_quality(
    package: &Package,
    docs: &[ImplDoc],
    operation: QualityOperation,
    state: &mut RunState,
) -> Result<(), String> {
    match operation {
        QualityOperation::Lint | QualityOperation::Test => {
            let mut any_configured = false;
            for doc in docs {
                if has_quality_config(package, doc, operation) {
                    any_configured = true;
                }
                run_doc_quality(package, doc, operation, state)?;
            }
            if !any_configured && !docs.is_empty() {
                let name = match operation {
                    QualityOperation::Lint => "lint",
                    QualityOperation::Test => "test",
                    QualityOperation::Fix { .. } => unreachable!(),
                };
                state.stdout.push_str(&format!(
                    "warning: no {name} tool configured in mds.config.toml [quality.*]; skipping\n"
                ));
            }
            if !state.has_errors() && !state.environment_missing {
                let name = match operation {
                    QualityOperation::Lint => "lint",
                    QualityOperation::Test => "test",
                    QualityOperation::Fix { .. } => unreachable!(),
                };
                state.stdout.push_str(&format!("{name} ok\n"));
            }
        }
        QualityOperation::Fix { check } => {
            let mut any_configured = false;
            for doc in docs {
                if package
                    .config
                    .quality
                    .get(&doc.lang)
                    .and_then(|c| c.fix.as_ref())
                    .is_some()
                {
                    any_configured = true;
                }
                fix_doc(package, doc, check, state)?;
            }
            if !any_configured && !docs.is_empty() {
                state.stdout.push_str(
                    "warning: no fix tool configured in mds.config.toml [quality.*]; skipping\n",
                );
            }
            if !state.has_errors() && !state.environment_missing {
                state.stdout.push_str("lint --fix ok\n");
            }
        }
    }
    Ok(())
}

fn has_quality_config(package: &Package, doc: &ImplDoc, operation: QualityOperation) -> bool {
    let Some(config) = package.config.quality.get(&doc.lang) else {
        return false;
    };
    match operation {
        QualityOperation::Lint => config.lint.is_some(),
        QualityOperation::Test => config.test.is_some(),
        QualityOperation::Fix { .. } => config.fix.is_some(),
    }
}

fn run_doc_quality(
    package: &Package,
    doc: &ImplDoc,
    operation: QualityOperation,
    state: &mut RunState,
) -> Result<(), String> {
    let descriptor = descriptor::builtin_descriptor(&doc.lang);
    let Some(config) = package.config.quality.get(&doc.lang) else {
        return Ok(());
    };
    let command = match operation {
        QualityOperation::Lint => config.lint.as_deref(),
        QualityOperation::Test => config.test.as_deref(),
        QualityOperation::Fix { .. } => None,
    };
    let Some(command) = command else {
        return Ok(());
    };
    let source = padded_code_from_markdown(doc)?;
    let behavior = resolve_tool_behavior(&descriptor, operation, command);
    let _ = execute_quality_command(package, doc, command, config, &behavior, &source, state)?;
    Ok(())
}

fn fix_doc(
    package: &Package,
    doc: &ImplDoc,
    check: bool,
    state: &mut RunState,
) -> Result<(), String> {
    let descriptor = descriptor::builtin_descriptor(&doc.lang);
    let Some(config) = package.config.quality.get(&doc.lang) else {
        return Ok(());
    };
    let Some(command) = config.fix.as_deref() else {
        return Ok(());
    };
    let behavior = resolve_tool_behavior(&descriptor, QualityOperation::Fix { check }, command);
    let old = fs::read_to_string(&doc.path)
        .map_err(|error| format!("failed to read {}: {error}", doc.path.display()))?;
    let mut replacements = Vec::new();
    for block in code_block_ranges(&old) {
        if let Some(fixed) = execute_quality_command(
            package,
            doc,
            command,
            config,
            &behavior,
            block.content,
            state,
        )? {
            replacements.push((block.start, block.end, fixed));
        }
    }
    let new = apply_replacements(&old, &replacements);
    if old != new {
        state.stdout.push_str(&unified_diff(&doc.path, &old, &new));
        if check {
            state.diagnostics.push(Diagnostic::error(
                Some(doc.path.clone()),
                "lint --fix --check found code block changes",
            ));
        } else {
            fs::write(&doc.path, new)
                .map_err(|error| format!("failed to write {}: {error}", doc.path.display()))?;
            state.generated.push(doc.path.clone());
        }
    }
    Ok(())
}

fn resolve_tool_behavior(
    descriptor: &descriptor::Descriptor,
    operation: QualityOperation,
    command: &str,
) -> ToolBehavior {
    descriptor::tool_behavior_for_command(command).unwrap_or_else(|| match operation {
        QualityOperation::Lint => descriptor.lint_behavior().clone(),
        QualityOperation::Test => descriptor.test_behavior().clone(),
        QualityOperation::Fix { .. } => descriptor.fix_behavior().clone(),
    })
}

fn execute_quality_command(
    package: &Package,
    doc: &ImplDoc,
    command: &str,
    config: &crate::model::QualityConfig,
    behavior: &ToolBehavior,
    source: &str,
    state: &mut RunState,
) -> Result<Option<String>, String> {
    let path = temp_code_path(package, &doc.lang);
    if needs_tempfile(behavior) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&path, source)
            .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    }

    let file_arg = behavior.append_file_arg().then_some(path.as_path());
    let stdin = match behavior.input_mode() {
        ToolInputMode::Stdin => Some(source),
        ToolInputMode::TempFile | ToolInputMode::Inline => None,
    };
    let inline_arg = match behavior.input_mode() {
        ToolInputMode::Inline => Some(source),
        ToolInputMode::TempFile | ToolInputMode::Stdin => None,
    };

    let status = run_toolchain_command(ToolInvocation {
        command,
        file_arg,
        cwd: &package.root,
        stdin,
        inline_arg,
    })?;

    warn_missing_optional_tools(config, &doc.path, state);

    match status {
        ToolRunStatus::EmptyCommand => Ok(None),
        ToolRunStatus::MissingTool(program) => {
            state.environment_missing = true;
            state.diagnostics.push(Diagnostic::error(
                Some(doc.path.clone()),
                format!(
                    "LINT001_TOOLCHAIN_FAILED: required toolchain `{program}` is not available"
                ),
            ));
            Ok(None)
        }
        ToolRunStatus::Completed(output) => {
            if !output.success {
                report_tool_failure(&output, behavior, &doc.path, &path, &package.root, state)?;
                return Ok(None);
            }
            let fixed = match behavior.output_mode() {
                ToolOutputMode::None => None,
                ToolOutputMode::Stdout => Some(output.stdout),
                ToolOutputMode::TempFile => Some(
                    fs::read_to_string(&path)
                        .map_err(|error| format!("failed to read {}: {error}", path.display()))?,
                ),
            };
            Ok(fixed)
        }
    }
}

fn warn_missing_optional_tools(
    config: &crate::model::QualityConfig,
    path: &std::path::Path,
    state: &mut RunState,
) {
    for optional in &config.optional {
        if !tool_available(optional) {
            state.diagnostics.push(Diagnostic::warning(
                Some(path.to_path_buf()),
                format!("optional toolchain `{optional}` is not available"),
            ));
        }
    }
}

fn report_tool_failure(
    output: &ToolRunOutput,
    behavior: &ToolBehavior,
    markdown_path: &std::path::Path,
    input_path: &std::path::Path,
    cwd: &std::path::Path,
    state: &mut RunState,
) -> Result<(), String> {
    let detail = tool_output_detail(output);
    let diagnostics = capture_tool_diagnostics(&detail, behavior, markdown_path, input_path, cwd)?;
    if diagnostics.is_empty() {
        let rendered = replace_path_variants(&detail, input_path, markdown_path, cwd);
        state.diagnostics.push(Diagnostic::error(
            Some(markdown_path.to_path_buf()),
            format!("LINT001_TOOLCHAIN_FAILED: toolchain command failed: {rendered}"),
        ));
        return Ok(());
    }
    state.diagnostics.extend(diagnostics);
    Ok(())
}

fn capture_tool_diagnostics(
    detail: &str,
    behavior: &ToolBehavior,
    markdown_path: &std::path::Path,
    input_path: &std::path::Path,
    cwd: &std::path::Path,
) -> Result<Vec<Diagnostic>, String> {
    let mut diagnostics = Vec::new();
    for raw_line in detail.lines().filter(|line| !line.trim().is_empty()) {
        for rule in &behavior.diagnostics {
            let regex = Regex::new(&rule.pattern)
                .map_err(|error| format!("invalid diagnostic regex `{}`: {error}", rule.pattern))?;
            let Some(captures) = regex.captures(raw_line) else {
                continue;
            };
            let mut diagnostic = match rule.severity.as_str() {
                "warning" => Diagnostic::warning(
                    Some(markdown_path.to_path_buf()),
                    capture_message(&captures, rule, raw_line),
                ),
                _ => Diagnostic::error(
                    Some(markdown_path.to_path_buf()),
                    capture_message(&captures, rule, raw_line),
                ),
            };
            if let Some(line) = captures
                .name(&rule.line_group)
                .and_then(|value| value.as_str().parse::<usize>().ok())
            {
                diagnostic = diagnostic.at_line(apply_line_offset(line, rule.line_offset));
            }
            if let Some(column) = captures
                .name(&rule.column_group)
                .and_then(|value| value.as_str().parse::<usize>().ok())
            {
                diagnostic = diagnostic.at_column(column);
            }
            if let Some(path_match) = captures.name(&rule.path_group) {
                let captured = std::path::PathBuf::from(path_match.as_str());
                let rewritten = path_variants(input_path, cwd)
                    .into_iter()
                    .any(|variant| variant == captured.display().to_string());
                if !rewritten {
                    diagnostic.path = Some(std::path::PathBuf::from(replace_path_variants(
                        path_match.as_str(),
                        input_path,
                        markdown_path,
                        cwd,
                    )));
                }
            }
            diagnostics.push(diagnostic);
            break;
        }
    }
    Ok(diagnostics)
}

fn capture_message(
    captures: &regex::Captures<'_>,
    rule: &crate::descriptor::DiagnosticCaptureRule,
    raw_line: &str,
) -> String {
    captures
        .name(&rule.message_group)
        .map(|value| value.as_str().to_string())
        .unwrap_or_else(|| raw_line.to_string())
}


fn apply_line_offset(line: usize, offset: isize) -> usize {
    if offset >= 0 {
        line.saturating_add(offset as usize)
    } else {
        line.saturating_sub(offset.unsigned_abs())
    }
}


fn needs_tempfile(behavior: &ToolBehavior) -> bool {
    matches!(behavior.input_mode(), ToolInputMode::TempFile)
        || matches!(behavior.output_mode(), ToolOutputMode::TempFile)
}

fn temp_code_path(package: &Package, lang: &Lang) -> PathBuf {
    let ext = lang.file_ext();
    let file_name = format!("source.{ext}");
    let path = package.root.join(".build/mds/tmp").join(&file_name);
    if is_excluded(&package.root, &path, &package.config.excludes) {
        package.root.join(".build/mds-tmp").join(file_name)
    } else {
        path
    }
}


#[derive(Debug)]
struct CodeBlock<'a> {
    start: usize,
    end: usize,
    content: &'a str,
    content_start_line: usize,
}

fn code_block_ranges(text: &str) -> Vec<CodeBlock<'_>> {
    let mut ranges = Vec::new();
    let mut in_block = false;
    let mut content_start = 0;
    let mut content_start_line = 1;
    let mut cursor = 0;
    let mut line_number = 1;
    for line in text.split_inclusive('\n') {
        let line_start = cursor;
        cursor += line.len();
        if line.trim_start().starts_with("```") {
            if in_block {
                ranges.push(CodeBlock {
                    start: content_start,
                    end: line_start,
                    content: &text[content_start..line_start],
                    content_start_line,
                });
                in_block = false;
            } else {
                in_block = true;
                content_start = cursor;
                content_start_line = line_number + 1;
            }
        }
        line_number += 1;
    }
    ranges
}

fn padded_code_from_markdown(doc: &ImplDoc) -> Result<String, String> {
    let text = fs::read_to_string(&doc.path)
        .map_err(|error| format!("failed to read {}: {error}", doc.path.display()))?;
    let mut output = String::new();
    let mut output_line = 1;
    for block in code_block_ranges(&text) {
        while output_line < block.content_start_line {
            output.push('\n');
            output_line += 1;
        }
        output.push_str(block.content);
        output_line += block.content.bytes().filter(|byte| *byte == b'\n').count();
    }
    if output.is_empty() {
        output.push_str(&doc.code);
    }
    Ok(output)
}

fn apply_replacements(old: &str, replacements: &[(usize, usize, String)]) -> String {
    let mut output = String::new();
    let mut cursor = 0;
    for (start, end, replacement) in replacements {
        output.push_str(&old[cursor..*start]);
        output.push_str(replacement);
        cursor = *end;
    }
    output.push_str(&old[cursor..]);
    output
}
