use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command as ProcessCommand;

use crate::diagnostics::{Diagnostic, RunState};
use crate::fs_utils::is_mds_managed_file;
use crate::model::{AgentKitCategory, AiTarget, InitOptions, PythonTool, RustTool, TypeScriptTool};

pub(crate) fn run_init(
    cwd: &Path,
    package: Option<&Path>,
    options: &InitOptions,
    verbose: bool,
    state: &mut RunState,
) -> Result<(), String> {
    let root = package.map_or_else(|| cwd.to_path_buf(), |path| cwd.join(path));
    let mut files = Vec::new();

    if !options.ai_only {
        files.extend(project_files(&root, options));
    }
    files.extend(ai_files(&root, &options.targets, &options.categories));

    state.stdout.push_str("Init plan:\n");
    for file in &files {
        state
            .stdout
            .push_str(&format!("- write {}\n", file.path.display()));
    }

    let setup_actions = setup_actions(&root, options);
    if !setup_actions.is_empty() {
        state.stdout.push_str("Setup plan:\n");
        for action in &setup_actions {
            state.stdout.push_str(&format!(
                "- {}: {}{}\n",
                action.kind,
                action.command.join(" "),
                action
                    .install_hint
                    .map(|hint| format!(" (install: {hint})"))
                    .unwrap_or_default()
            ));
        }
    }

    if !options.yes {
        state
            .stdout
            .push_str("No changes written. Re-run with --yes to apply the init plan.\n");
        return Ok(());
    }

    for file in files {
        write_planned_file(&file, options.force, state)?;
    }

    for action in setup_actions {
        run_setup_action(&root, &action, verbose, state);
    }

    if !state.has_errors() && !state.environment_missing {
        state.stdout.push_str("init ok\n");
    }
    Ok(())
}

struct PlannedFile {
    path: PathBuf,
    content: String,
}

struct SetupAction {
    kind: &'static str,
    command: Vec<String>,
    install_hint: Option<&'static str>,
}

fn project_files(root: &Path, options: &InitOptions) -> Vec<PlannedFile> {
    let name = root
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or("mds-project");
    vec![
        PlannedFile {
            path: root.join("mds.config.toml"),
            content: project_config(options),
        },
        PlannedFile {
            path: root.join("package.json"),
            content: format!(
                "{{\n  \"name\": \"{}\",\n  \"version\": \"0.1.0\",\n  \"private\": true\n}}\n",
                sanitize_package_name(name)
            ),
        },
        PlannedFile {
            path: root.join("package.md"),
            content: format!(
                "<!-- Generated by mds init. -->\n# Package\n\n## Package\n\n| Name | Version |\n| --- | --- |\n| {} | 0.1.0 |\n\n## Dependencies\n\n| Name | Version | Summary |\n| --- | --- | --- |\n\n## Dev Dependencies\n\n| Name | Version | Summary |\n| --- | --- | --- |\n\n## Rules\n\n- Keep Markdown as the source of truth.\n",
                sanitize_package_name(name)
            ),
        },
        PlannedFile {
            path: root.join("src-md/index.md"),
            content: "<!-- Generated by mds init. -->\n# Index\n\n## Purpose\n\nDescribe this mds package.\n\n## Architecture\n\nMarkdown files in this directory are the source of truth.\n\n## Exposes\n\n| Kind | Name | Target | Summary |\n| --- | --- | --- | --- |\n\n## Rules\n\n- Keep one implementation md per feature.\n"
                .to_string(),
        },
    ]
}

fn project_config(options: &InitOptions) -> String {
    let mut content = "# Generated by mds init.\n[package]\nenabled = true\nallow_raw_source = false\n\n[roots]\nmarkdown = \"src-md\"\nsource = \"src\"\ntypes = \"src\"\ntest = \"tests\"\n".to_string();
    content.push_str(&render_quality("ts", ts_quality(&options.ts_tools)));
    content.push_str(&render_quality("py", py_quality(&options.py_tools)));
    content.push_str(&render_quality("rs", rs_quality(&options.rs_tools)));
    content
}

struct InitQuality {
    lint: Option<&'static str>,
    fix: Option<&'static str>,
    test: Option<&'static str>,
    required: Vec<&'static str>,
    optional: Vec<&'static str>,
}

fn ts_quality(tools: &[TypeScriptTool]) -> InitQuality {
    let has = |tool| tools.contains(&tool);
    let lint = if has(TypeScriptTool::Eslint) {
        Some("eslint")
    } else if has(TypeScriptTool::Biome) {
        Some("biome lint")
    } else {
        None
    };
    let fix = if has(TypeScriptTool::Prettier) {
        Some("prettier --write")
    } else if has(TypeScriptTool::Biome) {
        Some("biome format --write")
    } else {
        None
    };
    let test = if has(TypeScriptTool::Jest) {
        Some("jest")
    } else if has(TypeScriptTool::Vitest) {
        Some("vitest run")
    } else {
        None
    };
    let mut required = Vec::new();
    if lint.is_some() || fix.is_some() || test.is_some() {
        add_unique(&mut required, "node");
    }
    if lint == Some("eslint") {
        add_unique(&mut required, "eslint");
    }
    if fix == Some("prettier --write") {
        add_unique(&mut required, "prettier");
    }
    if lint == Some("biome lint") || fix == Some("biome format --write") {
        add_unique(&mut required, "biome");
    }
    if test == Some("vitest run") {
        add_unique(&mut required, "vitest");
    }
    if test == Some("jest") {
        add_unique(&mut required, "jest");
    }
    InitQuality {
        lint,
        fix,
        test,
        required,
        optional: Vec::new(),
    }
}

fn py_quality(tools: &[PythonTool]) -> InitQuality {
    let has = |tool| tools.contains(&tool);
    let lint = has(PythonTool::Ruff).then_some("ruff check");
    let fix = if has(PythonTool::Black) {
        Some("black")
    } else if has(PythonTool::Ruff) {
        Some("ruff format")
    } else {
        None
    };
    let test = if has(PythonTool::Unittest) {
        Some("python3 -m unittest")
    } else if has(PythonTool::Pytest) {
        Some("pytest")
    } else {
        None
    };
    let mut required = Vec::new();
    if lint.is_some() || fix.is_some() || test == Some("python3 -m unittest") {
        add_unique(&mut required, "python3");
    }
    if lint == Some("ruff check") || fix == Some("ruff format") {
        add_unique(&mut required, "ruff");
    }
    if fix == Some("black") {
        add_unique(&mut required, "black");
    }
    if test == Some("pytest") {
        add_unique(&mut required, "pytest");
    }
    InitQuality {
        lint,
        fix,
        test,
        required,
        optional: Vec::new(),
    }
}

fn rs_quality(tools: &[RustTool]) -> InitQuality {
    let has = |tool| tools.contains(&tool);
    let lint = has(RustTool::Clippy).then_some("cargo clippy");
    let fix = has(RustTool::Rustfmt).then_some("rustfmt");
    let test = if has(RustTool::Nextest) {
        Some("cargo nextest run")
    } else if has(RustTool::CargoTest) {
        Some("cargo test")
    } else {
        None
    };
    let mut required = Vec::new();
    let mut optional = Vec::new();
    if lint.is_some() || matches!(test, Some("cargo test" | "cargo nextest run")) {
        add_unique(&mut required, "rustc");
        add_unique(&mut required, "cargo");
    }
    if fix == Some("rustfmt") {
        add_unique(&mut required, "rustfmt");
    }
    if lint == Some("cargo clippy") {
        add_unique(&mut optional, "clippy-driver");
    }
    if test == Some("cargo nextest run") {
        add_unique(&mut optional, "cargo-nextest");
    }
    InitQuality {
        lint,
        fix,
        test,
        required,
        optional,
    }
}

fn add_unique(values: &mut Vec<&'static str>, value: &'static str) {
    if !values.contains(&value) {
        values.push(value);
    }
}

fn render_quality(lang: &str, quality: InitQuality) -> String {
    format!(
        "\n[quality.{lang}]\nlinter = {}\nfixer = {}\ntest_runner = {}\nrequired = [{}]\noptional = [{}]\n",
        render_optional_command(quality.lint),
        render_optional_command(quality.fix),
        render_optional_command(quality.test),
        render_string_array(&quality.required),
        render_string_array(&quality.optional),
    )
}

fn render_optional_command(command: Option<&str>) -> String {
    command
        .map(|command| format!("\"{command}\""))
        .unwrap_or_else(|| "false".to_string())
}

fn render_string_array(values: &[&str]) -> String {
    values
        .iter()
        .map(|value| format!("\"{value}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn ai_files(
    root: &Path,
    targets: &[AiTarget],
    categories: &[AgentKitCategory],
) -> Vec<PlannedFile> {
    let mut files = Vec::new();
    for target in targets {
        for category in categories {
            if let Some(file) = ai_file(root, *target, *category) {
                files.push(file);
            }
        }
    }
    files
}

fn ai_file(root: &Path, target: AiTarget, category: AgentKitCategory) -> Option<PlannedFile> {
    let (path, title) = match (target, category) {
        (AiTarget::ClaudeCode, AgentKitCategory::Instructions) => ("CLAUDE.md", "Claude Code"),
        (AiTarget::ClaudeCode, AgentKitCategory::Skills) => {
            (".claude/skills/mds/SKILL.md", "Claude Code skill")
        }
        (AiTarget::ClaudeCode, AgentKitCategory::Commands) => {
            (".claude/commands/mds-check.md", "Claude Code command")
        }
        (AiTarget::ClaudeCode, AgentKitCategory::Workflows) => (
            ".claude/workflows/mds-validation.md",
            "Claude Code workflow",
        ),
        (AiTarget::CodexCli, AgentKitCategory::Instructions) => ("AGENTS.md", "Codex CLI"),
        (AiTarget::CodexCli, AgentKitCategory::Skills) => {
            (".codex/skills/mds.md", "Codex CLI skill")
        }
        (AiTarget::CodexCli, AgentKitCategory::Commands) => {
            (".codex/commands/mds-check.md", "Codex CLI command")
        }
        (AiTarget::CodexCli, AgentKitCategory::Workflows) => {
            (".codex/workflows/mds-validation.md", "Codex CLI workflow")
        }
        (AiTarget::Opencode, AgentKitCategory::Instructions) => {
            (".opencode/instructions.md", "Opencode")
        }
        (AiTarget::Opencode, AgentKitCategory::Skills) => {
            (".opencode/skills/mds/SKILL.md", "Opencode skill")
        }
        (AiTarget::Opencode, AgentKitCategory::Commands) => {
            (".opencode/commands/mds-check.md", "Opencode command")
        }
        (AiTarget::Opencode, AgentKitCategory::Workflows) => {
            (".opencode/workflows/mds-validation.md", "Opencode workflow")
        }
        (AiTarget::GithubCopilotCli, AgentKitCategory::Instructions) => {
            (".github/copilot-instructions.md", "GitHub Copilot CLI")
        }
        (AiTarget::GithubCopilotCli, AgentKitCategory::Skills) => (
            ".github/prompts/mds-skill.prompt.md",
            "GitHub Copilot prompt skill",
        ),
        (AiTarget::GithubCopilotCli, AgentKitCategory::Commands) => (
            ".github/prompts/mds-check.prompt.md",
            "GitHub Copilot prompt command",
        ),
        (AiTarget::GithubCopilotCli, AgentKitCategory::Workflows) => (
            ".github/prompts/mds-validation.prompt.md",
            "GitHub Copilot workflow prompt",
        ),
        (AiTarget::ClaudeCode, AgentKitCategory::Docs) => (
            "docs/ai/claude-code-mds-agent-guide.md",
            "Claude Code mds AI agent guide",
        ),
        (AiTarget::CodexCli, AgentKitCategory::Docs) => (
            "docs/ai/codex-cli-mds-agent-guide.md",
            "Codex CLI mds AI agent guide",
        ),
        (AiTarget::Opencode, AgentKitCategory::Docs) => (
            "docs/ai/opencode-mds-agent-guide.md",
            "Opencode mds AI agent guide",
        ),
        (AiTarget::GithubCopilotCli, AgentKitCategory::Docs) => (
            "docs/ai/github-copilot-cli-mds-agent-guide.md",
            "GitHub Copilot CLI mds AI agent guide",
        ),
    };
    Some(PlannedFile {
        path: root.join(path),
        content: agent_template(title, target, category),
    })
}

fn agent_template(title: &str, target: AiTarget, category: AgentKitCategory) -> String {
    format!(
        "<!-- Generated by mds init. Target: {}. Category: {}. -->\n# {title}\n\nUse Markdown as the source of truth. Read `docs/project/index.md` when it exists, then read requirements, specs, architecture, and validation before changing generated behavior.\n\nRules:\n\n- Do not edit generated code as the source of truth.\n- Put imports outside code blocks in `Uses` tables.\n- Keep one implementation md per feature.\n- Run `mds check` before generation-sensitive changes.\n- Run `mds build --dry-run` before writing generated outputs.\n\nCommon commands:\n\n```sh\nmds check\nmds build --dry-run\nmds lint --fix --check\nmds test\n```\n",
        target.key(),
        category.key()
    )
}

fn write_planned_file(file: &PlannedFile, force: bool, state: &mut RunState) -> Result<(), String> {
    if file.path.exists() && !is_mds_managed_file(&file.path) && !force {
        state.diagnostics.push(Diagnostic::error(
            Some(file.path.clone()),
            "refusing to overwrite non-managed file during init; re-run with --force after reviewing the diff",
        ));
        return Ok(());
    }
    if let Some(parent) = file.path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    fs::write(&file.path, &file.content)
        .map_err(|error| format!("failed to write {}: {error}", file.path.display()))?;
    state.generated.push(file.path.clone());
    Ok(())
}

fn setup_actions(root: &Path, options: &InitOptions) -> Vec<SetupAction> {
    let mut actions = Vec::new();
    if options.install_project_deps {
        if root.join("package.json").exists() {
            actions.push(SetupAction {
                kind: "project-deps",
                command: vec!["npm".to_string(), "install".to_string()],
                install_hint: None,
            });
        }
        if root.join("Cargo.toml").exists() {
            actions.push(SetupAction {
                kind: "project-deps",
                command: vec!["cargo".to_string(), "fetch".to_string()],
                install_hint: None,
            });
        }
        if root.join("pyproject.toml").exists() {
            actions.push(SetupAction {
                kind: "project-deps",
                command: vec!["uv".to_string(), "sync".to_string()],
                install_hint: None,
            });
        }
    }
    if options.install_toolchains {
        for (tool, hint) in [
            (
                "node",
                "install Node.js 24+ from nodejs.org or a trusted version manager",
            ),
            ("rustc", "rustup toolchain install stable"),
            ("cargo", "rustup toolchain install stable"),
            (
                "python3",
                "install Python 3.13+ from python.org or a trusted package manager",
            ),
            ("uv", "python3 -m pip install --user uv"),
        ] {
            push_toolchain_check(&mut actions, tool, hint);
        }
        for tool in selected_quality_tools(options) {
            push_toolchain_check(&mut actions, tool, quality_tool_hint(tool));
        }
    }
    if options.install_ai_cli {
        for (tool, hint) in [
            ("claude", "npm install -g @anthropic-ai/claude-code"),
            ("codex", "npm install -g @openai/codex"),
            ("opencode", "npm install -g opencode-ai"),
            (
                "gh",
                "install GitHub CLI, then gh extension install github/gh-copilot",
            ),
        ] {
            actions.push(SetupAction {
                kind: "ai-cli-check",
                command: vec![tool.to_string(), "--version".to_string()],
                install_hint: Some(hint),
            });
        }
    }
    actions
}

fn selected_quality_tools(options: &InitOptions) -> Vec<&'static str> {
    let mut tools = Vec::new();
    for quality in [
        ts_quality(&options.ts_tools),
        py_quality(&options.py_tools),
        rs_quality(&options.rs_tools),
    ] {
        for tool in quality.required.into_iter().chain(quality.optional) {
            add_unique(&mut tools, tool);
        }
    }
    tools
}

fn push_toolchain_check(actions: &mut Vec<SetupAction>, tool: &'static str, hint: &'static str) {
    if actions.iter().any(|action| {
        action.kind == "toolchain-check" && action.command.first().is_some_and(|name| name == tool)
    }) {
        return;
    }
    actions.push(SetupAction {
        kind: "toolchain-check",
        command: vec![tool.to_string(), "--version".to_string()],
        install_hint: Some(hint),
    });
}

fn quality_tool_hint(tool: &str) -> &'static str {
    match tool {
        "eslint" => "npm install --save-dev eslint",
        "prettier" => "npm install --save-dev prettier",
        "biome" => "npm install --save-dev @biomejs/biome",
        "vitest" => "npm install --save-dev vitest",
        "jest" => "npm install --save-dev jest",
        "ruff" => "uv add --dev ruff",
        "black" => "uv add --dev black",
        "pytest" => "uv add --dev pytest",
        "rustfmt" => "rustup component add rustfmt",
        "clippy-driver" => "rustup component add clippy",
        "cargo-nextest" => "cargo install cargo-nextest",
        "node" => "install Node.js 24+ from nodejs.org or a trusted version manager",
        "python3" => "install Python 3.13+ from python.org or a trusted package manager",
        "rustc" | "cargo" => "rustup toolchain install stable",
        "uv" => "python3 -m pip install --user uv",
        _ => "install the selected quality tool from its official source",
    }
}

fn run_setup_action(root: &Path, action: &SetupAction, verbose: bool, state: &mut RunState) {
    if action.command.is_empty() {
        return;
    }
    if verbose {
        state.stdout.push_str(&format!(
            "running setup action: {}\n",
            action.command.join(" ")
        ));
    }
    let mut command = ProcessCommand::new(&action.command[0]);
    command.args(&action.command[1..]).current_dir(root);
    match command.output() {
        Ok(output) if output.status.success() => {
            state
                .stdout
                .push_str(&format!("setup ok: {}\n", action.command.join(" ")));
        }
        Ok(output) => {
            let detail = String::from_utf8_lossy(&output.stderr);
            state.diagnostics.push(Diagnostic::error(
                None,
                format!(
                    "setup action failed: {}{}{}",
                    action.command.join(" "),
                    if detail.trim().is_empty() {
                        String::new()
                    } else {
                        format!(": {}", detail.trim())
                    },
                    action
                        .install_hint
                        .map(|hint| format!("; install hint: {hint}"))
                        .unwrap_or_default()
                ),
            ));
        }
        Err(error) => {
            state.environment_missing = true;
            state.diagnostics.push(Diagnostic::error(
                None,
                format!(
                    "setup action could not start: {}: {error}{}",
                    action.command.join(" "),
                    action
                        .install_hint
                        .map(|hint| format!("; install hint: {hint}"))
                        .unwrap_or_default()
                ),
            ));
        }
    }
}

fn sanitize_package_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect()
}
