use crate::adapter::{imports_for, output_relative_path, plan_rust_modules};
use crate::diagnostics::{Diagnostic, RunState};
use crate::fs_utils::{is_mds_managed_file, path_within};
use crate::hash::sha256;
use crate::manifest::plan_manifest;
use crate::model::{GeneratedFile, GeneratedKind, ImplDoc, Lang, OutputKind, Package};
use crate::package::rust_expose_modules;

pub(crate) fn plan_generation(
    package: &Package,
    docs: &[ImplDoc],
    state: &mut RunState,
) -> Vec<GeneratedFile> {
    let mut generated = Vec::new();
    for doc in docs {
        let source_hash = sha256(&doc.normalized_input);
        for kind in [OutputKind::Types, OutputKind::Source, OutputKind::Test] {
            if let Some(file) = plan_output(package, doc, kind, &source_hash, state) {
                generated.push(file);
            }
        }
    }
    if docs.iter().any(|doc| doc.lang == Lang::Rust) {
        let index_modules = rust_expose_modules(package, state);
        if let Some(file) = plan_rust_modules(package, docs, index_modules, state) {
            generated.push(file);
        }
    }
    generated.push(plan_manifest(package, docs, &generated));
    generated
}

pub(crate) fn plan_output(
    package: &Package,
    doc: &ImplDoc,
    kind: OutputKind,
    source_hash: &str,
    state: &mut RunState,
) -> Option<GeneratedFile> {
    let relative = output_relative_path(doc, kind);
    let root = match kind {
        OutputKind::Types => &package.config.roots.types,
        OutputKind::Source => &package.config.roots.source,
        OutputKind::Test => &package.config.roots.test,
    };
    let path = package.root.join(root).join(relative);
    if !path_within(&package.root, &path) {
        state.diagnostics.push(Diagnostic::error(
            Some(path),
            "output path must stay inside package root",
        ));
        return None;
    }
    if path.exists() && !is_mds_managed_file(&path) {
        state.diagnostics.push(Diagnostic::error(
            Some(path),
            "refusing to overwrite file without mds generated header",
        ));
        return None;
    }

    let imports = imports_for(package, doc, kind, &path);
    let code = doc.code.get(&kind).cloned().unwrap_or_default();
    let header = format!(
        "{} Generated by mds. Do not edit. Source: {}. Source-Hash: {}.\n",
        doc.lang.header_prefix(),
        doc.package_relative_path.display(),
        source_hash
    );
    let content = if imports.is_empty() {
        format!("{header}\n{code}")
    } else {
        format!("{header}\n{imports}\n{code}")
    };
    Some(GeneratedFile {
        path,
        content,
        kind: GeneratedKind::Output(kind),
        source_path: Some(doc.package_relative_path.clone()),
    })
}
