use crate::adapter::output_relative_path;
use crate::diagnostics::{Diagnostic, RunState};
use crate::fs_utils::{is_excluded, is_mds_managed_file, path_within};
use crate::hash::sha256;
use crate::manifest::plan_manifest;
use crate::model::{GeneratedFile, GeneratedKind, ImplDoc, OutputKind, Package};

pub(crate) fn plan_generation(
    package: &Package,
    docs: &[ImplDoc],
    state: &mut RunState,
) -> Vec<GeneratedFile> {
    let mut generated = Vec::new();
    for doc in docs {
        if let Some(file) = plan_output(package, doc, state) {
            generated.push(file);
        }
    }
    generated.push(plan_manifest(package, docs, &generated));
    generated
}

pub(crate) fn plan_output(
    package: &Package,
    doc: &ImplDoc,
    state: &mut RunState,
) -> Option<GeneratedFile> {
    let source_hash = sha256(&doc.normalized_input);
    let relative = output_relative_path(doc);
    let path = package
        .root
        .join(&package.config.roots.source)
        .join(relative);
    if is_excluded(&package.root, &path, &package.config.excludes) {
        return None;
    }
    if !path_within(&package.root, &path) {
        state.diagnostics.push(Diagnostic::error(
            Some(path),
            "output path must stay inside package root",
        ));
        return None;
    }
    if path.exists() && !is_mds_managed_file(&path) {
        state.diagnostics.push(Diagnostic::error(
            Some(path),
            "refusing to overwrite file without mds generated header",
        ));
        return None;
    }

    let header = format!(
        "{} Generated by mds. Do not edit. Source: {}. Source-Hash: {}.\n",
        doc.lang.header_prefix(),
        doc.package_relative_path.display(),
        source_hash
    );
    let content = format!("{header}\n{}", doc.code);

    Some(GeneratedFile {
        path,
        content,
        kind: GeneratedKind::Output(OutputKind::Source),
        source_path: Some(doc.package_relative_path.clone()),
    })
}
