// Generated by mds. Do not edit. Source: .mds/source/capabilities/diagnostics.rs.md. Source-Hash: abceafb27f5218e46c49da4836da2f29490b87a65c71e27713d18870deb4a7fb.

use std::path::{Path};
use mds_core::config::{merge_config_file};
use mds_core::descriptor::{set_workspace_descriptor_root};
use mds_core::diagnostics::{RunState};
use mds_core::markdown::{extract_all_code_blocks};
use mds_core::markdown::{sections_with_labels};
use mds_core::markdown::{validate_markdown_links};
use mds_core::model::{Config};
use mds_core::model::{Lang};
use mds_core::table::{parse_table_with_labels};
use tower_lsp::{lsp_types};
use crate::convert::{to_lsp_diagnostic};
