// Generated by mds. Do not edit. Source: .mds/source/capabilities/hover.rs.md. Source-Hash: 7ae4d58aa7a165ddb14cea21875cce77f2115ac0d0301ca37486be510c69d80e.

use std::path::{Path};
use mds_core::markdown::{sections_with_labels};
use mds_core::markdown::{source_markdown_root};
use mds_core::model::{Lang};
use tower_lsp::lsp_types::{*};
use crate::convert::{line_at};
use crate::convert::{word_at_position};
use crate::state::{WorkspaceState};
