// Generated by mds. Do not edit. Source: .mds/source/capabilities/symbols.rs.md. Source-Hash: 5386c76d27fc2f1646a6918176ee87e97dbac2a489eb285f724475aada33b826.

use tower_lsp::lsp_types::{*};
use crate::state::{WorkspaceState};
