#!/usr/bin/env node
/**
 * vendor-binary.js — Copy the native mds binary into the vendor/ directory
 * for packaging with mds-cli.
 *
 * Usage:
 *   node scripts/vendor-binary.js [--target <triple>] [--source <path>]
 *
 * If --source is not given, attempts to find the binary from:
 *   1. ../../crates/target/release/mds
 *   2. `which mds` on PATH
 *
 * The --target option is for cross-compilation (e.g., x86_64-unknown-linux-gnu).
 * When given, the binary is placed at vendor/mds-<target> and a dispatch
 * script is generated at vendor/mds.
 */

import { copyFileSync, mkdirSync, existsSync, chmodSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

function parseArgs() {
  const args = process.argv.slice(2);
  let source = null;
  let target = null;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--source" && args[i + 1]) source = args[++i];
    if (args[i] === "--target" && args[i + 1]) target = args[++i];
  }
  return { source, target };
}

function findBinary(explicitSource) {
  if (explicitSource) {
    if (!existsSync(explicitSource)) {
      console.error(`error: specified binary not found: ${explicitSource}`);
      process.exit(1);
    }
    return resolve(explicitSource);
  }

  // Try workspace release build
  const releasePath = resolve(ROOT, "..", "crates", "target", "release", "mds");
  if (existsSync(releasePath)) return releasePath;

  // Try PATH
  try {
    const which = execSync("which mds", { encoding: "utf-8" }).trim();
    if (which && existsSync(which)) return which;
  } catch {
    // not on PATH
  }

  console.error("error: native mds binary not found. Build with `cd crates && cargo build --release` first.");
  process.exit(1);
}

function main() {
  const { source, target } = parseArgs();
  const binary = findBinary(source);

  const vendorDir = join(ROOT, "cli", "vendor");
  mkdirSync(vendorDir, { recursive: true });

  if (target) {
    const dest = join(vendorDir, `mds-${target}`);
    copyFileSync(binary, dest);
    chmodSync(dest, 0o755);
    console.log(`copied ${binary} -> ${dest}`);

    // Generate dispatch script
    const dispatch = join(vendorDir, "mds");
    writeFileSync(dispatch, `#!/bin/sh
# Auto-generated by vendor-binary.js
DIR="$(cd "$(dirname "$0")" && pwd)"
ARCH="$(uname -m)"
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"

case "$OS-$ARCH" in
  linux-x86_64)  TRIPLE="x86_64-unknown-linux-gnu" ;;
  linux-aarch64) TRIPLE="aarch64-unknown-linux-gnu" ;;
  darwin-x86_64) TRIPLE="x86_64-apple-darwin" ;;
  darwin-arm64)  TRIPLE="aarch64-apple-darwin" ;;
  *)             echo "unsupported platform: $OS-$ARCH" >&2; exit 4 ;;
esac

exec "$DIR/mds-$TRIPLE" "$@"
`, { mode: 0o755 });
    console.log(`generated dispatch script: ${dispatch}`);
  } else {
    const dest = join(vendorDir, "mds");
    copyFileSync(binary, dest);
    chmodSync(dest, 0o755);
    console.log(`copied ${binary} -> ${dest}`);
  }
}

main();
