// Generated by mds. Do not edit. Source: .mds/source/main.rs.md. Source-Hash: 25dd740d73ab190ff984cf5fbe5345c390ed3f885ef2475dd8b3d5a33532e927.

use mds_cli::args::{parse_args};
use mds_cli::args::{print_usage};
use mds_cli::wizard::{run_interactive_init};
use mds_core::{execute};
use mds_core::{CliRequest};
use mds_core::{Command};
use std::io::{IsTerminal};
use std::process::{Command as ProcessCommand};
