// Generated by mds. Do not edit. Source: .mds/source/wizard.rs.md. Source-Hash: c48a2e7ee0fe297f9509ba2c17dff760a1b8158a7929e690c1ea801378853963.

use std::io::{self};
use std::io::{stdout};
use std::path::{Path};
use crossterm::event::{self, Event, KeyCode, KeyEventKind};
use crossterm::terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen};
use crossterm::{ExecutableCommand};
use mds_core::{descriptor};
use mds_core::{AgentKitCategory};
use mds_core::{AiTarget};
use mds_core::{InitOptions};
use mds_core::{InitQualityCommands};
use mds_core::{InitTargetCategories};
use mds_core::{LabelPreset};
use mds_core::{Lang};
use ratatui::{prelude::*};
use ratatui::widgets::{Block, Borders, Clear, List, ListItem, ListState, Padding, Paragraph, Wrap};
