use std::fs;
use std::path::{Component, Path, PathBuf};

pub(crate) fn is_mds_managed_file(path: &Path) -> bool {
    fs::read_to_string(path)
        .map(|content| {
            content
                .lines()
                .next()
                .is_some_and(|line| line.contains("Generated by mds"))
        })
        .unwrap_or(false)
}

pub(crate) fn path_within(root: &Path, path: &Path) -> bool {
    path.components()
        .try_fold(Vec::new(), |mut stack: Vec<_>, component| {
            match component {
                Component::ParentDir => {
                    stack.pop();
                }
                Component::Normal(value) => stack.push(value.to_os_string()),
                Component::RootDir | Component::Prefix(_) | Component::CurDir => {}
            }
            Some(stack)
        })
        .is_some()
        && path.starts_with(root)
}

pub(crate) fn collect_files(
    root: &Path,
    skip_workspace_private: bool,
) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();
    collect_files_inner(root, skip_workspace_private, &mut files)?;
    files.sort();
    Ok(files)
}

pub(crate) fn collect_files_inner(
    root: &Path,
    skip_workspace_private: bool,
    files: &mut Vec<PathBuf>,
) -> Result<(), String> {
    let entries = fs::read_dir(root)
        .map_err(|error| format!("failed to read directory {}: {error}", root.display()))?;
    for entry in entries {
        let entry = entry.map_err(|error| format!("failed to read directory entry: {error}"))?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|error| format!("failed to read file type {}: {error}", path.display()))?;
        if file_type.is_dir() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if skip_workspace_private
                && matches!(
                    name.as_ref(),
                    ".git" | ".opencode" | ".agents" | "docs" | "target" | "node_modules"
                )
            {
                continue;
            }
            collect_files_inner(&path, skip_workspace_private, files)?;
        } else if file_type.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

pub(crate) fn is_excluded(root: &Path, path: &Path, patterns: &[String]) -> bool {
    let relative = path.strip_prefix(root).unwrap_or(path);
    let value = relative
        .components()
        .filter_map(|component| match component {
            Component::Normal(value) => Some(value.to_string_lossy()),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("/");
    patterns.iter().any(|pattern| glob_match(pattern, &value))
}

fn glob_match(pattern: &str, value: &str) -> bool {
    glob_match_bytes(pattern.as_bytes(), value.as_bytes())
}

fn glob_match_bytes(pattern: &[u8], value: &[u8]) -> bool {
    match (pattern.split_first(), value.split_first()) {
        (None, None) => true,
        (None, Some(_)) => false,
        (Some((&b'*', rest)), _) => {
            glob_match_bytes(rest, value)
                || value
                    .split_first()
                    .is_some_and(|(_, tail)| glob_match_bytes(pattern, tail))
        }
        (Some((&b'?', rest)), Some((_, tail))) => glob_match_bytes(rest, tail),
        (Some((&expected, rest)), Some((&actual, tail))) if expected == actual => {
            glob_match_bytes(rest, tail)
        }
        _ => false,
    }
}
