// Generated by mds. Do not edit. Source: mds-lsp/.mds/source/main.rs.md. Source-Hash: 21383d08642308315f546a7f9d83fa33a1d9d20ea1673f229166bf03ee23d884.

use tower_lsp::{LspService, Server};
use tracing_subscriber::EnvFilter;

mod capabilities;

mod convert;

mod labels;

mod server;

mod state;

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .with_writer(std::io::stderr)
        .init();

    let stdin = tokio::io::stdin();
    let stdout = tokio::io::stdout();

    let (service, socket) = LspService::new(server::MdsLanguageServer::new);
    Server::new(stdin, stdout, socket).serve(service).await;
}
