# Generated by mds. Do not edit. Source: .mds/source/greet.py.md. Source-Hash: fc8b8b951d4e8fa7a762a69ad4fee252c13597e0ef69b5522fb0d5a8de14f3bf.

from dataclasses import dataclass
@dataclass
class GreetOptions:
    name: str

def greet(options: GreetOptions) -> str:
    return f"Hello, {options.name}!"
