# Generated by mds. Do not edit. Source: .mds/source/greet.py.md. Source-Hash: f608dde0ecb16d453e444da36bc53a9d17650c400ef0c8367fd694c50670a0f8.

from dataclasses import dataclass

@dataclass
class GreetOptions:
    name: str

def greet(options: GreetOptions) -> str:
    return f"Hello, {options.name}!"
