// Generated by mds. Do not edit. Source: .mds/source/greet.py.md. Source-Hash: 3e103d3df7f3b1401857485e0aa726236192dcbfb7c7cabeba0c87ce3519c418.

from dataclasses import dataclass
@dataclass
class GreetOptions:
    name: str

def greet(options: GreetOptions) -> str:
    return f"Hello, {options.name}!"
