# Generated by mds. Do not edit. Source: .mds/test/greet.py.md. Source-Hash: 0f1be0f2ed64ced49a7edacb2e24fcc525b9107d7a4b14481f4f8507bac47c48.

from greet import GreetOptions, greet


def test_greet_returns_expected_message() -> None:
    options = GreetOptions(name="World")
    assert greet(options) == "Hello, World!"
