// Generated by mds. Do not edit. Source: .mds/test/greet.md. Source-Hash: ab4638b7aef43f8b8edd97987cab3dc706a12113df79bdfbc4316abed617fddd.

from greet import GreetOptions, greet
def test_greet_returns_expected_message() -> None:
    options = GreetOptions(name="World")
    assert greet(options) == "Hello, World!"
