id = "c"
aliases = ["c-lang"]
match_suffixes = ["c"]

[language]
primary_ext = "c"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "c"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "h"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = ".test"
extension = "c"

[syntax]
top_level_keywords = ["typedef ", "struct ", "enum ", "static ", "extern ", "#define "]
comment_prefixes = ["//", "/*", "*"]
doc_comment_prefixes = ["/**"]

[[syntax.imports]]
starts_with = "#include "

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
// Implement your feature here.
'''