id = "dart"
aliases = ["dartlang"]
match_suffixes = ["dart"]

[language]
primary_ext = "dart"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "dart"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "dart"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = "_test"
extension = "dart"

[imports]
style = "dart"

[syntax]
top_level_keywords = ["class ", "enum ", "mixin ", "extension ", "typedef ", "final ", "const ", "void "]
comment_prefixes = ["//", "/*", "*"]
doc_comment_prefixes = ["///", "/**"]

[[syntax.imports]]
starts_with = "import "

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
// Implement your feature here.
'''