id = "java"
match_suffixes = ["java"]

[language]
primary_ext = "java"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "java"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = "Types"
extension = "java"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = "Test"
extension = "java"

[imports]
style = "java"

[syntax]
top_level_keywords = [
  "public class ",
  "class ",
  "public interface ",
  "interface ",
  "public enum ",
  "enum ",
  "public record ",
  "record ",
]
comment_prefixes = ["//", "/*", "*"]

[[syntax.imports]]
starts_with = "import "

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
// Implement your feature here.
'''