id = "mojo"
match_suffixes = ["mojo"]

[language]
primary_ext = "mojo"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "mojo"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "mojo"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = ".test"
extension = "mojo"

[imports]
style = "mojo"

[syntax]
top_level_keywords = ["fn ", "struct ", "class ", "alias ", "let ", "var "]
comment_prefixes = ["#"]
doc_string_delimiters = ["\"\"\"", "'''"]

[[syntax.imports]]
starts_with = "import "

[[syntax.imports]]
starts_with = "from "

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
# Implement your feature here.
'''