id = "scss"
match_suffixes = ["scss"]

[language]
primary_ext = "scss"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "scss"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "scss"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = ".test"
extension = "scss"

[syntax]
top_level_keywords = ["$", "@use ", "@forward ", "@mixin ", "@function ", ".", "#"]
comment_prefixes = ["//", "/*", "*"]

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
$feature-color: #0f172a;

.feature {
  color: $feature-color;
}
'''