id = "sql"
match_suffixes = ["sql"]

[language]
primary_ext = "sql"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "sql"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "sql"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = ".test"
extension = "sql"

[imports]
style = "none"

[syntax]
top_level_keywords = ["SELECT ", "INSERT ", "UPDATE ", "DELETE ", "CREATE ", "ALTER ", "WITH "]
comment_prefixes = ["--", "/*", "*"]

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
SELECT 1;
'''