id = "zig"
match_suffixes = ["zig"]

[language]
primary_ext = "zig"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "zig"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "zig"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = ".test"
extension = "zig"

[imports]
style = "zig"

[syntax]
top_level_keywords = ["pub fn ", "fn ", "pub const ", "const ", "pub var ", "var ", "test ", "comptime "]
comment_prefixes = ["//", "/*", "*"]
doc_comment_prefixes = ["///", "//!"]

[[syntax.imports]]
starts_with = "const "
contains = ["@import("]

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
// Implement your feature here.
'''