id = "go"
aliases = ["golang"]
match_suffixes = ["go"]

[language]
primary_ext = "go"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "go"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = "_types"
extension = "go"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = "_test"
extension = "go"

[syntax]
top_level_keywords = ["func ", "type ", "var ", "const "]
comment_prefixes = ["//", "/*", "*"]

[[syntax.imports]]
starts_with = "import "

[[syntax.imports]]
starts_with = "import ("

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
// Implement your feature here.
'''