// Generated by mds. Do not edit. Source: .mds/source/sample.ts.md. Source-Hash: 76e7890e55ba245f285fdd2f249e57adacfb718b0487f9aa4dc365b4bc40803f.

export function descriptorSample(): string {
  return "ok";
}
