// Generated by mds. Do not edit. Source: .mds/source/sample.angular.md. Source-Hash: b00728b3aa4dd37525c755824cf564a8c2f37440bd8841b039878d6265b31de3.

import { Component } from '@angular/core';
@Component({
  selector: 'descriptor-sample',
  template: '<p>ok</p>',
})
export class DescriptorSampleComponent {}
