// Generated by mds. Do not edit. Source: .mds/source/sample.tsx.md. Source-Hash: e19aa558b233d3cc0ff4d3891ef88ad9d86073edfd70ee6f34e1019237bc83fa.

export function DescriptorSample(): JSX.Element {
  return <div>ok</div>;
}
