// Generated by mds. Do not edit. Source: .mds/source/sample.js.md. Source-Hash: 6985ff561b6c47803f5508b3f739811106bacd346e8d6655017a37cb3a1fdc34.

export function descriptorSample() {
  return "ok";
}
