// Generated by mds. Do not edit. Source: .mds/source/sample.rs.md. Source-Hash: bd3409469271f5bbb746c36257a0ec65ff36f1a53cac1a52709bb4bc216d898b.

pub fn descriptor_sample() -> &'static str {
    "ok"
}
