// Generated by mds. Do not edit. Source: .mds/source/sample.jsx.md. Source-Hash: 0af08e3e794c0b9b81d0a18acb83cf2b964be843a044ec0f48705dc0e3227f92.

export function DescriptorSample() {
  return <div>ok</div>;
}
