// Generated by mds. Do not edit. Source: .mds/source/sample.svelte.md. Source-Hash: 2d0b66133523e9d84c090e6cb7dd8b914f1a495a8b7e773db967935018715f2b.

<script lang="ts">
  const message = 'ok';
</script>

<p>{message}</p>
