// Generated by mds. Do not edit. Source: .mds/source/sample.mojo.md. Source-Hash: af578d8bc21e5b190a539da8251fc7bc51b0e2fb01ee0165f2ccf8d435b7edde.

fn descriptor_sample() -> String:
    return "ok"
