// Generated by mds. Do not edit. Source: .mds/source/sample.cs.md. Source-Hash: 7e5deeb0825dfcf42bb7c04ef55daef4bf2b8691698c9bf9bca5082e239e8691.

namespace DescriptorSamples;

public static class DescriptorSample
{
    public static int Value() => 1;
}
