// Generated by mds. Do not edit. Source: .mds/source/sample.zig.md. Source-Hash: 631597ccf5a7bc726e142a9c8b846b17ba61ffc9a3cfc816f048995bb3fc3e9c.

pub fn descriptorSample() []const u8 {
    return "ok";
}
