// Generated by mds. Do not edit. Source: .mds/source/sample.go.md. Source-Hash: 8c0fa5a8bf9f2d53807d42536efc4d2f2b2488eb7cf18b342e4437e1a302f703.

package sample

func DescriptorSample() string {
    return "ok"
}
