// Generated by mds. Do not edit. Source: .mds/source/sample.java.md. Source-Hash: 18862a9e52112dbe41be3da3070ef28c3223dd2b1decf676411fa4c7c7dccc0a.

public final class DescriptorSample {
    private DescriptorSample() {}

    public static String value() {
        return "ok";
    }
}
