id = "bundler"
display_name = "Ruby (Bundler)"
lang = "ruby"
metadata_files = ["Gemfile", "*.gemspec"]
lockfiles = ["Gemfile.lock"]
metadata_reader = "bundler"

[commands]
install = "bundle install"
build = "bundle exec rake build"
typecheck = "bundle exec typeprof"
lint = "bundle exec rubocop"
test = "bundle exec rspec"