id = "cargo"
display_name = "Rust (Cargo)"
lang = "rs"
metadata_files = ["Cargo.toml"]
lockfiles = ["Cargo.lock"]
metadata_reader = "cargo-toml"

[commands]
install = "cargo fetch"
build = "cargo build"
typecheck = "cargo check"
lint = "cargo clippy"
test = "cargo test"