id = "poetry"
display_name = "Python (Poetry)"
lang = "py"
metadata_files = ["pyproject.toml"]
lockfiles = ["poetry.lock"]
metadata_reader = "pyproject-toml"

[commands]
install = "poetry install"
build = "poetry build"
typecheck = "poetry run mypy ."
lint = "poetry run ruff check"
test = "poetry run pytest"