id = "pub"
display_name = "Dart (pub)"
lang = "dart"
metadata_files = ["pubspec.yaml"]
lockfiles = ["pubspec.lock"]
metadata_reader = "pubspec-yaml"

[commands]
install = "dart pub get"
build = "dart compile exe"
typecheck = "dart analyze"
lint = "dart analyze"
test = "dart test"