id = "uv"
display_name = "Python (uv)"
lang = "py"
metadata_files = ["pyproject.toml"]
lockfiles = ["uv.lock"]
metadata_reader = "pyproject-toml"

[commands]
install = "uv sync"
build = "uv build"
typecheck = "uv run mypy ."
lint = "uv run ruff check"
test = "uv run pytest"