// Generated by mds. Do not edit. Source: mds-core/.mds/source/lib.rs.md. Source-Hash: 74e6c2b4ddf3d52c89d625b1e84e6dfdb5b3f0fc8383700b64cc7cd51379c9a6.

mod adapter;

pub mod config;

mod descriptor;

pub mod diagnostics;

mod diff;

mod doctor;

mod fs_utils;

mod generation;

mod hash;

mod init;

mod manifest;

pub mod markdown;

pub mod model;

mod new;

pub mod package;

mod package_sync;

mod quality;

mod release_quality;

mod runner;

pub mod table;

pub use diagnostics::{Diagnostic, RunState, Severity};
pub use model::{
    AgentKitCategory, AiTarget, BuildMode, CliRequest, CliResult, Command, Config, DocKind,
    DoctorFormat, GeneratedFile, GeneratedKind, ImplDoc, InitOptions, InitQualityCommands,
    InitTargetCategories, LabelPreset, Lang, MetadataKind, NewOptions, OutputKind, Package,
    PackageMetadata, PythonTool, QualityConfig, ReleaseQualityOptions, Roots, RustTool,
    TypeScriptTool,
};
pub use runner::execute;
