// Generated by mds. Do not edit. Source: mds-core/.mds/source/markdown.rs.md. Source-Hash: 6370ce93ac562044423dc1524b9b40333ccf1d449bd5cb0b212e51ea1e498445.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::diagnostics::{Diagnostic, RunState};
use crate::fs_utils::{collect_files, is_excluded};
use crate::model::{DocKind, ImplDoc, Lang, Package};

pub fn load_implementation_docs(
    package: &Package,
    state: &mut RunState,
) -> Result<Vec<ImplDoc>, String> {
    let markdown_root = source_markdown_root(package);
    if !markdown_root.exists() {
        state.diagnostics.push(Diagnostic::error(
            Some(markdown_root),
            "markdown root does not exist",
        ));
        return Ok(Vec::new());
    }

    let mut docs = Vec::new();
    for path in collect_files(&markdown_root, false)? {
        if is_excluded(&package.root, &path, &package.config.excludes) {
            continue;
        }
        let Some(lang) = Lang::from_path(&path) else {
            continue;
        };
        if !package.config.adapters.get(&lang).copied().unwrap_or(true) {
            continue;
        }
        if let Some(doc) = parse_impl_doc(package, DocKind::Source, lang, &path, state) {
            docs.push(doc);
        }
    }
    docs.extend(load_test_docs(package, &docs, state)?);
    docs.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(docs)
}

fn load_test_docs(
    package: &Package,
    source_docs: &[ImplDoc],
    state: &mut RunState,
) -> Result<Vec<ImplDoc>, String> {
    let markdown_root = test_markdown_root(package);
    if !markdown_root.exists() {
        return Ok(Vec::new());
    }

    let mut docs = Vec::new();
    for path in collect_files(&markdown_root, false)? {
        if is_excluded(&package.root, &path, &package.config.excludes) || !is_test_doc(&path) {
            continue;
        }
        let Some(lang) = resolve_test_doc_lang(package, &path, source_docs, state) else {
            continue;
        };
        if let Some(doc) = parse_impl_doc(package, DocKind::Test, lang, &path, state) {
            docs.push(doc);
        }
    }
    Ok(docs)
}

pub fn parse_impl_doc(
    package: &Package,
    doc_kind: DocKind,
    lang: Lang,
    path: &Path,
    state: &mut RunState,
) -> Option<ImplDoc> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(error) => {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!("failed to read implementation md: {error}"),
            ));
            return None;
        }
    };
    validate_impl_doc_structure(path, &text, &package.config.label_overrides, state);
    validate_markdown_links(path, &text, state);
    validate_code_block_boundaries(path, &lang, &text, state);

    let sections = sections_with_labels(&text, &package.config.label_overrides);
    let types_code = code_from_section(sections.get("Types"));
    let source_code = code_from_section(sections.get("Source"));
    let test_code = code_from_section(sections.get("Test"));
    let covers = covers_from_section(sections.get("Covers"));

    let code = extract_all_code_blocks(&text);
    if code.trim().is_empty() {
        state.diagnostics.push(Diagnostic::error(
            Some(path.to_path_buf()),
            "implementation md requires at least one code block",
        ));
    }

    let package_relative_path = match path.strip_prefix(&package.root) {
        Ok(path) => path.to_path_buf(),
        Err(_) => path.to_path_buf(),
    };
    let markdown_relative_path = match path.strip_prefix(markdown_root_for(package, doc_kind)) {
        Ok(path) => path.to_path_buf(),
        Err(_) => path.to_path_buf(),
    };
    let normalized_input = normalized_input(path, &text);

    Some(ImplDoc {
        doc_kind,
        lang,
        path: path.to_path_buf(),
        package_relative_path,
        markdown_relative_path,
        code,
        types_code,
        source_code,
        test_code,
        covers,
        normalized_input,
    })
}

pub fn source_markdown_root(package: &Package) -> PathBuf {
    let fixed = package.root.join(".mds/source");
    if fixed.exists() && (has_source_impl_docs(&fixed) || !package.root.join(&package.config.roots.markdown).exists()) {
        fixed
    } else {
        package.root.join(&package.config.roots.markdown)
    }
}

pub fn test_markdown_root(package: &Package) -> PathBuf {
    package.root.join(".mds/test")
}

fn markdown_root_for(package: &Package, doc_kind: DocKind) -> PathBuf {
    match doc_kind {
        DocKind::Source => source_markdown_root(package),
        DocKind::Test => test_markdown_root(package),
    }
}

fn has_source_impl_docs(root: &Path) -> bool {
    let Ok(files) = collect_files(root, false) else {
        return false;
    };
    files.into_iter().any(|path| {
        matches!(path.extension().and_then(|ext| ext.to_str()), Some("md"))
            && !matches!(path.file_name().and_then(|name| name.to_str()), Some("overview.md" | "index.md"))
    })
}

fn is_test_doc(path: &Path) -> bool {
    matches!(path.extension().and_then(|ext| ext.to_str()), Some("md"))
        && !matches!(path.file_name().and_then(|name| name.to_str()), Some("overview.md"))
}

fn resolve_test_doc_lang(
    package: &Package,
    path: &Path,
    source_docs: &[ImplDoc],
    state: &mut RunState,
) -> Option<Lang> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(error) => {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!("failed to read test md: {error}"),
            ));
            return None;
        }
    };
    let sections = sections_with_labels(&text, &package.config.label_overrides);
    let covers = covers_from_section(sections.get("Covers"));
    if covers.is_empty() {
        state.diagnostics.push(Diagnostic::error(
            Some(path.to_path_buf()),
            "test md requires at least one Covers entry",
        ));
        return None;
    }

    let mut lang = None;
    for cover in covers {
        let matches = source_docs
            .iter()
            .filter(|doc| cover_matches(doc, &cover))
            .collect::<Vec<_>>();
        match matches.as_slice() {
            [] => {
                state.diagnostics.push(Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!("test md Covers entry `{cover}` does not resolve to a source md"),
                ));
                return None;
            }
            [doc] => {
                if let Some(current) = &lang {
                    if current != &doc.lang {
                        state.diagnostics.push(Diagnostic::error(
                            Some(path.to_path_buf()),
                            "test md Covers entries must resolve to source docs of the same language",
                        ));
                        return None;
                    }
                } else {
                    lang = Some(doc.lang.clone());
                }
            }
            _ => {
                state.diagnostics.push(Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!("test md Covers entry `{cover}` resolves ambiguously"),
                ));
                return None;
            }
        }
    }

    lang
}

fn cover_matches(doc: &ImplDoc, cover: &str) -> bool {
    let cover = cover.trim();
    cover == logical_module_id(&doc.markdown_relative_path)
        || cover == doc.markdown_relative_path.to_string_lossy()
}

fn logical_module_id(path: &Path) -> String {
    let value = path.to_string_lossy().replace('\\', "/");
    let value = value.strip_suffix(".md").unwrap_or(&value);
    if let Some(index) = value.rfind('.') {
        value[..index].to_string()
    } else {
        value.to_string()
    }
}

/// Extract all code blocks from the entire markdown content.
/// Code blocks are separated by `\n\n` in the output.

fn validate_impl_doc_structure(
    path: &Path,
    text: &str,
    label_overrides: &HashMap<String, String>,
    state: &mut RunState,
) {
    validate_code_fence_integrity(path, text, state);
    validate_duplicate_h2_sections(path, text, label_overrides, state);
}

fn validate_code_fence_integrity(path: &Path, text: &str, state: &mut RunState) {
    let mut fence_len: Option<usize> = None;
    let mut fence_start_line = 0usize;
    for (line_index, line) in text.lines().enumerate() {
        let Some((marker_len, suffix)) = backtick_fence(line) else {
            continue;
        };
        if let Some(open_len) = fence_len {
            if is_closing_fence(marker_len, suffix, open_len) {
                fence_len = None;
                fence_start_line = 0;
            } else if marker_len >= open_len {
                state.diagnostics.push(Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!(
                        "code fence opened at line {} is not closed before a new fence opener at line {}",
                        fence_start_line,
                        line_index + 1
                    ),
                ));
                fence_len = Some(marker_len);
                fence_start_line = line_index + 1;
            }
        } else {
            fence_len = Some(marker_len);
            fence_start_line = line_index + 1;
        }
    }
    if fence_len.is_some() {
        state.diagnostics.push(Diagnostic::error(
            Some(path.to_path_buf()),
            format!("unterminated code fence opened at line {fence_start_line}"),
        ));
    }
}

fn validate_duplicate_h2_sections(
    path: &Path,
    text: &str,
    label_overrides: &HashMap<String, String>,
    state: &mut RunState,
) {
    let mut first_seen = HashMap::new();
    let mut fence_len: Option<usize> = None;
    for (line_index, line) in text.lines().enumerate() {
        if let Some((marker_len, suffix)) = backtick_fence(line) {
            if let Some(open_len) = fence_len {
                if is_closing_fence(marker_len, suffix, open_len) {
                    fence_len = None;
                }
            } else {
                fence_len = Some(marker_len);
            }
            continue;
        }
        if fence_len.is_some() {
            continue;
        }
        let Some(title) = line.strip_prefix("## ") else {
            continue;
        };
        let canonical = canonical_section_title(title.trim(), label_overrides);
        if let Some(first_line) = first_seen.insert(canonical.clone(), line_index + 1) {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!(
                    "duplicate H2 section `{canonical}`: first defined at line {first_line}, repeated at line {}",
                    line_index + 1
                ),
            ));
        }
    }
}

pub fn extract_all_code_blocks(text: &str) -> String {
    let mut fence_len: Option<usize> = None;
    let mut current = String::new();
    let mut blocks = Vec::new();
    for line in text.lines() {
        if let Some((marker_len, suffix)) = backtick_fence(line) {
            if let Some(open_len) = fence_len {
                if !is_closing_fence(marker_len, suffix, open_len) {
                    current.push_str(line);
                    current.push('\n');
                    continue;
                }
                blocks.push(current.trim_end_matches(['\r', '\n']).to_string());
                current.clear();
                fence_len = None;
            } else {
                fence_len = Some(marker_len);
            }
            continue;
        }
        if fence_len.is_some() {
            current.push_str(line);
            current.push('\n');
        }
    }
    if blocks.is_empty() {
        String::new()
    } else {
        blocks.join("\n\n") + "\n"
    }
}

fn code_from_section(section: Option<&String>) -> String {
    section
        .map(|section| extract_all_code_blocks(section))
        .unwrap_or_default()
}

fn covers_from_section(section: Option<&String>) -> Vec<String> {
    section
        .map(|section| {
            section
                .lines()
                .map(|line| line.trim().trim_start_matches(['-', '*']).trim())
                .filter(|line| !line.is_empty())
                .map(ToOwned::to_owned)
                .collect()
        })
        .unwrap_or_default()
}

fn validate_code_block_boundaries(path: &Path, lang: &Lang, text: &str, state: &mut RunState) {
    for block in code_blocks(text) {
        let has_import = block
            .content
            .lines()
            .any(|line| is_import_line(lang, line.trim_start()));
        let declaration_count = block
            .content
            .lines()
            .filter(|line| is_top_level_declaration(lang, line))
            .count();
        if has_import && declaration_count > 0 {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!(
                    "code block starting at line {} mixes imports with implementation; move imports to Uses or an import-only block",
                    block.start_line
                ),
            ));
        }

        if declaration_count > 1 {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!(
                    "code block starting at line {} contains multiple top-level implementations; split each logical unit into its own code block",
                    block.start_line
                ),
            ));
        }
    }
}

#[derive(Debug)]

struct CodeBlock<'a> {
    content: &'a str,
    start_line: usize,
}

fn code_blocks(text: &str) -> Vec<CodeBlock<'_>> {
    let mut blocks = Vec::new();
    let mut fence_len: Option<usize> = None;
    let mut content_start = 0;
    let mut content_start_line = 1;
    let mut cursor = 0;
    let mut line_number = 1;
    for line in text.split_inclusive('\n') {
        let line_start = cursor;
        cursor += line.len();
        if let Some((marker_len, suffix)) = backtick_fence(line) {
            if let Some(open_len) = fence_len {
                if is_closing_fence(marker_len, suffix, open_len) {
                    blocks.push(CodeBlock {
                        content: &text[content_start..line_start],
                        start_line: content_start_line,
                    });
                    fence_len = None;
                }
            } else {
                fence_len = Some(marker_len);
                content_start = cursor;
                content_start_line = line_number + 1;
            }
        }
        line_number += 1;
    }
    blocks
}

fn is_import_line(lang: &Lang, trimmed_start: &str) -> bool {
    match lang {
        Lang::Rust => {
            trimmed_start.starts_with("use ") || trimmed_start.starts_with("extern crate ")
        }
        Lang::TypeScript => {
            trimmed_start.starts_with("import ")
                || trimmed_start.starts_with("export ") && trimmed_start.contains(" from ")
                || trimmed_start.starts_with("const ") && trimmed_start.contains("require(")
                || trimmed_start.starts_with("let ") && trimmed_start.contains("require(")
                || trimmed_start.starts_with("var ") && trimmed_start.contains("require(")
        }
        Lang::Python => trimmed_start.starts_with("import ") || trimmed_start.starts_with("from "),
        Lang::Other(_) => false,
    }
}

fn is_top_level_declaration(lang: &Lang, line: &str) -> bool {
    if line.trim_start() != line {
        return false;
    }
    let trimmed = line.trim_start();
    if trimmed.is_empty() || is_comment_line(lang, trimmed) || is_import_line(lang, trimmed) {
        return false;
    }
    match lang {
        Lang::Rust => matches_top_level_keyword(
            trimmed,
            &[
                "pub fn ",
                "fn ",
                "pub struct ",
                "struct ",
                "pub enum ",
                "enum ",
                "pub trait ",
                "trait ",
                "impl ",
                "pub type ",
                "type ",
                "pub const ",
                "const ",
                "pub static ",
                "static ",
                "pub mod ",
                "mod ",
            ],
        ),
        Lang::TypeScript => matches_top_level_keyword(
            trimmed,
            &[
                "export function ",
                "function ",
                "export class ",
                "class ",
                "export interface ",
                "interface ",
                "export type ",
                "type ",
                "export const ",
                "const ",
                "export let ",
                "let ",
                "export enum ",
                "enum ",
            ],
        ),
        Lang::Python => matches_top_level_keyword(trimmed, &["def ", "async def ", "class "]),
        Lang::Other(_) => false,
    }
}

fn matches_top_level_keyword(line: &str, keywords: &[&str]) -> bool {
    keywords.iter().any(|keyword| line.starts_with(keyword))
}

fn is_comment_line(lang: &Lang, trimmed: &str) -> bool {
    match lang {
        Lang::Rust | Lang::TypeScript => {
            trimmed.starts_with("//") || trimmed.starts_with("/*") || trimmed.starts_with('*')
        }
        Lang::Python => trimmed.starts_with('#'),
        Lang::Other(_) => false,
    }
}

fn backtick_fence(line: &str) -> Option<(usize, &str)> {
    let trimmed = line.trim_start();
    let count = trimmed.chars().take_while(|char| *char == '`').count();
    (count >= 3).then_some((count, &trimmed[count..]))
}

fn is_closing_fence(marker_len: usize, suffix: &str, open_len: usize) -> bool {
    marker_len >= open_len && suffix.trim().is_empty()
}

pub fn sections_with_labels(
    text: &str,
    label_overrides: &HashMap<String, String>,
) -> HashMap<String, String> {
    let mut result = HashMap::new();
    let mut current: Option<String> = None;
    let mut body = String::new();
    for line in text.lines() {
        if let Some(title) = line.strip_prefix("## ") {
            let title = canonical_section_title(title.trim(), label_overrides);
            if let Some(name) = current.replace(title) {
                result.insert(name, body.trim_matches('\n').to_string());
                body.clear();
            }
        } else if current.is_some() {
            body.push_str(line);
            body.push('\n');
        }
    }
    if let Some(name) = current {
        result.insert(name, body.trim_matches('\n').to_string());
    }
    result
}

fn canonical_section_title(title: &str, label_overrides: &HashMap<String, String>) -> String {
    for canonical in [
        "Purpose", "Contract", "Types", "Source", "Cases", "Test", "Expose", "Exposes",
    ] {
        if title == canonical {
            return canonical.to_string();
        }
        let key = canonical.to_ascii_lowercase();
        if label_overrides
            .get(&key)
            .is_some_and(|override_label| override_label.trim() == title)
        {
            return canonical.to_string();
        }
    }
    title.to_string()
}

pub fn normalized_input(path: &Path, text: &str) -> String {
    let mut normalized = path.display().to_string();
    normalized.push('\n');
    normalized.push_str(text.replace("\r\n", "\n").trim_end());
    normalized.push('\n');
    normalized
}

pub fn validate_markdown_links(path: &Path, text: &str, state: &mut RunState) {
    let link_text = text_without_code_blocks(text);
    for target in standard_markdown_links(&link_text)
        .into_iter()
        .chain(wikilinks(&link_text))
    {
        if !should_validate_local_link(&target) {
            continue;
        }
        let clean_target = target
            .split('#')
            .next()
            .unwrap_or_default()
            .trim()
            .trim_matches('<')
            .trim_matches('>');
        if clean_target.is_empty() {
            continue;
        }
        let target_path = path
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join(clean_target);
        if !target_path.exists() {
            state.diagnostics.push(Diagnostic::error(
                Some(path.to_path_buf()),
                format!("Markdown link target does not exist: `{target}`"),
            ));
        }
    }
}

fn text_without_code_blocks(text: &str) -> String {
    let mut output = String::new();
    let mut fence_len: Option<usize> = None;
    for line in text.lines() {
        if let Some((marker_len, suffix)) = backtick_fence(line) {
            if let Some(open_len) = fence_len {
                if is_closing_fence(marker_len, suffix, open_len) {
                    fence_len = None;
                }
            } else {
                fence_len = Some(marker_len);
            }
            continue;
        }
        if fence_len.is_none() {
            output.push_str(line);
            output.push('\n');
        }
    }
    output
}

fn standard_markdown_links(text: &str) -> Vec<String> {
    let mut links = Vec::new();
    let bytes = text.as_bytes();
    let mut idx = 0;
    while idx < bytes.len() {
        if bytes[idx] != b'[' {
            idx += 1;
            continue;
        }
        let Some(close_text) = text[idx + 1..].find(']') else {
            break;
        };
        let open_target = idx + close_text + 2;
        if bytes.get(open_target) != Some(&b'(') {
            idx += 1;
            continue;
        }
        let Some(close_target) = text[open_target + 1..].find(')') else {
            break;
        };
        links.push(text[open_target + 1..open_target + 1 + close_target].to_string());
        idx = open_target + close_target + 2;
    }
    links
}

fn wikilinks(text: &str) -> Vec<String> {
    let mut links = Vec::new();
    let mut rest = text;
    while let Some(start) = rest.find("[[") {
        rest = &rest[start + 2..];
        let Some(end) = rest.find("]]") else {
            break;
        };
        let target = rest[..end]
            .split('|')
            .next()
            .unwrap_or_default()
            .trim()
            .to_string();
        links.push(target);
        rest = &rest[end + 2..];
    }
    links
}

fn should_validate_local_link(target: &str) -> bool {
    let target = target.trim();
    if target.is_empty()
        || target.starts_with('#')
        || target.starts_with("http://")
        || target.starts_with("https://")
        || target.starts_with("mailto:")
    {
        return false;
    }
    let clean = target.split('#').next().unwrap_or_default();
    clean.ends_with(".md") || clean.contains('/')
}
