use std::fs;
use std::path::Path;

use crate::diagnostics::{Diagnostic, RunState};
use crate::fs_utils::is_mds_managed_file;
use crate::model::NewOptions;

pub(crate) fn run_new(
    cwd: &Path,
    package: Option<&Path>,
    options: &NewOptions,
    _verbose: bool,
    state: &mut RunState,
) -> Result<(), String> {
    let root = package.map_or_else(|| cwd.to_path_buf(), |path| cwd.join(path));
    let src_md = root.join("src-md");
    let name = &options.name;

    let is_index = name == "index.md" || name.ends_with("/index.md");

    if !is_index {
        let lang = detect_lang(name);
        if lang.is_none() {
            return Err(format!(
                "cannot detect language from `{name}`; expected index.md or a name ending in .ts.md, .py.md, or .rs.md"
            ));
        }
    }

    let target = src_md.join(name);
    if target.exists() && !is_mds_managed_file(&target) && !options.force {
        state.diagnostics.push(Diagnostic::error(
            Some(target.clone()),
            "file already exists and is not mds-managed; use --force to overwrite",
        ));
        return Ok(());
    }

    let feature_name = extract_feature_name(name);
    let content = if is_index {
        generate_index_template(&feature_name)
    } else {
        generate_impl_template(name, &feature_name, detect_lang(name).unwrap())
    };

    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("failed to create {}: {e}", parent.display()))?;
    }
    fs::write(&target, &content)
        .map_err(|e| format!("failed to write {}: {e}", target.display()))?;

    state.generated.push(target.clone());
    state
        .stdout
        .push_str(&format!("created {}\n", target.display()));
    Ok(())
}

fn detect_lang(name: &str) -> Option<&'static str> {
    if name.ends_with(".ts.md") {
        Some("ts")
    } else if name.ends_with(".py.md") {
        Some("py")
    } else if name.ends_with(".rs.md") {
        Some("rs")
    } else {
        None
    }
}

fn extract_feature_name(name: &str) -> String {
    let base = name
        .trim_end_matches(".md")
        .trim_end_matches(".ts")
        .trim_end_matches(".py")
        .trim_end_matches(".rs");
    let base = if base == "index" || base.ends_with("/index") {
        if let Some(pos) = base.rfind('/') {
            let dir = &base[..pos];
            if let Some(pos2) = dir.rfind('/') {
                &dir[pos2 + 1..]
            } else {
                dir
            }
        } else {
            "Index"
        }
    } else if let Some(pos) = base.rfind('/') {
        &base[pos + 1..]
    } else {
        base
    };
    to_title_case(base)
}

fn to_title_case(s: &str) -> String {
    s.split(|c: char| c == '-' || c == '_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => {
                    let upper: String = first.to_uppercase().collect();
                    upper + chars.as_str()
                }
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn generate_index_template(feature_name: &str) -> String {
    format!(
        "<!-- Generated by mds new. -->\n\
         # {feature_name}\n\
         \n\
         ## Purpose\n\
         \n\
         Describe the purpose of this directory.\n\
         \n\
         ## Architecture\n\
         \n\
         Markdown files in this directory are the source of truth.\n\
         \n\
         ## Exposes\n\
         \n\
         | Kind | Name | Target | Summary |\n\
         | --- | --- | --- | --- |\n\
         \n\
         ## Rules\n\
         \n\
         - Keep one implementation md per feature.\n"
    )
}

fn generate_impl_template(name: &str, feature_name: &str, lang: &str) -> String {
    let (types_block, source_block, test_block) = match lang {
        "ts" => (
            ts_types_template(name, feature_name),
            ts_source_template(name, feature_name),
            ts_test_template(name, feature_name),
        ),
        "py" => (
            py_types_template(feature_name),
            py_source_template(feature_name),
            py_test_template(name, feature_name),
        ),
        "rs" => (
            rs_types_template(feature_name),
            rs_source_template(feature_name),
            rs_test_template(feature_name),
        ),
        _ => unreachable!(),
    };

    format!(
        "<!-- Generated by mds new. -->\n\
         # {feature_name}\n\
         \n\
         ## Purpose\n\
         \n\
         Describe the purpose of this feature.\n\
         \n\
         ## Expose\n\
         \n\
         | Kind | Name | Summary |\n\
         | --- | --- | --- |\n\
         \n\
         ## Uses\n\
         \n\
         | Kind | Name | From | Summary |\n\
         | --- | --- | --- | --- |\n\
         \n\
         ## Types\n\
         \n\
         {types_block}\n\
         \n\
         ## Source\n\
         \n\
         {source_block}\n\
         \n\
         ## Test\n\
         \n\
         {test_block}\n"
    )
}

fn ts_types_template(_name: &str, _feature_name: &str) -> String {
    "```ts\n// Define your types here.\n```".to_string()
}

fn ts_source_template(_name: &str, _feature_name: &str) -> String {
    "```ts\n// Implement your feature here.\n```".to_string()
}

fn ts_test_template(_name: &str, _feature_name: &str) -> String {
    "```ts\nimport { describe, it, expect } from \"vitest\";\n\ndescribe(\"TODO\", () => {\n  it(\"should work\", () => {\n    expect(true).toBe(true);\n  });\n});\n```".to_string()
}

fn py_types_template(_feature_name: &str) -> String {
    "```py\n# Define your types here.\n```".to_string()
}

fn py_source_template(_feature_name: &str) -> String {
    "```py\n# Implement your feature here.\n```".to_string()
}

fn py_test_template(_name: &str, _feature_name: &str) -> String {
    "```py\ndef test_todo():\n    assert True\n```".to_string()
}

fn rs_types_template(_feature_name: &str) -> String {
    "```rs\n// Define your types here.\n```".to_string()
}

fn rs_source_template(_feature_name: &str) -> String {
    "```rs\n// Implement your feature here.\n```".to_string()
}

fn rs_test_template(_feature_name: &str) -> String {
    "```rs\n#[cfg(test)]\nmod tests {\n    #[test]\n    fn test_todo() {\n        assert!(true);\n    }\n}\n```".to_string()
}
