// Generated by mds. Do not edit. Source: .mds/source/build.rs.md. Source-Hash: e7d5be00a33079298e28722fa61597d8876d3d580c952c85a1a0bdc767f50964.

use std::{env};
use std::{fs};
use std::path::{Path};
use std::path::{PathBuf};
