// Generated by mds. Do not edit. Source: .mds/source/diff.rs.md. Source-Hash: 36fc1408f8094f14b87246aeaf15e442b452b89099badf206e6ede11cca0f279.

use std::fs;
use std::path::Path;
use crate::diagnostics::RunState;
use crate::model::GeneratedFile;
