// Generated by mds. Do not edit. Source: .mds/source/diff.rs.md. Source-Hash: 654b20cf813bcffe7e5e255550f5217e87a3049756625d2bcdf9c2657e3d60cd.

use std::{fs};
use std::path::{Path};
use crate::diagnostics::{RunState};
use crate::model::{GeneratedFile};
