// Generated by mds. Do not edit. Source: .mds/source/doctor.rs.md. Source-Hash: 7eb8f80f7c8430a114b9757d29f87887046acbecad460606473e916912ddf15f.

use std::process::{Command as ProcessCommand};
use crate::adapter::{tool_available};
use crate::diagnostics::{Diagnostic};
use crate::diagnostics::{RunState};
use crate::model::{DoctorFormat};
use crate::model::{Package};
