// Generated by mds. Do not edit. Source: .mds/source/generation.rs.md. Source-Hash: a085794cf445ab95c68601b1ad743952204b7b909101cff372e39b1f55fa9d7c.

use std::ffi::{OsStr};
use std::{fs};
use std::path::{Path};
use crate::adapter::{output_relative_path};
use crate::descriptor::{output_root};
use crate::descriptor::{OutputRoot};
use crate::diagnostics::{Diagnostic};
use crate::diagnostics::{RunState};
use crate::fs_utils::{collect_files};
use crate::fs_utils::{is_excluded};
use crate::fs_utils::{is_mds_managed_file};
use crate::fs_utils::{path_within};
use crate::hash::{sha256};
use crate::manifest::{plan_manifest};
use crate::markdown::{source_markdown_root};
use crate::model::{DocKind};
use crate::model::{GeneratedFile};
use crate::model::{GeneratedKind};
use crate::model::{ImplDoc};
use crate::model::{Lang};
use crate::model::{OutputKind};
use crate::model::{Package};
