// Generated by mds. Do not edit. Source: .mds/source/manifest.rs.md. Source-Hash: dd8294bfb3ded00e4730b0d9174e1ae654caa98aaa40273fe8cdb8784ce56fd2.

use std::fs;
use std::path::{Component, Path};
use crate::diagnostics::{Diagnostic, RunState};
use crate::hash::sha256;
use crate::model::{GeneratedFile, GeneratedKind, ImplDoc, Package};
