// Generated by mds. Do not edit. Source: .mds/source/markdown.rs.md. Source-Hash: 0c986999fa43b0c5c6c063d125a35e65195502ff30ded881329f9b3cbdff9c44.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use crate::diagnostics::{Diagnostic, RunState};
use crate::fs_utils::{collect_files, is_excluded};
use crate::model::{DocKind, ImplDoc, Lang, Package};
