// Generated by mds. Do not edit. Source: .mds/source/new.rs.md. Source-Hash: 5aa08081c357025a8217ac3d9c58916460f2b1da9cbf7ef3ae6d541eedb398f9.

use std::collections::{HashMap};
use std::{fs};
use std::path::{Path};
use std::path::{PathBuf};
use crate::{descriptor};
use crate::diagnostics::{Diagnostic};
use crate::diagnostics::{RunState};
use crate::fs_utils::{is_mds_managed_file};
use crate::model::{NewOptions};
