// Generated by mds. Do not edit. Source: .mds/source/new.rs.md. Source-Hash: 6c9a9bd85a67123463c572e8e4e776381772fc675168340e736ae0b87a287bec.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use crate::descriptor;
use crate::diagnostics::{Diagnostic, RunState};
use crate::fs_utils::is_mds_managed_file;
use crate::model::NewOptions;
