// Generated by mds. Do not edit. Source: .mds/source/package.rs.md. Source-Hash: b6b8373ba5d96bfcca9c16a1a4e25e43849c4626f2335d8719d12000ade9b5dd.

use std::collections::{HashMap, HashSet};
use std::ffi::OsStr;
use std::fs;
use std::path::Path;
use regex::Regex;
use crate::config::merge_config_file;
use crate::descriptor;
use crate::diagnostics::{Diagnostic, RunState};
use crate::fs_utils::{collect_files, is_excluded};
use crate::markdown::{sections_with_labels, source_markdown_root, validate_markdown_links};
use crate::model::{Package, PackageMetadata};
use crate::table::parse_table_with_labels;
