// Generated by mds. Do not edit. Source: .mds/source/runner.rs.md. Source-Hash: ac43a74cbe31af2887ee193e0bcaf115f48099b34de9d8c237d2b4dd7b174754.

use std::fs;
use std::path::Path;
use crate::descriptor::set_workspace_descriptor_root;
use crate::diagnostics::{Diagnostic, RunState};
use crate::diff::{render_dry_run, write_generated};
use crate::doctor::run_doctor;
use crate::generation::plan_generation;
use crate::init::run_init;
use crate::manifest::validate_manifest;
use crate::markdown::load_implementation_docs;
use crate::model::{BuildMode, CliRequest, CliResult, Command, Package};
use crate::new::run_new;
use crate::package::{discover_packages, validate_index_docs, validate_package_md};
use crate::package_sync::sync_package_md;
use crate::quality::{run_quality, QualityOperation};
