// Generated by mds. Do not edit. Source: .mds/source/table.rs.md. Source-Hash: 98b93b453a117cc9cb44016e9d90116fa3675fb01d701bf68392a5c36eb981b8.

use std::collections::HashMap;
use std::path::Path;
use crate::diagnostics::{Diagnostic, RunState};
