// Generated by mds. Do not edit. Source: .mds/test/greet.test.ts.md. Source-Hash: 99bcde688b3b78046bc3f286fbb9770542dd605b6776e0761958aceeaa00c354.

import { describe, expect, it } from "vitest";
import { greet } from "../src/greet";

describe("greet", () => {
  it("returns greeting with name", () => {
    expect(greet({ name: "World" })).toBe("Hello, World!");
  });

  it("uses Anonymous when name is missing", () => {
    expect(greet({})).toBe("Hello, Anonymous!");
  });
});
