// Generated by mds. Do not edit. Source: .mds/source/convert.rs.md. Source-Hash: b1ee57f467f30dd51ede4aa7aff33b15876ed2e35b22d9bae64aa5d44ba9e1b2.

use mds_core::{Diagnostic};
use mds_core::{Severity};
use tower_lsp::{lsp_types};
