// Generated by mds. Do not edit. Source: .mds/test/diagnostics.rs.md. Source-Hash: 6007d334a978398288b0cacef80b5fa8a0a5ce3096e285b38b8c837f1f92f469.

use std::path::{PathBuf};
use mds_core::{Config};
use mds_lsp::capabilities::{diagnostics};
fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(format!("/tmp/mds-test/{name}"))
}

fn sample_markdown(text: &str) -> String {
    text.replace("{h2}", "##")
        .replace("{h5}", "#####")
        .replace("{fence}", "```")
}

#[test]
fn test_valid_impl_md_no_diagnostics_for_minimal() {
    let text = sample_markdown(r#"{h2} Purpose

A minimal test module.

{h2} Contract

Public contract.

{h2} Types

### Uses

| From | Target | Expose | Summary |
| --- | --- | --- | --- |
| builtin | node:path | join | Path join utility |

{fence}typescript
export type MyType = string;
{fence}

{h2} Source

### Uses

| From | Target | Expose | Summary |
| --- | --- | --- | --- |
| internal | utils/helper | helper | Helper function |

{fence}typescript
export function main(): void {}
{fence}

{h2} Cases

Basic use case.

{h2} Test

### Uses

| From | Target | Expose | Summary |
| --- | --- | --- | --- |
| internal | utils/helper | helper | Helper function |

{fence}typescript
test("it works", () => {});
{fence}
"#);

    let path = fixture_path("valid.ts.md");
    let config = Config::default();
    let diags = diagnostics::validate_impl_md_text(&path, &text, &config);
    assert!(diags.is_empty(), "expected no diagnostics, got: {diags:?}");
}

#[test]
fn test_missing_sections() {
    // With the new format, the only requirement is at least one code block
    let text = sample_markdown(r#"{h2} Purpose

A module with no code blocks.
"#);

    let path = fixture_path("missing.ts.md");
    let config = Config::default();
    let diags = diagnostics::validate_impl_md_text(&path, &text, &config);

    let messages: Vec<&str> = diags.iter().map(|d| d.message.as_str()).collect();
    assert!(
        messages.iter().any(|m| m.contains("code block")),
        "should report missing code block: {messages:?}"
    );
}

#[test]
fn test_heading_depth_violation() {
    // H5+ is no longer an error in the new format
    let text = sample_markdown(r#"{h2} Purpose

A module.

{h5} Deep heading is allowed now

{h2} Source

{fence}typescript
function main() {}
{fence}
"#);

    let path = fixture_path("deep-heading.ts.md");
    let config = Config::default();
    let diags = diagnostics::validate_impl_md_text(&path, &text, &config);

    // No heading-depth errors anymore
    let messages: Vec<&str> = diags.iter().map(|d| d.message.as_str()).collect();
    assert!(
        !messages.iter().any(|m| m.contains("H3-H4")),
        "should not report deep heading: {messages:?}"
    );
}

#[test]
fn test_config_validation_invalid_toml() {
    let text = "this is not valid toml [[[";
    let path = fixture_path("mds.config.toml");
    let diags = diagnostics::validate_config_text(&path, text);
    assert!(!diags.is_empty(), "should report TOML parse error");
}

#[test]
fn test_package_index_missing_sections() {
    let text = sample_markdown(r#"{h2} Package

| Name | Version |
| --- | --- |
| test-pkg | 1.0.0 |
"#);

    let path = fixture_path("index.md");
    let config = Config::default();
    let diags = diagnostics::validate_package_md_text(&path, &text, &config);

    let messages: Vec<&str> = diags.iter().map(|d| d.message.as_str()).collect();
    assert!(
        messages.iter().any(|m| m.contains("Dependencies")),
        "should report missing Dependencies: {messages:?}"
    );
    assert!(
        messages.iter().any(|m| m.contains("Rules")),
        "should report missing Rules: {messages:?}"
    );
}

#[test]
fn test_code_block_language_mismatch_warning() {
    let text = sample_markdown(r#"{h2} Purpose

A module.

{h2} Contract

Contract.

{h2} Types

{fence}python
x = 1
{fence}

{h2} Source

{fence}python
def main(): pass
{fence}

{h2} Cases

Cases.

{h2} Test

{fence}python
def test_it(): assert True
{fence}
"#);

    // File is .ts.md but code blocks use python
    let path = fixture_path("mismatch.ts.md");
    let config = Config::default();
    let diags = diagnostics::validate_impl_md_text(&path, &text, &config);

    let warnings: Vec<&str> = diags
        .iter()
        .filter(|d| d.severity == Some(tower_lsp::lsp_types::DiagnosticSeverity::WARNING))
        .map(|d| d.message.as_str())
        .collect();
    assert!(
        warnings
            .iter()
            .any(|m| m.contains("python") && m.contains("ts")),
        "should warn about language mismatch: {warnings:?}"
    );
}

#[test]
fn test_empty_document_diagnostics() {
    let text = "";
    let path = fixture_path("empty.ts.md");
    let config = Config::default();
    let diags = diagnostics::validate_impl_md_text(&path, text, &config);
    // Should report missing code block
    assert!(
        !diags.is_empty(),
        "empty doc should report missing code block: {diags:?}"
    );
    assert!(
        diags.iter().any(|d| d.message.contains("code block")),
        "should mention code block requirement: {diags:?}"
    );
}

#[test]
fn test_valid_config_no_diagnostics() {
    // Write a valid config to a temp file
    let dir = tempfile::tempdir().unwrap();
    let config_path = dir.path().join("mds.config.toml");
    std::fs::write(
        &config_path,
        "[package]\nenabled = true\n\n[roots]\nmarkdown = \"src-md\"\n",
    )
    .unwrap();

    let diags = diagnostics::validate_config_text(
        &config_path,
        "[package]\nenabled = true\n\n[roots]\nmarkdown = \"src-md\"\n",
    );
    // May have diagnostics about missing index.md etc, but no TOML errors
    let toml_errors: Vec<&str> = diags
        .iter()
        .filter(|d| d.message.contains("TOML"))
        .map(|d| d.message.as_str())
        .collect();
    assert!(
        toml_errors.is_empty(),
        "valid TOML should not have parse errors: {toml_errors:?}"
    );
}

#[test]
fn test_package_index_full_valid() {
    let text = sample_markdown(r#"{h2} Package

| Name | Version |
| --- | --- |
| test-pkg | 1.0.0 |

{h2} Dependencies

No dependencies.

{h2} Dev Dependencies

No dev dependencies.

{h2} Rules

No special rules.
"#);

    let path = fixture_path("index.md");
    let config = Config::default();
    let diags = diagnostics::validate_package_md_text(&path, &text, &config);
    assert!(
        diags.is_empty(),
        "valid index.md should have no errors: {diags:?}"
    );
}
