id = "css"
match_suffixes = ["css"]

[language]
primary_ext = "css"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "css"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "css"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = ".test"
extension = "css"

[imports]
style = "none"

[syntax]
top_level_keywords = [":root", "@media ", "@layer ", "@keyframes ", ".", "#"]
comment_prefixes = ["/*", "*"]

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
.feature {
  display: block;
}
'''