id = "html"
match_suffixes = ["html"]

[language]
primary_ext = "html"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "html"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "html"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = ".test"
extension = "html"

[imports]
style = "none"

[syntax]
top_level_keywords = ["<!DOCTYPE", "<html", "<body", "<main", "<section", "<div"]
comment_prefixes = ["<!--"]

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
<div><!-- Implement your feature here. --></div>
'''