id = "ruby"
aliases = ["rb"]
match_suffixes = ["rb", "ruby"]

[language]
primary_ext = "rb"

[files.source]
strip_lang_ext = false
prefix = ""
suffix = ""
extension = "rb"

[files.types]
strip_lang_ext = true
prefix = ""
suffix = ".types"
extension = "rb"

[files.test]
strip_lang_ext = true
prefix = ""
suffix = "_test"
extension = "rb"

[imports]
style = "ruby"

[syntax]
top_level_keywords = ["class ", "module ", "def ", "require ", "extend ", "include "]
comment_prefixes = ["#"]

[[syntax.imports]]
starts_with = "require "

[[syntax.imports]]
starts_with = "require_relative "

[scaffold]
fence_lang = "matched-suffix"
source_body = '''
# Implement your feature here.
'''