id = "conan"
display_name = "Conan"
lang = "cpp"
metadata_files = ["conanfile.txt", "conanfile.py"]
lockfiles = ["conan.lock"]
metadata_reader = "conan-text"

[commands]
install = "conan install ."
build = "conan build ."
typecheck = "conan build ."
lint = "clang-tidy"
test = "ctest"