id = "dotnet"
display_name = ".NET SDK"
lang = "cs"
metadata_files = ["*.csproj"]
lockfiles = ["packages.lock.json"]
metadata_reader = "dotnet-xml"

[commands]
install = "dotnet restore"
build = "dotnet build"
typecheck = "dotnet build"
lint = "dotnet format --verify-no-changes"
test = "dotnet test"