id = "hatch"
display_name = "Python (Hatch)"
lang = "py"
metadata_files = ["pyproject.toml"]
lockfiles = ["hatch.lock"]
metadata_reader = "pyproject-toml"

[commands]
install = "hatch env create"
build = "hatch build"
typecheck = "hatch run mypy ."
lint = "hatch run ruff check"
test = "hatch run pytest"