id = "meson"
display_name = "Meson"
lang = "cpp"
metadata_files = ["meson.build"]
lockfiles = ["meson-private/coredata.dat"]
metadata_reader = "meson-text"

[commands]
install = "meson setup build"
build = "meson compile -C build"
typecheck = "meson compile -C build"
lint = "clang-tidy"
test = "meson test -C build"