id = "pdm"
display_name = "Python (PDM)"
lang = "py"
metadata_files = ["pyproject.toml"]
lockfiles = ["pdm.lock"]
metadata_reader = "pyproject-toml"

[commands]
install = "pdm install"
build = "pdm build"
typecheck = "pdm run mypy ."
lint = "pdm run ruff check"
test = "pdm run pytest"