id = "pnpm"
display_name = "Node.js (pnpm)"
lang = "ts"
metadata_files = ["package.json"]
lockfiles = ["pnpm-lock.yaml"]
metadata_reader = "node-package-json"

[commands]
install = "pnpm install"
build = "pnpm build"
typecheck = "pnpm typecheck"
lint = "pnpm lint"
test = "pnpm test"