id = "yarn"
display_name = "Node.js (Yarn)"
lang = "ts"
metadata_files = ["package.json"]
lockfiles = ["yarn.lock"]
metadata_reader = "node-package-json"

[commands]
install = "yarn install"
build = "yarn build"
typecheck = "yarn typecheck"
lint = "yarn lint"
test = "yarn test"