id = "zig-build"
aliases = ["zig"]
display_name = "Zig"
lang = "zig"
metadata_files = ["build.zig.zon", "build.zig"]
lockfiles = ["zig-cache"]
metadata_reader = "zig-zon"

[commands]
install = "zig build"
build = "zig build"
typecheck = "zig build"
lint = "zig fmt --check ."
test = "zig test"