[package]
enabled = true
allow_raw_source = false

[roots]
markdown = "src-md"
source = "../.build/rust/mds-lsp"
types = "../.build/rust/mds-lsp"
test = "../.build/rust/mds-lsp"
excludes = []

[quality.rs]
linter = "cargo clippy -- -D warnings"
fixer = "cargo fmt"
test_runner = "cargo test"
required = ["rustc", "cargo", "rustfmt"]
optional = ["clippy-driver"]
