// Generated by mds. Do not edit. Source: .mds/source/greet.ts.md. Source-Hash: 90e2d39ddf35ea62c242ca021d510b72130fa73f3bce5653639629271aea5cd4.

export interface GreetOptions {
  name: string;
}

export function greet(options: GreetOptions): string {
  return `Hello, ${options.name}!`;
}
