// Generated by mds. Do not edit. Source: .mds/source/greet.ts.md. Source-Hash: 7f5c32b5095955d84266f0c21b15f3d6552794e4e917541126d718fccb457236.

export interface GreetOptions {
  name?: string;
}

export function greet(options: GreetOptions): string {
  const name = options.name?.trim() || "Anonymous";
  return `Hello, ${name}!`;
}
