// Generated by mds. Do not edit. Source: .mds/source/greet.ts.md. Source-Hash: f486702f67202efb88e34eeef9ce899e9dcb5b38fee0fe8fff9426f866c77720.

export interface GreetOptions {
  name: string;
}

export function greet(options: GreetOptions): string {
  return `Hello, ${options.name}!`;
}
