id = "clang-tidy"
match_prefixes = ["clang-tidy"]

[behavior]
input = "stdin"
append_file_arg = true

[[behavior.diagnostics]]
pattern = '^(?P<path>.+?):(?P<line>\d+):(?P<column>\d+): (?P<message>.+)$'