#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
SOURCE_ROOT="$ROOT/src-md"
BUILD_ROOT="$ROOT/.build"
RUST_BUILD_ROOT="$BUILD_ROOT/rust"

if [[ ! -d "$SOURCE_ROOT" ]]; then
  echo "error: source root not found: $SOURCE_ROOT" >&2
  exit 1
fi

rm -rf "$RUST_BUILD_ROOT"
mkdir -p "$RUST_BUILD_ROOT"

python3 - "$ROOT" <<'PY'
from pathlib import Path
import hashlib
import shutil
import sys

root = Path(sys.argv[1])
source_root = root / "src-md"
rust_build_root = root / ".build" / "rust"

packages = ["mds-core", "mds-cli", "mds-lsp"]

def extract_code_blocks(text: str) -> str:
    blocks = []
    current = []
    in_block = False
    for line in text.splitlines():
        if line.lstrip().startswith("````"):
            if in_block:
                blocks.append("\n".join(current).rstrip())
                current = []
                in_block = False
            else:
                in_block = True
            continue
        if in_block:
            current.append(line)
    return "\n\n".join(blocks).rstrip() + "\n"


def generated_header(path: Path, source_rel: Path) -> str:
    text = path.read_text(encoding="utf-8")
    normalized = f"{path}\n{text.replace(chr(13) + chr(10), chr(10)).rstrip()}\n"
    source_hash = hashlib.sha256(normalized.encode()).hexdigest()
    return (
        "// Generated by mds. Do not edit. "
        f"Source: {source_rel.as_posix()}. Source-Hash: {source_hash}.\n\n"
    )


shutil.copy2(source_root / "Cargo.toml", rust_build_root / "Cargo.toml")
if (source_root / "Cargo.lock").exists():
    shutil.copy2(source_root / "Cargo.lock", rust_build_root / "Cargo.lock")

for package in packages:
    package_source = source_root / package
    package_build = rust_build_root / package
    package_build.mkdir(parents=True, exist_ok=True)
    shutil.copy2(package_source / "Cargo.toml", package_build / "Cargo.toml")

    for path in package_source.rglob("*"):
        if path.is_dir():
            continue

        rel = path.relative_to(package_source)
        if rel in {Path("Cargo.toml"), Path("package.md"), Path("index.md")}:
            continue
        if rel.name == "index.md":
            continue

        if path.name.endswith(".rs.md"):
            output_rel = rel.with_name(rel.name[:-3])
            output_path = package_build / output_rel
            output_path.parent.mkdir(parents=True, exist_ok=True)
            code = extract_code_blocks(path.read_text(encoding="utf-8"))
            output_path.write_text(
                generated_header(path, path.relative_to(root)) + code,
                encoding="utf-8",
            )
            continue

        if path.suffix == ".md" and "templates" not in rel.parts:
            continue

        output_path = package_build / rel
        output_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, output_path)
PY

echo "synced Rust workspace to $RUST_BUILD_ROOT"
