// Generated by mds. Do not edit. Source: .mds/source/init/mod.rs.md. Source-Hash: 93c3d0cd78fde2d537e5613679c1d853dc0445513b60f080e9bf2ca7d9d47c0f.

use std::{fs};
use std::path::{Path};
use std::path::{PathBuf};
use std::process::{Command as ProcessCommand};
use crate::{descriptor};
use crate::diagnostics::{Diagnostic};
use crate::diagnostics::{RunState};
use crate::fs_utils::{is_mds_managed_file};
use crate::model::{AgentKitCategory};
use crate::model::{AiTarget};
use crate::model::{InitOptions};
use crate::model::{InitQualityCommands};
use crate::model::{LabelPreset};
use crate::model::{Lang};
use crate::model::{PythonTool};
use crate::model::{RustTool};
use crate::model::{TypeScriptTool};
mod template_registry {
    include!(concat!(env!("OUT_DIR"), "/template_registry.rs"));
}

pub(crate) fn run_init(
    cwd: &Path,
    package: Option<&Path>,
    options: &InitOptions,
    verbose: bool,
    state: &mut RunState,
) -> Result<(), String> {
    let root = package.map_or_else(|| cwd.to_path_buf(), |path| cwd.join(path));
    let mut files = Vec::new();
    let detected_package_manager = descriptor::detect_package_manager(&root);

    if !options.ai_only {
        if detected_package_manager.is_none() {
            state.diagnostics.push(Diagnostic::error(
                Some(root.clone()),
                "mds init requires an existing recognized package manager metadata file",
            ));
            return Ok(());
        }
        files.extend(project_files(&root, options));
    }
    files.extend(ai_files(&root, options, options.label_preset));

    state.stdout.push_str("Init plan:\n");
    for file in &files {
        state
            .stdout
            .push_str(&format!("- write {}\n", file.path.display()));
    }

    let setup_actions = setup_actions(&root, options, detected_package_manager.as_ref());
    if !setup_actions.is_empty() {
        state.stdout.push_str("Setup plan:\n");
        for action in &setup_actions {
            state.stdout.push_str(&format!(
                "- {}: {}{}\n",
                action.kind,
                action.command.join(" "),
                action
                    .install_hint
                    .map(|hint| format!(" (install: {hint})"))
                    .unwrap_or_default()
            ));
        }
    }

    if !options.yes {
        state
            .stdout
            .push_str("No changes written. Re-run with --yes to apply the init plan.\n");
        return Ok(());
    }

    for file in files {
        write_planned_file(&file, options.force, state)?;
    }

    for action in setup_actions {
        run_setup_action(&root, &action, verbose, state);
    }

    if !state.has_errors() && !state.environment_missing {
        if !options.targets.is_empty() {
            state.stdout.push_str(&ai_post_init_guide(&options.targets));
        }
        state.stdout.push_str("init ok\n");
    }
    Ok(())
}

struct PlannedFile {
    path: PathBuf,
    content: String,
}

struct SetupAction {
    kind: &'static str,
    command: Vec<String>,
    install_hint: Option<&'static str>,
}

fn project_files(root: &Path, options: &InitOptions) -> Vec<PlannedFile> {
    let name = root
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or("mds-project");
    let preset = options.label_preset;
    let l_name = preset.section_label("name");
    let l_summary = preset.section_label("summary");
    let l_purpose = preset.section_label("purpose");
    let pkg_name = sanitize_package_name(name);
    let root_module = package_root_markdown_name(root);
    let files = vec![
        PlannedFile {
            path: root.join("mds.config.toml"),
            content: project_config(options),
        },
        PlannedFile {
            path: root.join(".mds/source/overview.md"),
            content: format!(
                "<!-- Generated by mds init. -->\n# Source Overview\n\n## {l_purpose}\n\nDescribe the `.mds/source/` hierarchy.\n\n## Architecture\n\nMarkdown files in this directory describe package and source hierarchy rules.\n\n### Package Summary\n\n| {l_name} | Version |\n| --- | --- |\n| {pkg_name} | 0.1.0 |\n\n### Dependencies\n\n| {l_name} | Version | {l_summary} |\n| --- | --- | --- |\n\n### Dev Dependencies\n\n| {l_name} | Version | {l_summary} |\n| --- | --- | --- |\n\n## Rules\n\n- Keep package or directory root Imports / Exports in `{root_module}`.\n- Keep one source md per feature.\n",
            ),
        },
        PlannedFile {
            path: root.join(".mds/source").join(&root_module),
            content: format!(
                "<!-- Generated by mds init. -->\n# Package Root\n\n## {l_purpose}\n\nDescribe the package root module surface.\n\n## API\n\nDescribe public exports in prose. Keep import and export declarations in implementation code blocks instead of duplicate tables.\n",
            ),
        },
        PlannedFile {
            path: root.join(".mds/test/overview.md"),
            content: format!(
                "<!-- Generated by mds init. -->\n# Test Overview\n\n## {l_purpose}\n\nDescribe the `.mds/test/` hierarchy.\n\n## Architecture\n\nMarkdown files in this directory define test intent and executable test code.\n\n## Rules\n\n- Keep one test md per verification target.\n- Use `Covers` to point at the source module id being verified.\n",
            ),
        },
        PlannedFile {
            path: root.join(".mds/reference/overview.md"),
            content: "# Source Overview Example\n\n## Purpose\n\nDescribe the source hierarchy and package-level intent.\n\n## Architecture\n\nSummarize how source markdown maps to generated code.\n\n### Package Summary\n\n| Name | Version |\n| --- | --- |\n| example-package | 0.1.0 |\n\n### Dependencies\n\n| Name | Version | Summary |\n| --- | --- | --- |\n\n### Dev Dependencies\n\n| Name | Version | Summary |\n| --- | --- | --- |\n\n## Rules\n\n- Keep package or directory root Imports / Exports in language root markdown such as `index.ts.md` or `lib.rs.md`.\n- Keep one source md per feature.\n"
                .to_string(),
        },
        PlannedFile {
            path: root.join(".mds/reference/root-module.md"),
            content: "# Package Root Example\n\n## Purpose\n\nDescribe the package root module surface.\n\n## Exports\n\n| Name | Visibility | Summary |\n| --- | --- | --- |\n| greet | public | Public greeting function |\n\n## Imports\n\n| From | Target | Symbols | Via | Summary | Reference |\n| --- | --- | --- | --- | --- | --- |\n| internal | ./greet | greet | - | Greeting entrypoint | [./greet.ts.md#greet](./greet.ts.md#greet) |\n"
                .to_string(),
        },
        PlannedFile {
            path: root.join(".mds/reference/impl.md"),
            content: "# greet\n\n## Purpose\n\nProvide the greeting entrypoint.\n\n## Contract\n\n- Return a greeting string for the supplied name.\n\n## Exports\n\n| Name | Visibility | Summary |\n| --- | --- | --- |\n| greet | public | Public greeting function |\n\n##### greet\n\nShared entrypoint referenced from tests and other modules.\n\n## Imports\n\n| From | Target | Symbols | Via | Summary | Reference |\n| --- | --- | --- | --- | --- | --- |\n| internal | ./format-name | formatName | - | Name formatter | [./format-name.ts.md#format-name](./format-name.ts.md#format-name) |\n\n## Types\n\n```ts\nexport type Greeting = string;\n```\n\n## Source\n\n```ts\nexport function greet(name: string): Greeting {\n  return `Hello, ${formatName(name)}`;\n}\n```\n\n## Cases\n\n- Returns a stable greeting for a valid name.\n"
                .to_string(),
        },
        PlannedFile {
            path: root.join(".mds/reference/test.md"),
            content: "# greet test\n\n## Purpose\n\nVerify the greeting behavior.\n\n## Covers\n\n- greet\n\n## Imports\n\n| From | Target | Symbols | Via | Summary | Reference |\n| --- | --- | --- | --- | --- | --- |\n| internal | ./greet | greet | - | Function under test | [./greet.ts.md#greet](./greet.ts.md#greet) |\n| external | vitest | describe, expect, it | - | Test helpers | - |\n\n## Cases\n\n- Returns `Hello, Ada` for `Ada`.\n\n## Test\n\n```ts\ndescribe('greet', () => {\n  it('returns a greeting', () => {\n    expect(greet('Ada')).toBe('Hello, Ada');\n  });\n});\n```\n"
                .to_string(),
        },
    ];
    files
}

fn package_root_markdown_name(root: &Path) -> String {
    let lang = descriptor::detect_package_manager(root)
        .map(|manager| manager.lang)
        .unwrap_or_else(|| "ts".to_string());
    let descriptor = descriptor::descriptor_for_key(&lang)
        .or_else(|| descriptor::descriptor_for_key("ts"))
        .expect("default language descriptor");
    format!("index.{}.md", descriptor.language.primary_ext)
}

fn project_config(options: &InitOptions) -> String {
    let mut content = "# Generated by mds init.\n[package]\nenabled = true\nallow_raw_source = false\n\n[roots]\nsource = \"src\"\ntypes = \"src\"\ntest = \"tests\"\n".to_string();
    for descriptor in descriptor::builtin_language_descriptors() {
        content.push_str(&render_quality(
            &descriptor.id,
            quality_for_lang(options, Lang::Other(descriptor.id.clone())),
        ));
    }
    if !options.label_preset.labels().is_empty() {
        content.push_str("\n[labels]\n");
        for (key, value) in options.label_preset.labels() {
            content.push_str(&format!("{key} = \"{value}\"\n"));
        }
    }
    content
}

struct InitQuality {
    type_check: Option<String>,
    lint: Option<String>,
    fix: Option<String>,
    test: Option<String>,
    required: Vec<String>,
    optional: Vec<String>,
}

fn quality_for_lang(options: &InitOptions, lang: Lang) -> InitQuality {
    if let Some(commands) = options
        .quality_commands
        .iter()
        .find(|commands| commands.lang.key() == lang.key())
    {
        return custom_quality(commands);
    }
    let descriptor = descriptor::builtin_descriptor(&lang);
    let mut quality = init_quality_from_defaults(&descriptor);
    apply_legacy_quality_options(options, &descriptor, &mut quality);
    quality
}

fn custom_quality(commands: &InitQualityCommands) -> InitQuality {
    InitQuality {
        type_check: commands.type_check.clone(),
        lint: commands.lint.clone(),
        fix: None,
        test: commands.test.clone(),
        required: Vec::new(),
        optional: Vec::new(),
    }
}

fn init_quality_from_defaults(descriptor: &descriptor::Descriptor) -> InitQuality {
    let mut quality = InitQuality {
        type_check: descriptor.default_typecheck_command().map(str::to_string),
        lint: descriptor.default_lint_command().map(str::to_string),
        fix: descriptor.default_fix_command().map(str::to_string),
        test: descriptor.default_test_command().map(str::to_string),
        required: Vec::new(),
        optional: Vec::new(),
    };
    add_default_profile_tools(descriptor, &mut quality);
    quality
}

fn add_default_profile_tools(descriptor: &descriptor::Descriptor, quality: &mut InitQuality) {
    if let Some(command) = quality.type_check.clone() {
        if let Some(profile) = descriptor.typecheck_profile_for_command(&command) {
            add_profile_tools(quality, profile);
        }
    }
    if let Some(command) = quality.lint.clone() {
        if let Some(profile) = descriptor.lint_profile_for_command(&command) {
            add_profile_tools(quality, profile);
        }
    }
    if let Some(command) = quality.fix.clone() {
        if let Some(profile) = descriptor.fix_profile_for_command(&command) {
            add_profile_tools(quality, profile);
        }
    }
    if let Some(command) = quality.test.clone() {
        if let Some(profile) = descriptor.test_profile_for_command(&command) {
            add_profile_tools(quality, profile);
        }
    }
}

fn apply_legacy_quality_options(
    options: &InitOptions,
    descriptor: &descriptor::Descriptor,
    quality: &mut InitQuality,
) {
    match descriptor.id.as_str() {
        "ts" => apply_typescript_tools(&options.ts_tools, descriptor, quality),
        "py" => apply_python_tools(&options.py_tools, descriptor, quality),
        "rs" => apply_rust_tools(&options.rs_tools, descriptor, quality),
        _ => {}
    }
}

fn apply_typescript_tools(
    tools: &[TypeScriptTool],
    descriptor: &descriptor::Descriptor,
    quality: &mut InitQuality,
) {
    clear_quality(quality);
    for tool in tools {
        match tool {
            TypeScriptTool::Eslint => select_lint_profile(descriptor, quality, "eslint"),
            TypeScriptTool::Prettier => select_fix_profile(descriptor, quality, "prettier"),
            TypeScriptTool::Biome => {
                select_lint_profile(descriptor, quality, "biome");
                select_fix_profile(descriptor, quality, "biome");
            }
            TypeScriptTool::Vitest => select_test_profile(descriptor, quality, "vitest"),
            TypeScriptTool::Jest => select_test_profile(descriptor, quality, "jest"),
        }
    }
}

fn apply_python_tools(
    tools: &[PythonTool],
    descriptor: &descriptor::Descriptor,
    quality: &mut InitQuality,
) {
    clear_quality(quality);
    for tool in tools {
        match tool {
            PythonTool::Ruff => {
                select_lint_profile(descriptor, quality, "ruff");
                select_fix_profile(descriptor, quality, "ruff");
            }
            PythonTool::Black => select_fix_profile(descriptor, quality, "black"),
            PythonTool::Pytest => select_test_profile(descriptor, quality, "pytest"),
            PythonTool::Unittest => select_test_profile(descriptor, quality, "unittest"),
        }
    }
}

fn apply_rust_tools(
    tools: &[RustTool],
    descriptor: &descriptor::Descriptor,
    quality: &mut InitQuality,
) {
    clear_quality(quality);
    for tool in tools {
        match tool {
            RustTool::Rustfmt => select_fix_profile(descriptor, quality, "rustfmt"),
            RustTool::Clippy => select_lint_profile(descriptor, quality, "clippy"),
            RustTool::CargoTest => select_test_profile(descriptor, quality, "cargo-test"),
            RustTool::Nextest => select_test_profile(descriptor, quality, "nextest"),
        }
    }
}

fn clear_quality(quality: &mut InitQuality) {
    quality.type_check = None;
    quality.lint = None;
    quality.fix = None;
    quality.test = None;
    quality.required.clear();
    quality.optional.clear();
}

fn select_lint_profile(
    descriptor: &descriptor::Descriptor,
    quality: &mut InitQuality,
    key: &str,
) {
    if let Some(profile) = descriptor.lint_profile(key) {
        quality.lint = Some(profile.command.clone());
        add_profile_tools(quality, profile);
    }
}

fn select_fix_profile(
    descriptor: &descriptor::Descriptor,
    quality: &mut InitQuality,
    key: &str,
) {
    if let Some(profile) = descriptor.fix_profile(key) {
        quality.fix = Some(profile.command.clone());
        add_profile_tools(quality, profile);
    }
}

fn select_test_profile(
    descriptor: &descriptor::Descriptor,
    quality: &mut InitQuality,
    key: &str,
) {
    if let Some(profile) = descriptor.test_profile(key) {
        quality.test = Some(profile.command.clone());
        add_profile_tools(quality, profile);
    }
}

fn add_profile_tools(quality: &mut InitQuality, profile: &descriptor::ToolProfile) {
    for tool in &profile.required {
        add_unique(&mut quality.required, tool);
    }
    for tool in &profile.optional {
        add_unique(&mut quality.optional, tool);
    }
}


fn add_unique(values: &mut Vec<String>, value: &str) {
    if !values.iter().any(|current| current == value) {
        values.push(value.to_string());
    }
}

fn render_quality(lang: &str, quality: InitQuality) -> String {
    let mut content = format!("\n[quality.{lang}]\n");
    if quality.type_check.is_some() {
        content.push_str(&format!(
            "type_checker = {}\n",
            render_optional_owned_command(quality.type_check.as_deref())
        ));
    }
    content.push_str(&format!(
        "linter = {}\nfixer = {}\ntest_runner = {}\nrequired = [{}]\noptional = [{}]\n",
        render_optional_command(quality.lint.as_deref()),
        render_optional_command(quality.fix.as_deref()),
        render_optional_command(quality.test.as_deref()),
        render_string_array(&quality.required),
        render_string_array(&quality.optional),
    ));
    content
}

fn render_optional_command(command: Option<&str>) -> String {
    command
        .map(|command| format!("\"{command}\""))
        .unwrap_or_else(|| "false".to_string())
}

fn render_optional_owned_command(command: Option<&str>) -> String {
    command
        .filter(|command| !command.trim().is_empty())
        .map(|command| format!("\"{command}\""))
        .unwrap_or_else(|| "false".to_string())
}

fn render_string_array(values: &[String]) -> String {
    values
        .iter()
        .map(|value| format!("\"{value}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn ai_files(root: &Path, options: &InitOptions, label_preset: LabelPreset) -> Vec<PlannedFile> {
    let mut files = Vec::new();
    if options.target_categories.is_empty() {
        for target in &options.targets {
            for file in ai_target_files(root, *target, &options.categories, label_preset) {
                files.push(file);
            }
        }
        return files;
    }
    for target in &options.target_categories {
        for file in ai_target_files(root, target.target, &target.categories, label_preset) {
            files.push(file);
        }
    }
    files
}

fn ai_target_files(
    root: &Path,
    target: AiTarget,
    categories: &[AgentKitCategory],
    label_preset: LabelPreset,
) -> Vec<PlannedFile> {
    let entries = template_registry::templates_for_target(target.key());
    entries
        .into_iter()
        .filter(|entry| {
            AgentKitCategory::parse(entry.category).is_some_and(|cat| categories.contains(&cat))
        })
        .flat_map(|entry| expand_template_entry(root, entry, label_preset))
        .collect()
}

fn descriptor_match_suffixes(descriptor: &descriptor::Descriptor) -> Vec<String> {
    let mut suffixes = descriptor.match_suffixes.clone();
    if !suffixes.contains(&descriptor.language.primary_ext) {
        suffixes.push(descriptor.language.primary_ext.clone());
    }
    suffixes
}

fn expand_template_entry(
    root: &Path,
    entry: &template_registry::TemplateEntry,
    label_preset: LabelPreset,
) -> Vec<PlannedFile> {
    if !entry.output_path.contains("{{LANG_ID}}") && !entry.content.contains("{{LANG_ID}}") {
        return vec![PlannedFile {
            path: root.join(entry.output_path),
            content: apply_label_preset(entry.content, label_preset),
        }];
    }

    descriptor::builtin_language_descriptors()
        .into_iter()
        .map(|descriptor| PlannedFile {
            path: root.join(render_language_template(entry.output_path, &descriptor, label_preset)),
            content: render_language_template(entry.content, &descriptor, label_preset),
        })
        .collect()
}

fn render_language_template(
    template: &str,
    descriptor: &descriptor::Descriptor,
    label_preset: LabelPreset,
) -> String {
    let import_row = language_import_row();
    let import_statement = descriptor
        .render_import(&import_row)
        .unwrap_or_else(|| "// No generated import for this descriptor.".to_string());
    template
        .replace("{{LANG_ID}}", &descriptor.id)
        .replace("{{LANG_SUFFIXES}}", &descriptor_match_suffixes(descriptor).join(","))
        .replace("{{FENCE_LANG}}", &descriptor.language.primary_ext)
        .replace("{{IMPORT_STYLE}}", &descriptor.imports.style)
        .replace("{{IMPORT_ROW}}", "| internal | ./dep | ImportedSymbol | - | Dependency symbol. | [./dep.md#imported-symbol](./dep.md#imported-symbol) |")
        .replace("{{GENERATED_IMPORT}}", &import_statement)
        .replace("{{IMPORTS}}", &label_preset.section_label("imports"))
        .replace("{{EXPORTS}}", &label_preset.section_label("exports"))
        .replace("{{FROM}}", &label_preset.section_label("from"))
        .replace("{{TARGET}}", &label_preset.section_label("target"))
        .replace("{{SYMBOLS}}", &label_preset.section_label("symbols"))
        .replace("{{VIA}}", &label_preset.section_label("via"))
        .replace("{{SUMMARY}}", &label_preset.section_label("summary"))
        .replace("{{REFERENCE}}", &label_preset.section_label("reference"))
        .replace("{{NAME}}", &label_preset.section_label("name"))
        .replace("{{VISIBILITY}}", &label_preset.section_label("visibility"))
}

fn language_import_row() -> std::collections::HashMap<String, String> {
    std::collections::HashMap::from([
        ("from".to_string(), "internal".to_string()),
        ("target".to_string(), "./dep".to_string()),
        ("symbols".to_string(), "ImportedSymbol".to_string()),
        ("via".to_string(), "-".to_string()),
    ])
}

fn apply_label_preset(content: &str, preset: LabelPreset) -> String {
    let mut result = content.to_string();
    let replacements: &[(&str, &str)] = &[
        ("{{PURPOSE}}", "purpose"),
        ("{{CONTRACT}}", "contract"),
        ("{{TYPES}}", "types"),
        ("{{SOURCE}}", "source"),
        ("{{CASES}}", "cases"),
        ("{{TEST}}", "test"),
        ("{{COVERS}}", "covers"),
        ("{{IMPORTS}}", "imports"),
        ("{{EXPORTS}}", "exports"),
        ("{{EXPOSE}}", "expose"),
        ("{{FROM}}", "from"),
        ("{{TARGET}}", "target"),
        ("{{SYMBOLS}}", "symbols"),
        ("{{VIA}}", "via"),
        ("{{SUMMARY}}", "summary"),
        ("{{REFERENCE}}", "reference"),
        ("{{NAME}}", "name"),
        ("{{VISIBILITY}}", "visibility"),
    ];
    for (placeholder, key) in replacements {
        let label = preset.section_label(key);
        result = result.replace(placeholder, &label);
    }
    result
}

fn ai_post_init_guide(targets: &[AiTarget]) -> String {
    let mut guide = String::new();
    guide.push_str("\nIntegration guide:\n");
    for target in targets {
        guide.push_str(&format!("  {}: generated files follow template manifest output paths\n", target.key()));
    }
    guide
}

fn write_planned_file(file: &PlannedFile, force: bool, state: &mut RunState) -> Result<(), String> {
    if file.path.exists() && !is_mds_managed_file(&file.path) && !force {
        state.diagnostics.push(Diagnostic::error(
            Some(file.path.clone()),
            "refusing to overwrite non-managed file during init; re-run with --force after reviewing the diff",
        ));
        return Ok(());
    }
    if let Some(parent) = file.path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    fs::write(&file.path, &file.content)
        .map_err(|error| format!("failed to write {}: {error}", file.path.display()))?;
    state.generated.push(file.path.clone());
    Ok(())
}

fn setup_actions(
    _root: &Path,
    options: &InitOptions,
    package_manager: Option<&descriptor::PackageManagerManifest>,
) -> Vec<SetupAction> {
    let mut actions = Vec::new();
    if options.install_project_deps {
        if let Some(command) = package_manager.and_then(|manager| manager.command("install")) {
            actions.push(SetupAction {
                kind: "project-deps",
                command: split_command(command),
                install_hint: None,
            });
        }
    }
    if options.install_toolchains {
        for (tool, hint) in [
            (
                "node",
                "install Node.js 24+ from nodejs.org or a trusted version manager",
            ),
            ("rustc", "rustup toolchain install stable"),
            ("cargo", "rustup toolchain install stable"),
            (
                "python3",
                "install Python 3.13+ from python.org or a trusted package manager",
            ),
            ("uv", "python3 -m pip install --user uv"),
        ] {
            push_toolchain_check(&mut actions, tool, hint);
        }
        for tool in selected_quality_tools(options) {
            push_toolchain_check(&mut actions, &tool, quality_tool_hint(&tool));
        }
    }
    if options.install_ai_cli {
        for (tool, hint) in [
            ("claude", "npm install -g @anthropic-ai/claude-code"),
            ("codex", "npm install -g @openai/codex"),
            ("opencode", "npm install -g opencode-ai"),
            (
                "gh",
                "install GitHub CLI, then gh extension install github/gh-copilot",
            ),
        ] {
            actions.push(SetupAction {
                kind: "ai-cli-check",
                command: vec![tool.to_string(), "--version".to_string()],
                install_hint: Some(hint),
            });
        }
    }
    actions
}

fn selected_quality_tools(options: &InitOptions) -> Vec<String> {
    let mut tools = Vec::new();
    for descriptor in descriptor::builtin_language_descriptors() {
        let quality = quality_for_lang(options, Lang::Other(descriptor.id));
        for tool in quality.required.into_iter().chain(quality.optional) {
            add_unique(&mut tools, &tool);
        }
    }
    tools
}

fn push_toolchain_check(actions: &mut Vec<SetupAction>, tool: &str, hint: &'static str) {
    if actions.iter().any(|action| {
        action.kind == "toolchain-check" && action.command.first().is_some_and(|name| name == tool)
    }) {
        return;
    }
    actions.push(SetupAction {
        kind: "toolchain-check",
        command: vec![tool.to_string(), "--version".to_string()],
        install_hint: Some(hint),
    });
}

fn quality_tool_hint(tool: &str) -> &'static str {
    match tool {
        "tsc" => "npm install --save-dev typescript",
        "eslint" => "npm install --save-dev eslint",
        "prettier" => "npm install --save-dev prettier",
        "biome" => "npm install --save-dev @biomejs/biome",
        "vitest" => "npm install --save-dev vitest",
        "jest" => "npm install --save-dev jest",
        "mypy" => "uv add --dev mypy",
        "ruff" => "uv add --dev ruff",
        "black" => "uv add --dev black",
        "pytest" => "uv add --dev pytest",
        "rustfmt" => "rustup component add rustfmt",
        "clippy-driver" => "rustup component add clippy",
        "cargo-nextest" => "cargo install cargo-nextest",
        "node" => "install Node.js 24+ from nodejs.org or a trusted version manager",
        "python3" => "install Python 3.13+ from python.org or a trusted package manager",
        "rustc" | "cargo" => "rustup toolchain install stable",
        "uv" => "python3 -m pip install --user uv",
        _ => "install the selected quality tool from its official source",
    }
}

fn split_command(command: &str) -> Vec<String> {
    command.split_whitespace().map(ToOwned::to_owned).collect()
}

fn run_setup_action(root: &Path, action: &SetupAction, verbose: bool, state: &mut RunState) {
    if action.command.is_empty() {
        return;
    }
    if verbose {
        state.stdout.push_str(&format!(
            "running setup action: {}\n",
            action.command.join(" ")
        ));
    }
    let mut command = ProcessCommand::new(&action.command[0]);
    command.args(&action.command[1..]).current_dir(root);
    match command.output() {
        Ok(output) if output.status.success() => {
            state
                .stdout
                .push_str(&format!("setup ok: {}\n", action.command.join(" ")));
        }
        Ok(output) => {
            let detail = String::from_utf8_lossy(&output.stderr);
            state.diagnostics.push(Diagnostic::error(
                None,
                format!(
                    "setup action failed: {}{}{}",
                    action.command.join(" "),
                    if detail.trim().is_empty() {
                        String::new()
                    } else {
                        format!(": {}", detail.trim())
                    },
                    action
                        .install_hint
                        .map(|hint| format!("; install hint: {hint}"))
                        .unwrap_or_default()
                ),
            ));
        }
        Err(error) => {
            state.environment_missing = true;
            state.diagnostics.push(Diagnostic::error(
                None,
                format!(
                    "setup action could not start: {}: {error}{}",
                    action.command.join(" "),
                    action
                        .install_hint
                        .map(|hint| format!("; install hint: {hint}"))
                        .unwrap_or_default()
                ),
            ));
        }
    }
}

fn sanitize_package_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect()
}
