// Generated by mds. Do not edit. Source: .mds/source/init/mod.rs.md. Source-Hash: f7f2aa42409f462f621698697acb780c23af26985cdaa32f465cf29b95763ac6.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command as ProcessCommand;
use crate::descriptor;
use crate::diagnostics::{Diagnostic, RunState};
use crate::fs_utils::is_mds_managed_file;
use crate::model::{
AgentKitCategory, AiTarget, InitOptions, InitQualityCommands, LabelPreset, Lang, PythonTool,
RustTool, TypeScriptTool,
};
