// Generated by mds. Do not edit. Source: .mds/source/init/mod.rs.md. Source-Hash: 3998274b3b26072c1bc3b0d27327fb249893c941dca77f4b244a901a1537cb12.

use std::{fs};
use std::path::{Path};
use std::path::{PathBuf};
use std::process::{Command as ProcessCommand};
use crate::{descriptor};
use crate::diagnostics::{Diagnostic};
use crate::diagnostics::{RunState};
use crate::fs_utils::{is_mds_managed_file};
use crate::model::{AgentKitCategory};
use crate::model::{AiTarget};
use crate::model::{InitOptions};
use crate::model::{InitQualityCommands};
use crate::model::{LabelPreset};
use crate::model::{Lang};
use crate::model::{PythonTool};
use crate::model::{RustTool};
use crate::model::{TypeScriptTool};
