// Generated by mds. Do not edit. Source: mds-lsp/.mds/source/capabilities/mod.rs.md. Source-Hash: 1629377a4b6039d86f47e6eeb8bb2110e24a1c9ea90b45a3e7d26c349c5734ab.

pub mod code_action;

pub mod completion;

pub mod diagnostics;

pub mod hover;

pub mod navigation;

pub mod symbols;
