// Generated by mds. Do not edit. Source: .mds/source/args.rs.md. Source-Hash: b0acc2aaeea0a3cc3ed96d174bd986df042ad9adc8030f579661f3e7af3ed183.

use std::path::{PathBuf};
use mds_core::{AgentKitCategory};
use mds_core::{AiTarget};
use mds_core::{BuildMode};
use mds_core::{CliRequest};
use mds_core::{Command};
use mds_core::{DoctorFormat};
use mds_core::{InitOptions};
use mds_core::{LabelPreset};
use mds_core::{NewOptions};
use mds_core::{PythonTool};
use mds_core::{RustTool};
use mds_core::{TypeScriptTool};
