// Generated by mds. Do not edit. Source: .mds/source/main.rs.md. Source-Hash: d0a99ba5bbf3edca893ed706acc1bcc3e98c5ae5cdd4a60092cf63118b1ed270.

use mds_cli::args::{parse_args, print_usage};
use mds_cli::wizard::run_interactive_init;
use mds_core::{execute, CliRequest, Command};
use std::io::IsTerminal;
use std::process::Command as ProcessCommand;
