// Generated by mds. Do not edit. Source: .mds/source/wizard.rs.md. Source-Hash: 9e40a045b78ac264612b602cb77e04e14d72aaeb0eb324f6ec00969dc7d607a2.

use std::io::{self, stdout};
use std::path::Path;
use crossterm::{
event::{self, Event, KeyCode, KeyEventKind},
terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
ExecutableCommand,
};
use mds_core::{
descriptor,
AgentKitCategory, AiTarget, InitOptions, InitQualityCommands, InitTargetCategories,
LabelPreset, Lang,
};
use ratatui::{
prelude::*,
widgets::{Block, Borders, Clear, List, ListItem, ListState, Padding, Paragraph, Wrap},
};
