// Generated by mds. Do not edit. Source: .mds/source/capabilities/completion.rs.md. Source-Hash: 42a31b8acbc1ffdb3de0ebd8e06d5f5754ada2cd22ee33c98b9b98ac8d683913.

use std::path::{Path};
use mds_core::model::{Config};
use mds_core::model::{Lang};
use tower_lsp::lsp_types::{*};
use crate::convert::{line_at};
use crate::labels::{resolve_label};
