// Generated by mds. Do not edit. Source: .mds/source/capabilities/diagnostics.rs.md. Source-Hash: 167fdd481df99da22b5e63975572e0fcdd931aa7459c5d6d739f993f67244904.

use std::path::{Path};
use std::collections::{HashMap};
use mds_core::config::{merge_config_file};
use mds_core::descriptor::{set_workspace_descriptor_root};
use mds_core::descriptor::{fence_labels_for_lang};
use mds_core::descriptor::{is_root_module_markdown_path};
use mds_core::descriptor::{lang_for_markdown_path};
use mds_core::diagnostics::{RunState};
use mds_core::markdown::{extract_all_code_blocks};
use mds_core::markdown::{sections_with_labels};
use mds_core::markdown::{validate_markdown_links};
use mds_core::model::{Config};
use mds_core::model::{Lang};
use mds_core::table::{parse_table_with_labels};
use tower_lsp::{lsp_types};
use crate::convert::{to_lsp_diagnostic};
pub fn validate_impl_md_text(
    path: &Path,
    text: &str,
    _config: &Config,
) -> Vec<lsp_types::Diagnostic> {
    let mut state = RunState::default();
    set_workspace_descriptor_root(path.parent());

    // Validate markdown links
    validate_markdown_links(path, text, &mut state);

    // Validate that there is at least one code block
    let code = extract_all_code_blocks(text);
    let sections = sections_with_labels(text, &_config.label_overrides);
    let has_source_code = sections
        .get("Source")
        .is_some_and(|section| !extract_all_code_blocks(section).trim().is_empty());
    if code.trim().is_empty() && has_source_code {
        state.diagnostics.push(mds_core::Diagnostic::error(
            Some(path.to_path_buf()),
            "implementation md requires at least one code block",
        ));
    }
    validate_documented_source(path, text, &sections, &mut state);

    // Check language matching with file extension
    if let Some(ref lang) = lang_for_markdown_path(path) {
        validate_code_block_languages(text, lang, path, &mut state);
    }

    state.diagnostics.iter().map(to_lsp_diagnostic).collect()
}

fn validate_documented_source(
    path: &Path,
    text: &str,
    sections: &std::collections::HashMap<String, String>,
    state: &mut RunState,
) {
    if !sections.contains_key("Purpose") {
        state.diagnostics.push(mds_core::Diagnostic::error(
            Some(path.to_path_buf()),
            "source md requires ## Purpose",
        ));
    }
    if has_generated_source(sections) && !sections.contains_key("Contract") {
        state.diagnostics.push(mds_core::Diagnostic::error(
            Some(path.to_path_buf()),
            "impl md requires ## Contract",
        ));
    }
    validate_export_documentation(path, text, sections, state);
    validate_import_documentation(path, sections, state);
    if sections.contains_key("Types") {
        state.diagnostics.push(mds_core::Diagnostic::error(
            Some(path.to_path_buf()),
            "## Types is deprecated; move type definitions into ## Source",
        ));
    }
}

fn has_generated_source(sections: &std::collections::HashMap<String, String>) -> bool {
    sections
        .get("Source")
        .is_some_and(|section| !extract_all_code_blocks(section).trim().is_empty())
}

fn validate_export_documentation(
    path: &Path,
    text: &str,
    sections: &std::collections::HashMap<String, String>,
    state: &mut RunState,
) {
    let Some(section) = sections.get("Exports").or_else(|| sections.get("Expose")).or_else(|| sections.get("Exposes")) else {
        return;
    };
    let Some(rows) = table_rows(section) else {
        return;
    };
    let h5 = h5_sections(text);
    for row in rows {
        let name = row.get("name").map(String::as_str).unwrap_or_default().trim();
        if is_blank_cell(name) {
            continue;
        }
        let summary = row.get("summary").map(String::as_str).unwrap_or_default();
        if is_blank_cell(summary) {
            state.diagnostics.push(mds_core::Diagnostic::error(
                Some(path.to_path_buf()),
                format!("export `{name}` requires a non-empty Summary"),
            ));
        }
        if !is_root_module_markdown_path(path) {
            match h5.get(&slugify_heading(name)) {
                Some(section) if is_blank_cell(&section.prose) => state.diagnostics.push(mds_core::Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!("export `{name}` H5 shared definition requires explanatory prose"),
                )),
                Some(section) if has_generated_source(sections) && section.parent_section.as_deref() != Some("Source") => state.diagnostics.push(mds_core::Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!("export `{name}` H5 shared definition must be in ## Source before its code block"),
                )),
                Some(section) if has_generated_source(sections) && !section.before_code_block => state.diagnostics.push(mds_core::Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!("export `{name}` H5 shared definition must be followed by its Source code block"),
                )),
                Some(_) => {}
                None => state.diagnostics.push(mds_core::Diagnostic::error(
                    Some(path.to_path_buf()),
                    format!("export `{name}` requires a matching H5 shared definition"),
                )),
            }
        }
    }
}

fn validate_import_documentation(
    path: &Path,
    sections: &std::collections::HashMap<String, String>,
    state: &mut RunState,
) {
    let Some(section) = sections.get("Imports").or_else(|| sections.get("Uses")) else {
        return;
    };
    let Some(rows) = table_rows(section) else {
        return;
    };
    for row in rows {
        let from = row.get("from").map(String::as_str).unwrap_or_default().trim();
        let target = row.get("target").map(String::as_str).unwrap_or_default().trim();
        let reference = row.get("reference").map(String::as_str).unwrap_or_default();
        if is_blank_cell(from) && is_blank_cell(target) {
            continue;
        }
        let requires_reference = matches!(from, "internal" | "workspace" | "package");
        if requires_reference && is_blank_cell(reference) {
            state.diagnostics.push(mds_core::Diagnostic::error(
                Some(path.to_path_buf()),
                format!("import `{target}` requires a Markdown Reference link"),
            ));
        }
    }
}

fn table_rows(section: &str) -> Option<Vec<HashMap<String, String>>> {
    let lines = section.lines().collect::<Vec<_>>();
    for index in 0..lines.len().saturating_sub(1) {
        if !lines[index].trim_start().starts_with('|') || !lines[index + 1].contains("---") {
            continue;
        }
        let headers = split_row(lines[index])
            .into_iter()
            .map(|header| header.trim().to_ascii_lowercase())
            .collect::<Vec<_>>();
        let mut rows = Vec::new();
        for row_line in lines.iter().skip(index + 2) {
            if !row_line.trim_start().starts_with('|') {
                break;
            }
            let cells = split_row(row_line);
            let mut row = HashMap::new();
            for (cell_index, header) in headers.iter().enumerate() {
                row.insert(header.clone(), cells.get(cell_index).cloned().unwrap_or_default());
            }
            rows.push(row);
        }
        return Some(rows);
    }
    None
}

fn split_row(line: &str) -> Vec<String> {
    line.trim()
        .trim_matches('|')
        .split('|')
        .map(|cell| cell.trim().to_string())
        .collect()
}

struct H5Section {
    prose: String,
    parent_section: Option<String>,
    before_code_block: bool,
}

fn h5_sections(text: &str) -> HashMap<String, H5Section> {
    let mut sections = HashMap::new();
    let mut current: Option<String> = None;
    let mut current_parent: Option<String> = None;
    let mut body = String::new();
    let mut parent_section: Option<String> = None;
    for line in text.lines() {
        if current.is_none() {
            if let Some(title) = line.strip_prefix("## ") {
                parent_section = Some(title.trim().to_string());
            }
        }
        if let Some(title) = line.strip_prefix("##### ") {
            if let Some(anchor) = current.replace(slugify_heading(title.trim())) {
                sections.insert(anchor, h5_section(&body, current_parent.take()));
                body.clear();
            }
            current_parent = parent_section.clone();
        } else if line.starts_with("## ") || line.starts_with("### ") || line.starts_with("#### ") {
            if let Some(anchor) = current.take() {
                sections.insert(anchor, h5_section(&body, current_parent.take()));
                body.clear();
            }
            if let Some(title) = line.strip_prefix("## ") {
                parent_section = Some(title.trim().to_string());
            }
        } else if current.is_some() {
            body.push_str(line);
            body.push('\n');
        }
    }
    if let Some(anchor) = current {
        sections.insert(anchor, h5_section(&body, current_parent));
    }
    sections
}

fn h5_section(body: &str, parent_section: Option<String>) -> H5Section {
    H5Section {
        prose: prose_body(body),
        parent_section,
        before_code_block: body
            .lines()
            .map(str::trim_start)
            .any(|line| line.starts_with("```")),
    }
}

fn prose_body(body: &str) -> String {
    body.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('|') && !line.starts_with("```"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn is_blank_cell(value: &str) -> bool {
    let trimmed = value.trim().trim_matches('`');
    trimmed.is_empty() || trimmed == "-"
}

fn slugify_heading(value: &str) -> String {
    value
        .trim()
        .to_ascii_lowercase()
        .chars()
        .map(|character| if character.is_ascii_alphanumeric() { character } else { '-' })
        .collect::<String>()
        .trim_matches('-')
        .to_string()
}

pub fn validate_config_text(path: &Path, text: &str) -> Vec<lsp_types::Diagnostic> {
    let mut state = RunState::default();
    let mut config = Config::default();
    set_workspace_descriptor_root(path.parent());

    // Try to parse and merge the config
    match text.parse::<toml::Value>() {
        Ok(_value) => {
            // Use the existing config merge logic by writing to temp and reading
            // For now, validate through the existing merge path
            merge_config_file(&mut config, path, &mut state);
        }
        Err(error) => {
            // Extract line information from TOML parse error
            let msg = format!("TOML parse error: {error}");
            state
                .diagnostics
                .push(mds_core::Diagnostic::error(Some(path.to_path_buf()), msg));
        }
    }

    state.diagnostics.iter().map(to_lsp_diagnostic).collect()
}

#[allow(dead_code)]
pub fn validate_package_md_text(
    path: &Path,
    text: &str,
    config: &Config,
) -> Vec<lsp_types::Diagnostic> {
    let mut state = RunState::default();
    set_workspace_descriptor_root(path.parent());

    validate_markdown_links(path, text, &mut state);

    let sections = sections_with_labels(text, &config.label_overrides);
    for required in ["Package", "Dependencies", "Dev Dependencies", "Rules"] {
        if !sections.contains_key(required) {
            state.diagnostics.push(mds_core::Diagnostic::error(
                Some(path.to_path_buf()),
                format!("package overview requires ## {required}"),
            ));
        }
    }

    if let Some(package_section) = sections.get("Package") {
        if parse_table_with_labels(
            package_section,
            &["Name", "Version"],
            path,
            &config.label_overrides,
            &mut state,
        )
        .is_none()
        {
            state.diagnostics.push(mds_core::Diagnostic::error(
                Some(path.to_path_buf()),
                "package overview Package section requires Name and Version table columns",
            ));
        }
    }

    state.diagnostics.iter().map(to_lsp_diagnostic).collect()
}

fn validate_code_block_languages(
    text: &str,
    expected_lang: &Lang,
    path: &Path,
    state: &mut RunState,
) {
    let expected_labels = fence_labels_for_lang(expected_lang);

    for (idx, line) in text.lines().enumerate() {
        let trimmed = line.trim_start();
        if let Some(label) = opening_fence_label(trimmed) {
            if !label.is_empty()
                && !expected_labels.contains(&label)
                && label != "text"
                && label != "txt"
                && label != "markdown"
                && label != "md"
                && label != "toml"
                && label != "json"
                && label != "yaml"
                && label != "yml"
                && label != "sh"
                && label != "bash"
                && label != "shell"
            {
                state.diagnostics.push(
                    mds_core::Diagnostic::warning(
                        Some(path.to_path_buf()),
                        format!(
                            "code block language `{label}` may not match file language `{}`",
                            expected_lang.key()
                        ),
                    )
                    .at_line(idx + 1),
                );
            }
        }
    }
}

fn opening_fence_label(trimmed: &str) -> Option<String> {
    let marker_len = trimmed.chars().take_while(|character| *character == '`').count();
    if marker_len < 3 {
        return None;
    }
    let label = trimmed[marker_len..]
        .split_whitespace()
        .next()
        .unwrap_or_default()
        .to_ascii_lowercase();
    (!label.is_empty()).then_some(label)
}
