// Generated by mds. Do not edit. Source: .mds/source/capabilities/mod.rs.md. Source-Hash: c1942abf2f0964d2e445e86ee3ed33050960218020e275ff574219bfae0d2b6b.

pub mod code_action;

pub mod completion;

pub mod diagnostics;

pub mod hover;

pub mod navigation;

pub mod symbols;
