// Generated by mds. Do not edit. Source: .mds/source/capabilities/mod.rs.md. Source-Hash: 90483adb72044eb2dbd1144b552f2ef0d3d1460621350e43c21077154980cd93.

pub mod code_action;
pub mod completion;
pub mod diagnostics;
pub mod hover;
pub mod navigation;
pub mod symbols;
