// Generated by mds. Do not edit. Source: .mds/source/capabilities/navigation.rs.md. Source-Hash: 0043b532b7bdb6cebc63c5ca69095d00cfb30895bed898b2e03b92c4ea6de9f9.

use std::path::{Path};
use mds_core::markdown::{source_markdown_root};
use mds_core::model::{Lang};
use tower_lsp::lsp_types::{*};
use crate::convert::{line_at};
use crate::convert::{table_cell_at_position};
use crate::convert::{word_at_position};
use crate::state::{WorkspaceState};
