// Generated by mds. Do not edit. Source: .mds/source/capabilities/navigation.rs.md. Source-Hash: c520c978e6e3dd7b7dbdcf61b57677d34f56632cccd65d3c55fd22588d2d6231.

use std::path::Path;

use mds_core::markdown::source_markdown_root;
use mds_core::model::Lang;
use tower_lsp::lsp_types::*;

use crate::convert::{line_at, table_cell_at_position, word_at_position};
use crate::state::WorkspaceState;

pub fn goto_definition(
    text: &str,
    position: Position,
    path: &Path,
    state: &WorkspaceState,
) -> Option<GotoDefinitionResponse> {
    let line_text = line_at(text, position.line)?;

    // Check if cursor is in a Uses table row
    if !line_text.trim_start().starts_with('|') {
        return None;
    }

    // Try to resolve the target cell
    let cell = table_cell_at_position(text, position)?;
    if cell.is_empty() {
        return None;
    }

    // Reject path traversal attempts
    if cell.contains("..") || cell.starts_with('/') || cell.contains('\\') {
        return None;
    }

    let pkg_state = state.package_for_path(path)?;
    let package = &pkg_state.package;
    let markdown_root = source_markdown_root(package);

    // Try as internal target: resolve relative to markdown root
    let lang = Lang::from_path(path)?;
    let ext = match &lang {
        Lang::TypeScript => ".ts.md".to_string(),
        Lang::Python => ".py.md".to_string(),
        Lang::Rust => ".rs.md".to_string(),
        Lang::Other(e) => format!(".{e}.md"),
    };

    let target_path = markdown_root.join(format!("{cell}{ext}"));
    // Verify resolved path is within markdown root (path traversal prevention)
    if let (Ok(canonical_root), Ok(canonical_target)) =
        (markdown_root.canonicalize(), target_path.canonicalize())
    {
        if !canonical_target.starts_with(&canonical_root) {
            return None;
        }
    }

    if target_path.exists() {
        let uri = Url::from_file_path(&target_path).ok()?;
        return Some(GotoDefinitionResponse::Scalar(Location {
            uri,
            range: Range::default(),
        }));
    }

    // Try looking up in expose index
    let locations = state.find_expose_locations(&cell);
    if !locations.is_empty() {
        let locs: Vec<Location> = locations
            .iter()
            .filter_map(|p| {
                Url::from_file_path(p).ok().map(|uri| Location {
                    uri,
                    range: Range::default(),
                })
            })
            .collect();
        if locs.len() == 1 {
            return Some(GotoDefinitionResponse::Scalar(locs.into_iter().next()?));
        }
        return Some(GotoDefinitionResponse::Array(locs));
    }

    None
}

pub fn find_references(
    text: &str,
    position: Position,
    path: &Path,
    state: &WorkspaceState,
) -> Option<Vec<Location>> {
    let word = word_at_position(text, position)?;
    if word.is_empty() {
        return None;
    }

    let pkg_state = state.package_for_path(path)?;

    // Get this file's module stem
    let doc = pkg_state.index.docs.get(path)?;
    let stem = doc
        .markdown_relative_path
        .to_string_lossy()
        .replace(".md", "");

    // Search all docs for textual references to this stem or the word
    let mut locations = Vec::new();
    let mut seen_files = std::collections::HashSet::new();

    for doc_path in pkg_state.index.docs.keys() {
        if doc_path == path {
            continue;
        }
        let file_text = match std::fs::read_to_string(doc_path) {
            Ok(t) => t,
            Err(_) => continue,
        };
        for (idx, line) in file_text.lines().enumerate() {
            if line.contains(&stem) || line.contains(&word) {
                if !seen_files.insert((doc_path.clone(), idx)) {
                    continue;
                }
                if let Ok(uri) = Url::from_file_path(doc_path) {
                    let char_end = u32::try_from(line.len()).unwrap_or(u32::MAX);
                    locations.push(Location {
                        uri,
                        range: Range {
                            start: Position {
                                line: idx as u32,
                                character: 0,
                            },
                            end: Position {
                                line: idx as u32,
                                character: char_end,
                            },
                        },
                    });
                }
            }
        }
    }

    if locations.is_empty() {
        None
    } else {
        Some(locations)
    }
}
