// Generated by mds. Do not edit. Source: .mds/source/labels.rs.md. Source-Hash: 0f5baf1bf30f03b15a383fdb272bed9c39844d578fa1b64f5d1b371d5667d7fc.

use mds_core::model::{Config};
pub fn resolve_label(key: &str, config: &Config) -> String {
    if let Some(override_label) = config.label_overrides.get(key) {
        return override_label.clone();
    }
    // Default: capitalize first letter
    let mut chars = key.chars();
    match chars.next() {
        Some(first) => {
            let upper: String = first.to_uppercase().collect();
            format!("{upper}{}", chars.as_str())
        }
        None => key.to_string(),
    }
}
