// Generated by mds. Do not edit. Source: mds/lsp/.mds/source/labels.rs.md. Source-Hash: 5035dfc1110a7522677a3b457d5bb992d65173d76dda71c74a1bee83dec324cb.

use mds_core::model::Config;

/// Resolve a canonical label key to its display form using label overrides.

pub fn resolve_label(key: &str, config: &Config) -> String {
    if let Some(override_label) = config.label_overrides.get(key) {
        return override_label.clone();
    }
    // Default: capitalize first letter
    let mut chars = key.chars();
    match chars.next() {
        Some(first) => {
            let upper: String = first.to_uppercase().collect();
            format!("{upper}{}", chars.as_str())
        }
        None => key.to_string(),
    }
}
