// Generated by mds. Do not edit. Source: .mds/source/labels.rs.md. Source-Hash: ab5594332e6d59e3aef3ac6cd13e8dd02e4c38b7accfc2a47d2509a0db8297f1.

use mds_core::model::{Config};
pub fn resolve_label(key: &str, config: &Config) -> String {
    if let Some(override_label) = config.label_overrides.get(key) {
        return override_label.clone();
    }
    // Default: capitalize first letter
    let mut chars = key.chars();
    match chars.next() {
        Some(first) => {
            let upper: String = first.to_uppercase().collect();
            format!("{upper}{}", chars.as_str())
        }
        None => key.to_string(),
    }
}
