// Generated by mds. Do not edit. Source: .mds/source/main.rs.md. Source-Hash: d86ecb11092b354597b2eb2e0de4bb49e8cab386c9a1df737bec51cd88970da0.

use tower_lsp::{LspService, Server};
use tracing_subscriber::EnvFilter;

mod capabilities;

mod convert;

mod labels;

mod server;

mod state;

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .with_writer(std::io::stderr)
        .init();

    let stdin = tokio::io::stdin();
    let stdout = tokio::io::stdout();

    let (service, socket) = LspService::new(server::MdsLanguageServer::new);
    Server::new(stdin, stdout, socket).serve(service).await;
}
