// Generated by mds. Do not edit. Source: .mds/source/main.rs.md. Source-Hash: a0b528b15b2e7de6fa14d70135c7deb544ae279ab1d85537e683addc51bb932c.

use tower_lsp::{LspService};
use tower_lsp::{Server};
use tracing_subscriber::{EnvFilter};
mod capabilities;

mod convert;

mod labels;

mod server;

mod state;

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .with_writer(std::io::stderr)
        .init();

    let stdin = tokio::io::stdin();
    let stdout = tokio::io::stdout();

    let (service, socket) = LspService::new(server::MdsLanguageServer::new);
    Server::new(stdin, stdout, socket).serve(service).await;
}
