// Generated by mds. Do not edit. Source: .mds/source/state.rs.md. Source-Hash: faa42e7ecbd182dbe51021368fe169cf905c8df2e59f6ffc307fd0a32bd0d1c7.

use std::collections::{HashMap};
use std::path::{Path};
use std::path::{PathBuf};
use std::sync::{Arc};
use mds_core::{Config};
use mds_core::{ImplDoc};
use mds_core::{Lang};
use mds_core::{Package};
use tokio::sync::{RwLock};
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct OpenFile {
    pub uri: String,
    pub path: PathBuf,
    pub text: String,
    pub version: i32,
    pub lang: Option<Lang>,
}

#[allow(dead_code)]
#[derive(Debug, Clone, Default)]
pub struct WorkspaceIndex {
    pub docs: HashMap<PathBuf, ImplDoc>,
    pub expose_index: HashMap<String, Vec<PathBuf>>,
    pub file_exposes: HashMap<PathBuf, Vec<String>>,
}

#[derive(Debug, Clone)]
pub struct PackageState {
    pub package: Package,
    pub index: WorkspaceIndex,
}

#[allow(dead_code)]
#[derive(Debug, Default)]
pub struct WorkspaceState {
    pub workspace_folders: Vec<PathBuf>,
    pub open_files: HashMap<String, OpenFile>,
    pub packages: Vec<PackageState>,
    pub configs: HashMap<PathBuf, Config>,
}

pub type SharedState = Arc<RwLock<WorkspaceState>>;

#[allow(dead_code)]
impl WorkspaceState {
    pub fn package_for_path(&self, path: &Path) -> Option<&PackageState> {
        self.packages
            .iter()
            .find(|pkg| path.starts_with(&pkg.package.root))
    }
}

#[allow(dead_code)]
impl WorkspaceState {
    pub fn find_doc(&self, path: &Path) -> Option<&ImplDoc> {
        for pkg in &self.packages {
            if let Some(doc) = pkg.index.docs.get(path) {
                return Some(doc);
            }
        }
        None
    }
}

#[allow(dead_code)]
impl WorkspaceState {
    pub fn find_expose_locations(&self, name: &str) -> Vec<PathBuf> {
        let mut results = Vec::new();
        for pkg in &self.packages {
            if let Some(paths) = pkg.index.expose_index.get(name) {
                results.extend(paths.iter().cloned());
            }
        }
        results
    }
}
