// Generated by mds. Do not edit. Source: .mds/source/greet.rs.md. Source-Hash: 72d6e51f9572832d7d2022aa9ba17d8d9287f3ff76cbe6a1c6baec8d775c2a66.

pub struct GreetOptions {
    pub name: String,
}

pub fn greet(options: &GreetOptions) -> String {
    format!("Hello, {}!", options.name)
}
