// Generated by mds. Do not edit. Source: .mds/source/greet.rs.md. Source-Hash: 4ed30c9a0a42219e347439545adf5e41be3325afb9171272867f4bc559efa1b3.

pub struct GreetOptions {
    pub name: String,
}

pub fn greet(options: &GreetOptions) -> String {
    format!("Hello, {}!", options.name)
}
